# 02 Strict Test-Only Table Model Forecasting

This notebook trains one final model per ticker/model family/horizon under the strict protocol. Hyperparameters are tuned only inside the train block, model families are ranked on validation, and all final artifacts for `03_model_comparison.ipynb` are based on test predictions only. Mature tickers use a rolling maximum of the latest 5 trading years before validation/test fitting; shorter-history tickers use all available history and remain flagged.

In [1]:
from pathlib import Path
import os
import sys

cwd = Path.cwd().resolve()
for candidate in [cwd, cwd / "forecasting", cwd.parent, cwd.parent / "forecasting"]:
    if (candidate / "src" / "stock_forecast").exists():
        PROJECT_DIR = candidate
        break
else:
    raise RuntimeError("Cannot locate forecasting project directory with src/stock_forecast")

SRC_DIR = PROJECT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

ARTIFACT_DIR = PROJECT_DIR / "artifacts"
DATA_DIR = ARTIFACT_DIR / "data"
REPORTS_DIR = ARTIFACT_DIR / "reports"
PLOTS_DIR = ARTIFACT_DIR / "plots"
for path in [DATA_DIR, REPORTS_DIR, PLOTS_DIR]:
    path.mkdir(parents=True, exist_ok=True)

print(f"PROJECT_DIR = {PROJECT_DIR}")

PROJECT_DIR = /home/sapce/forecasting_stock_prices/forecasting

In [2]:
import importlib.util
import pandas as pd
from IPython.display import display

from stock_forecast.artifacts import load_json, load_table
from stock_forecast.mlflow_tracking import MLflowRunConfig, log_strict_protocol_result, mlflow_horizon_run
from stock_forecast.models import build_model
from stock_forecast.strict_protocol import run_strict_per_ticker_protocol

pd.set_option("display.max_columns", 160)

## Notebook Constants

In [3]:
FORCE_RETRAIN = False
PRIMARY_METRIC = "directional_accuracy"
RANDOM_STATE = 42
N_TRIALS = 25
OPTUNA_N_JOBS = 2

STRICT_VALIDATION_ROWS = 126
STRICT_TEST_ROWS = 126
MATURE_MIN_ROWS = 1008
LIMITED_HISTORY_MIN_BLOCK_ROWS = 42
MIN_TRAIN_ROWS = 60
STRICT_MAX_TRAIN_ROWS = 1260
INNER_MAX_FOLDS = 3
INNER_MIN_TRAIN_ROWS = 126
LIMITED_HISTORY_N_TRIALS = 8


TRANSACTION_COST_BPS = 10
SLIPPAGE_BPS = 5
LONG_THRESHOLD = 0.0
SIGNAL_ANCHOR = "expanding_median"

MLFLOW_ENABLED = os.environ.get("MLFLOW_ENABLED", "true").strip().lower() in {"1", "true", "yes", "y"}
MLFLOW_TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI", "http://localhost:5000")
MLFLOW_EXPERIMENT_NAME = os.environ.get("MLFLOW_EXPERIMENT_NAME", "stock_return_forecasting_research")
MLFLOW_LOG_OPTUNA_TRIALS = os.environ.get("MLFLOW_LOG_OPTUNA_TRIALS", "true").strip().lower() in {"1", "true", "yes", "y"}

HORIZONS = [
    {"name": "week", "horizon": 5},
    {"name": "month", "horizon": 21},
]

MOMENTUM_CANDIDATE_COLUMNS = [
    "ret_lag_1",
    "ret_lag_2",
    "ret_lag_3",
    "ret_lag_5",
    "ret_lag_10",
    "ret_lag_20",
    "rolling_ret_mean_5",
    "rolling_ret_mean_10",
    "rolling_ret_mean_20",
    "rolling_ret_mean_60",
]


def with_tuning(config: dict) -> dict:
    return {**config, "n_trials": N_TRIALS, "optuna_n_jobs": OPTUNA_N_JOBS}


def make_model_configs(feature_cols: list[str]) -> list[dict]:
    momentum_choices = [col for col in MOMENTUM_CANDIDATE_COLUMNS if col in feature_cols]
    configs = [
        {
            "name": "naive_persistence",
            "model_type": "naive_persistence",
            "estimator_factory": build_model,
            "static_params": {},
            "search_space": {},
            "needs_scaler": False,
        },
        with_tuning(
            {
                "name": "momentum",
                "model_type": "momentum",
                "estimator_factory": build_model,
                "static_params": {},
                "search_space": {"column": {"type": "categorical", "choices": momentum_choices}},
                "needs_scaler": False,
            }
        ),
        with_tuning(
            {
                "name": "ridge",
                "model_type": "ridge",
                "estimator_factory": build_model,
                "static_params": {},
                "search_space": {
                    "alpha": {"type": "float", "low": 1e-3, "high": 1e5, "log": True},
                    "solver": {"type": "categorical", "choices": ["auto", "svd", "cholesky", "lsqr"]},
                    "fit_intercept": {"type": "categorical", "choices": [True, False]},
                    "tol": {"type": "float", "low": 1e-6, "high": 1e-2, "log": True},
                },
                "needs_scaler": True,
            }
        ),
        with_tuning(
            {
                "name": "hist_gradient_boosting",
                "model_type": "hist_gradient_boosting",
                "estimator_factory": build_model,
                "static_params": {},
                "search_space": {
                    "max_iter": {"type": "int", "low": 20, "high": 400},
                    "learning_rate": {"type": "float", "low": 1e-3, "high": 0.1, "log": True},
                    "l2_regularization": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
                    "max_leaf_nodes": {"type": "int", "low": 3, "high": 31},
                    "max_depth": {"type": "categorical", "choices": [None, 2, 3, 4, 6, 8]},
                    "min_samples_leaf": {"type": "int", "low": 10, "high": 100},
                    "max_bins": {"type": "int", "low": 32, "high": 255},
                },
                "needs_scaler": False,
            }
        ),
    ]

    if importlib.util.find_spec("lightgbm") is not None:
        configs.append(
            with_tuning(
                {
                    "name": "lightgbm",
                    "model_type": "lightgbm",
                    "estimator_factory": build_model,
                    "static_params": {"objective": "regression", "verbosity": -1, "force_col_wise": True, "n_jobs": 1},
                    "search_space": {
                        "n_estimators": {"type": "int", "low": 25, "high": 400},
                        "learning_rate": {"type": "float", "low": 1e-3, "high": 0.1, "log": True},
                        "num_leaves": {"type": "int", "low": 2, "high": 64},
                        "max_depth": {"type": "categorical", "choices": [-1, 2, 3, 4, 6, 8, 10]},
                        "min_child_samples": {"type": "int", "low": 5, "high": 100},
                        "subsample": {"type": "float", "low": 0.5, "high": 1.0},
                        "subsample_freq": {"type": "int", "low": 1, "high": 10},
                        "colsample_bytree": {"type": "float", "low": 0.5, "high": 1.0},
                        "reg_alpha": {"type": "float", "low": 1e-8, "high": 10.0, "log": True},
                        "reg_lambda": {"type": "float", "low": 1e-3, "high": 100.0, "log": True},
                        "min_split_gain": {"type": "float", "low": 0.0, "high": 1.0},
                    },
                    "needs_scaler": False,
                }
            )
        )

    if importlib.util.find_spec("xgboost") is not None:
        configs.append(
            with_tuning(
                {
                    "name": "xgboost",
                    "model_type": "xgboost",
                    "estimator_factory": build_model,
                    "static_params": {"objective": "reg:squarederror", "verbosity": 0, "n_jobs": 1},
                    "search_space": {
                        "n_estimators": {"type": "int", "low": 25, "high": 400},
                        "learning_rate": {"type": "float", "low": 1e-3, "high": 0.1, "log": True},
                        "max_depth": {"type": "int", "low": 1, "high": 8},
                        "min_child_weight": {"type": "float", "low": 0.1, "high": 20.0, "log": True},
                        "subsample": {"type": "float", "low": 0.5, "high": 1.0},
                        "colsample_bytree": {"type": "float", "low": 0.5, "high": 1.0},
                        "reg_alpha": {"type": "float", "low": 1e-8, "high": 10.0, "log": True},
                        "reg_lambda": {"type": "float", "low": 1e-3, "high": 100.0, "log": True},
                        "gamma": {"type": "float", "low": 0.0, "high": 5.0},
                    },
                    "needs_scaler": False,
                }
            )
        )

    if importlib.util.find_spec("catboost") is not None:
        configs.append(
            with_tuning(
                {
                    "name": "catboost",
                    "model_type": "catboost",
                    "estimator_factory": build_model,
                    "static_params": {
                        "loss_function": "RMSE",
                        "verbose": False,
                        "allow_writing_files": False,
                        "thread_count": 1,
                        "grow_policy": "Depthwise",
                    },
                    "search_space": {
                        "iterations": {"type": "int", "low": 25, "high": 400},
                        "learning_rate": {"type": "float", "low": 1e-3, "high": 0.1, "log": True},
                        "depth": {"type": "int", "low": 2, "high": 8},
                        "l2_leaf_reg": {"type": "float", "low": 1e-2, "high": 100.0, "log": True},
                        "random_strength": {"type": "float", "low": 0.0, "high": 10.0},
                        "bagging_temperature": {"type": "float", "low": 0.0, "high": 10.0},
                        "border_count": {"type": "int", "low": 32, "high": 254},
                        "min_data_in_leaf": {"type": "int", "low": 1, "high": 50},
                    },
                    "needs_scaler": False,
                }
            )
        )

    return configs

## Load EDA Artifacts

In [4]:
horizon_inputs = []
base_feature_cols = None

for spec in HORIZONS:
    horizon_name = spec["name"]
    horizon_dir = DATA_DIR / "horizons" / horizon_name
    model_dataset_path = horizon_dir / "model_dataset.parquet"
    feature_columns_path = horizon_dir / "feature_columns.json"

    if horizon_name == "week" and not model_dataset_path.exists() and not model_dataset_path.with_suffix(".csv").exists():
        model_dataset_path = DATA_DIR / "model_dataset.parquet"
        feature_columns_path = DATA_DIR / "feature_columns.json"

    if not model_dataset_path.exists() and not model_dataset_path.with_suffix(".csv").exists():
        raise FileNotFoundError(f"Run notebooks/01_eda.ipynb before this notebook; missing {model_dataset_path}")
    if not feature_columns_path.exists():
        raise FileNotFoundError(f"Missing {feature_columns_path}. Run notebooks/01_eda.ipynb first")

    model_df = load_table(model_dataset_path)
    model_df["date"] = pd.to_datetime(model_df["date"])
    feature_payload = load_json(feature_columns_path)
    horizon_feature_cols = feature_payload["feature_columns"]
    target_col = feature_payload["target_column"]

    if base_feature_cols is None:
        base_feature_cols = horizon_feature_cols
    elif horizon_feature_cols != base_feature_cols:
        raise ValueError(f"Base feature columns differ for horizon {horizon_name}")

    model_configs = make_model_configs(horizon_feature_cols)
    horizon_inputs.append(
        {
            "horizon_name": feature_payload.get("horizon_name", horizon_name),
            "horizon": int(feature_payload.get("horizon", spec["horizon"])),
            "model_df": model_df,
            "feature_cols": horizon_feature_cols,
            "target_col": target_col,
            "model_configs": model_configs,
            "artifact_dir": ARTIFACT_DIR / "horizons" / horizon_name,
        }
    )

    print({
        "horizon": horizon_name,
        "rows": len(model_df),
        "features": len(horizon_feature_cols),
        "target": target_col,
        "models": [model["name"] for model in model_configs],
    })
    display(model_df[["date", "ticker", target_col, *horizon_feature_cols[:6]]].head())

{'horizon': 'week', 'rows': 19407, 'features': 127, 'target': 'target_return_5_next_open', 'models': ['naive_persistence', 'momentum', 'ridge', 'hist_gradient_boosting']}

,date,ticker,target_return_5_next_open,log_close,ret_1,open_close_ret,high_low_range,close_to_high,close_to_low
0,2015-11-09,CBOM,0.013316,1.321756,-0.003992,0.000000,0.000000,0.000000,0.000000
1,2015-11-10,CBOM,0.019908,1.320422,-0.001334,0.004013,0.004005,0.000000,0.004021
2,2015-11-11,CBOM,0.005312,1.319086,-0.001336,0.002677,0.002674,0.000000,0.002681
3,2015-11-12,CBOM,0.010582,1.323088,0.004003,0.000000,0.000000,0.000000,0.000000
4,2015-11-13,CBOM,-0.002649,1.329724,0.006636,0.005305,0.300265,-0.227783,0.005319

{'horizon': 'month', 'rows': 19295, 'features': 127, 'target': 'target_return_21_next_open', 'models': ['naive_persistence', 'momentum', 'ridge', 'hist_gradient_boosting']}

,date,ticker,target_return_21_next_open,log_close,ret_1,open_close_ret,high_low_range,close_to_high,close_to_low
0,2015-11-09,CBOM,0.027761,1.321756,-0.003992,0.000000,0.000000,0.000000,0.000000
1,2015-11-10,CBOM,0.023842,1.320422,-0.001334,0.004013,0.004005,0.000000,0.004021
2,2015-11-11,CBOM,0.021081,1.319086,-0.001336,0.002677,0.002674,0.000000,0.002681
3,2015-11-12,CBOM,0.021053,1.323088,0.004003,0.000000,0.000000,0.000000,0.000000
4,2015-11-13,CBOM,0.011834,1.329724,0.006636,0.005305,0.300265,-0.227783,0.005319

## Run Strict Protocol

In [5]:
horizon_results = {}

for item in horizon_inputs:
    horizon_name = item["horizon_name"]
    horizon = item["horizon"]
    mlflow_config = MLflowRunConfig(
        tracking_uri=MLFLOW_TRACKING_URI,
        experiment_name=MLFLOW_EXPERIMENT_NAME,
        notebook_name="02_table_model_forecasting",
        horizon_name=horizon_name,
        horizon=horizon,
        enabled=MLFLOW_ENABLED,
        log_optuna_trials=MLFLOW_LOG_OPTUNA_TRIALS,
    )
    mlflow_params = {
        "primary_metric": PRIMARY_METRIC,
        "force_retrain": FORCE_RETRAIN,
        "random_state": RANDOM_STATE,
        "n_trials": N_TRIALS,
        "optuna_n_jobs": OPTUNA_N_JOBS,
        "model_count": len(item["model_configs"]),
        "feature_count": len(item["feature_cols"]),
        "target_col": item["target_col"],
        "validation_rows": STRICT_VALIDATION_ROWS,
        "test_rows": STRICT_TEST_ROWS,
        "transaction_cost_bps": TRANSACTION_COST_BPS,
        "slippage_bps": SLIPPAGE_BPS,
        "signal_anchor": SIGNAL_ANCHOR,
    }
    with mlflow_horizon_run(
        mlflow_config,
        params=mlflow_params,
        tags={"training_protocol": "strict_table_models", "training_notebook": "02_table_model_forecasting"},
    ) as mlflow_run:
        result = run_strict_per_ticker_protocol(
            model_df=item["model_df"],
            feature_cols=item["feature_cols"],
            target_col=item["target_col"],
            model_configs=item["model_configs"],
            artifact_dir=item["artifact_dir"],
            force_retrain=FORCE_RETRAIN,
            primary_metric=PRIMARY_METRIC,
            random_state=RANDOM_STATE,
            run_metadata={"horizon_name": horizon_name, "horizon": horizon},
            validation_rows=STRICT_VALIDATION_ROWS,
            test_rows=STRICT_TEST_ROWS,
            mature_min_rows=MATURE_MIN_ROWS,
            limited_history_min_block_rows=LIMITED_HISTORY_MIN_BLOCK_ROWS,
            min_train_rows=MIN_TRAIN_ROWS,
            max_train_rows=STRICT_MAX_TRAIN_ROWS,
            inner_max_folds=INNER_MAX_FOLDS,
            inner_min_train_rows=INNER_MIN_TRAIN_ROWS,
            limited_history_n_trials=LIMITED_HISTORY_N_TRIALS,
            transaction_cost_bps=TRANSACTION_COST_BPS,
            slippage_bps=SLIPPAGE_BPS,
            long_threshold=LONG_THRESHOLD,
            signal_anchor=SIGNAL_ANCHOR,
            mlflow_trial_logger=mlflow_run.trial_logger,
        )
        log_strict_protocol_result(
            result,
            params=mlflow_params,
            tags={"training_protocol": "strict_table_models", "training_notebook": "02_table_model_forecasting"},
        )
    horizon_results[horizon_name] = result

    print(f"=== Strict protocol: {horizon_name} ({horizon} trading days) ===")
    display(result["outer_splits"])
    display(result["validation_model_ranking"])
    display(result["selected_models_by_ticker"])
    display(result["test_prediction_metrics"])
    display(result["test_signal_metrics"])
    display(result["leakage_audit"])

    failed = result["leakage_audit"][~result["leakage_audit"]["passed"]]
    if not failed.empty:
        raise AssertionError(f"Strict protocol leakage audit failed for {horizon_name}: {failed['check'].tolist()}")

🏃 View run week-momentum-trial-1 at: http://localhost:5000/#/experiments/2/runs/2cd60c4fa0dc47268bfed6e1ea71ecb8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-0 at: http://localhost:5000/#/experiments/2/runs/d26441ff9b434aed9b98fae171c51181
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-2 at: http://localhost:5000/#/experiments/2/runs/fc918229409f466992ab1288eea4e90a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-3 at: http://localhost:5000/#/experiments/2/runs/41b481552ac14ff3aec285b40d0081e2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-4 at: http://localhost:5000/#/experiments/2/runs/37a6350dbcf041ff882506b5d7625143
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-5 at: http://localhost:5000/#/experiments/2/runs/a05c8eb3aa7041c3b6b076bec344df4d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-6 at: http://localhost:5000/#/experiments/2/runs/06e2a18f305b48648a34b5e0c7508f83
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-7 at: http://localhost:5000/#/experiments/2/runs/970e740bf8c443f8ba0842a3a2e7c554
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-8 at: http://localhost:5000/#/experiments/2/runs/b0bcd44de51d431193007c73606042ce
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-9 at: http://localhost:5000/#/experiments/2/runs/e11d586508ee4b0388de4e93095091d6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-10 at: http://localhost:5000/#/experiments/2/runs/29e7808b07544a9d854577865db79e3f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-11 at: http://localhost:5000/#/experiments/2/runs/1aa9c38d2be549ae8a3ecc9fe1d25195
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-12 at: http://localhost:5000/#/experiments/2/runs/2674f7715a404431aaf4332ef1bf9026
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-13 at: http://localhost:5000/#/experiments/2/runs/26c1f5a2db554d348dc0f6e5791c2213
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-14 at: http://localhost:5000/#/experiments/2/runs/cf8ff5cb2cf84943bc540357b0df2c42
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-15 at: http://localhost:5000/#/experiments/2/runs/72b9e43e44d54e68a6310ffd12b4bb37
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-16 at: http://localhost:5000/#/experiments/2/runs/3a5c4d73d6264051a98566d32e021a14
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-17 at: http://localhost:5000/#/experiments/2/runs/7d29317830924868a8bb2943f7f51be7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-18 at: http://localhost:5000/#/experiments/2/runs/7150abbdf9ac4143b07a631caa205351
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-19 at: http://localhost:5000/#/experiments/2/runs/5ab386d5449040aa95d153a3d3189df9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-20 at: http://localhost:5000/#/experiments/2/runs/57db9cfa8d764aa792b83b631030039f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-21 at: http://localhost:5000/#/experiments/2/runs/07ff2dfd8f1141eebfee64b284ad97e3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-22 at: http://localhost:5000/#/experiments/2/runs/7af6e67dee0b4fd3b6b86069c9aa0e7d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-23 at: http://localhost:5000/#/experiments/2/runs/a19ae6ff278945e1a963b51b371c51a9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-24 at: http://localhost:5000/#/experiments/2/runs/8aa94353b5d8413194a8453d2a72ef64
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-1 at: http://localhost:5000/#/experiments/2/runs/f085b7ed962247feb330783bb2233261
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-0 at: http://localhost:5000/#/experiments/2/runs/813bc9b59bfe44aaabb32682a04889d9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-2 at: http://localhost:5000/#/experiments/2/runs/e9745a928c904b3ab2b800f146440366
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-3 at: http://localhost:5000/#/experiments/2/runs/b56bc52a2fb34622acdc19279e2ac188
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-4 at: http://localhost:5000/#/experiments/2/runs/7be145ecf15b471aa99b9c78d20d1a83
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-5 at: http://localhost:5000/#/experiments/2/runs/f70d795876234cd7b838befae874cc3a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-6 at: http://localhost:5000/#/experiments/2/runs/a75dcfbff2df4a638020c26839f8fd7b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-7 at: http://localhost:5000/#/experiments/2/runs/dbfc284933d24c23a06c30025f3c3abf
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-8 at: http://localhost:5000/#/experiments/2/runs/fc4f33f28dd643febc30390bb974c62b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-9 at: http://localhost:5000/#/experiments/2/runs/da5ba1522ae6483ca592221671747e77
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-10 at: http://localhost:5000/#/experiments/2/runs/e431a16af6d147b8b5e979cde2f7f1e6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-11 at: http://localhost:5000/#/experiments/2/runs/ab2c5059b72a4db1b580d9d21b3622b8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-12 at: http://localhost:5000/#/experiments/2/runs/e536e78c530948feaeffc85395d26056
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-13 at: http://localhost:5000/#/experiments/2/runs/701678aaa2db4c4c88426f09352e4a7b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-14 at: http://localhost:5000/#/experiments/2/runs/22f3ac65e1dd4300ad51f072b7d12396
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-15 at: http://localhost:5000/#/experiments/2/runs/47265516f64c44ed92cbc67e94691c71
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-16 at: http://localhost:5000/#/experiments/2/runs/f2ae19feaddd427c8f9b0f35599c0443
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-17 at: http://localhost:5000/#/experiments/2/runs/87ba9b4113634d3481e8b454d92a5399
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-18 at: http://localhost:5000/#/experiments/2/runs/8bb989a4f16748a7ae196d54cba40bb6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-19 at: http://localhost:5000/#/experiments/2/runs/d4260db69b374f9b847621a2f23a0dfb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-20 at: http://localhost:5000/#/experiments/2/runs/b08fd36a5bf14909b7595c143037d1b2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-21 at: http://localhost:5000/#/experiments/2/runs/4f582d4293074d1fa2aa81cbb4e1eaf8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-22 at: http://localhost:5000/#/experiments/2/runs/f441cdd04baa4dba920ba5e1ec227eb1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-23 at: http://localhost:5000/#/experiments/2/runs/b2f5fa9a864e4bb98542efac66e82dd4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-24 at: http://localhost:5000/#/experiments/2/runs/38b35f076d954e5a81f295094a1dabae
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-0 at: http://localhost:5000/#/experiments/2/runs/c59a28d9f253413f94047ce0fdccac43
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-1 at: http://localhost:5000/#/experiments/2/runs/c20a184989c84d05bee861f4226551e6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-2 at: http://localhost:5000/#/experiments/2/runs/242656f279dd42b6b8ec810c8e284441
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-3 at: http://localhost:5000/#/experiments/2/runs/d1f52aa19fc442b8a7dda1da17ceb953
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-5 at: http://localhost:5000/#/experiments/2/runs/8f1dc60e6ce1487390fd965f026551ff
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-4 at: http://localhost:5000/#/experiments/2/runs/816f1704fd2f4d8f8b4a996cf0fd54f0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-6 at: http://localhost:5000/#/experiments/2/runs/d014efbc02844d49a6678d0353536b8d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-7 at: http://localhost:5000/#/experiments/2/runs/abff0676e6f84cbe85c36066aac2995d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-8 at: http://localhost:5000/#/experiments/2/runs/99d40151aaba4e0c9e9ad1eae5e3cc88
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-9 at: http://localhost:5000/#/experiments/2/runs/b739943c63bd48a2a81bb53087daca1c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-10 at: http://localhost:5000/#/experiments/2/runs/20640352dc48425589a05e22c5a9acb7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-11 at: http://localhost:5000/#/experiments/2/runs/6419d5239fe74f7d8079bef5ab454536
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-13 at: http://localhost:5000/#/experiments/2/runs/01c5a8ce79964dd8af3725b97877d7c0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-12 at: http://localhost:5000/#/experiments/2/runs/7e1ec79d114e456fbe1001e5e438d9e6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-15 at: http://localhost:5000/#/experiments/2/runs/56a72952c4ff417b8873a7638d315d47
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-14 at: http://localhost:5000/#/experiments/2/runs/fcb7ba1be315488e85d8434a549356f4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-16 at: http://localhost:5000/#/experiments/2/runs/7af6eaa0d9bd42a18d65887f65c784d9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-17 at: http://localhost:5000/#/experiments/2/runs/3cc98ff473b447d89cc6443d0617534c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-18 at: http://localhost:5000/#/experiments/2/runs/84c167b95e814659bde2c3cf68a66a2b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-19 at: http://localhost:5000/#/experiments/2/runs/f4684f6b5b594082b5f7e9577236517d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-20 at: http://localhost:5000/#/experiments/2/runs/e4edac938de74126b60ce1cde8e8d9e0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-22 at: http://localhost:5000/#/experiments/2/runs/fd602791243247e68da5ba689fd359b7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-21 at: http://localhost:5000/#/experiments/2/runs/25b37e22a45847fab38507c9d7df37dc
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-23 at: http://localhost:5000/#/experiments/2/runs/5a69b705e86547f489c0d8f08f20ca4c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-24 at: http://localhost:5000/#/experiments/2/runs/6d897c238f0a429886f1e119aaf429ac
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-0 at: http://localhost:5000/#/experiments/2/runs/8e196b405780403aacfa2f3a428e21f0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-1 at: http://localhost:5000/#/experiments/2/runs/09b9bb8682e04c609c495faaaf80dbec
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-2 at: http://localhost:5000/#/experiments/2/runs/11687d80eda545969a973504d48f99d2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-3 at: http://localhost:5000/#/experiments/2/runs/0cb5c75cd4b941308fb8821c607a75c9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-4 at: http://localhost:5000/#/experiments/2/runs/c3d6735967d0440da1f6dfd2772b83ab
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-5 at: http://localhost:5000/#/experiments/2/runs/5712984a3d464d0385826afafa29f5d3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-6 at: http://localhost:5000/#/experiments/2/runs/666fea4605104469b1ed60a3c019e4c1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-7 at: http://localhost:5000/#/experiments/2/runs/3602c839ca564e0d968d1454fd4f4f56
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-1 at: http://localhost:5000/#/experiments/2/runs/bc45611ee04b4feb85b133eed962109b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-0 at: http://localhost:5000/#/experiments/2/runs/fa48e6bbc2c242baa25efa900ee4713b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-2 at: http://localhost:5000/#/experiments/2/runs/f9eeb8f9a2214af389e53cba7603a462
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-3 at: http://localhost:5000/#/experiments/2/runs/79ba9dc5c1084345846fc99e46041bf2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-4 at: http://localhost:5000/#/experiments/2/runs/740f08d4d1ea4f0c95fcadfe2ddb79dd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-5 at: http://localhost:5000/#/experiments/2/runs/ce64cd94a3ae472a9957b5ec8a77f4cc
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-6 at: http://localhost:5000/#/experiments/2/runs/2437c3b373d444d88b1e6f5c8cf300ee
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-ridge-trial-7 at: http://localhost:5000/#/experiments/2/runs/55af6a44dfec461fa21071d002e0e2a2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-0 at: http://localhost:5000/#/experiments/2/runs/9cc216bc89ea45518a3d530b63eacaf5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-1 at: http://localhost:5000/#/experiments/2/runs/64042096b453499dae2830307a87bd42
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-2 at: http://localhost:5000/#/experiments/2/runs/0ba43122a0784404b9513350456f97b9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-3 at: http://localhost:5000/#/experiments/2/runs/3783e39f09c24560a26265cd5a0d4ade
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-4 at: http://localhost:5000/#/experiments/2/runs/6a8f466852194101bb6b0fd96bf8d4c4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-5 at: http://localhost:5000/#/experiments/2/runs/112f87ebd9a14dc6bb25ab637867e5b4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-7 at: http://localhost:5000/#/experiments/2/runs/ebb0460b60e2441498e75485b96b055e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-hist_gradient_boosting-trial-6 at: http://localhost:5000/#/experiments/2/runs/db13b346cf7c425596a6a2140e87c355
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-1 at: http://localhost:5000/#/experiments/2/runs/5a80368176a64d279d261bcc41496636
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-0 at: http://localhost:5000/#/experiments/2/runs/a6fa2bf635c040a2a0e5d98954dce4ca
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-2 at: http://localhost:5000/#/experiments/2/runs/f5ddeef8c2ff4f92988f84f4075104ad
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-3 at: http://localhost:5000/#/experiments/2/runs/73b689ad684745b99e972a7e79cb78f8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-5 at: http://localhost:5000/#/experiments/2/runs/71130990d0e641f1930ffceaef82e3be
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-4 at: http://localhost:5000/#/experiments/2/runs/f127bd6b78d542ecb3a5c6b1b4497d52
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-6 at: http://localhost:5000/#/experiments/2/runs/d2e5bfc3be5a413d8c324629c7ac6f03
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-7 at: http://localhost:5000/#/experiments/2/runs/60d2b1cc9a5b4d939bb8d87a3b166387
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-8 at: http://localhost:5000/#/experiments/2/runs/3007e9b4f1ce4383bf48f5f55feab862
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-9 at: http://localhost:5000/#/experiments/2/runs/02a54237f6d04b6d9ec656e5a5f4babc
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-10 at: http://localhost:5000/#/experiments/2/runs/b4e83226dae44752bcccb11eb08de95f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-11 at: http://localhost:5000/#/experiments/2/runs/d28783ff30914500ab5215737d4d4f67
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-13 at: http://localhost:5000/#/experiments/2/runs/3c11e94b60c4409abf8b08f5f62d6bbe
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-momentum-trial-12 at: http://localhost:5000/#/experiments/2/runs/a2f92a049d994fb098c5ad2841b4d36c
🧪 View experiment at: http://localhost:5000/#/experiments/2

,ticker,status,split_quality,limited_history,n_obs,n_train_available,n_train,n_refit_available,n_refit,max_train_rows,n_validation,n_test,train_start,train_end,refit_start,refit_end,validation_start,validation_end,test_start,test_end,train_target_end,refit_target_end,validation_target_end,test_target_end,horizon_name,horizon
0,CBOM,ok,mature,False,2758,2506,1260,2632,1260,1260,126,126,2020-10-19,2025-09-02,2021-04-20,2026-01-24,2025-09-03,2026-01-24,2026-01-25,2026-06-07,2025-09-08,2026-01-30,2026-01-30,2026-06-13,week,5
1,MBNK,ok,limited_history,True,537,323,323,430,430,1260,107,107,2024-09-05,2025-10-12,2024-09-05,2026-02-12,2025-10-13,2026-02-12,2026-02-13,2026-06-07,2025-10-18,2026-02-20,2026-02-20,2026-06-13,week,5
2,SBER,ok,mature,False,4629,4377,1260,4503,1260,1260,126,126,2020-10-19,2025-09-02,2021-04-20,2026-01-24,2025-09-03,2026-01-24,2026-01-25,2026-06-07,2025-09-08,2026-01-30,2026-01-30,2026-06-13,week,5
3,SBERP,ok,mature,False,4629,4377,1260,4503,1260,1260,126,126,2020-10-19,2025-09-02,2021-04-20,2026-01-24,2025-09-03,2026-01-24,2026-01-25,2026-06-07,2025-09-08,2026-01-30,2026-01-30,2026-06-13,week,5
4,SVCB,ok,limited_history,True,636,384,384,510,510,1260,126,126,2024-04-27,2025-09-02,2024-04-27,2026-01-24,2025-09-03,2026-01-24,2026-01-25,2026-06-07,2025-09-08,2026-01-30,2026-01-30,2026-06-13,week,5
5,T,ok,mature,False,1633,1381,1260,1507,1260,1260,126,126,2020-09-07,2025-08-25,2021-03-09,2026-01-18,2025-08-26,2026-01-18,2026-01-19,2026-06-07,2025-08-31,2026-01-24,2026-01-24,2026-06-13,week,5
6,VTBR,ok,mature,False,4585,4333,1260,4459,1260,1260,126,126,2020-10-13,2025-09-02,2021-04-14,2026-01-24,2025-09-03,2026-01-24,2026-01-25,2026-06-07,2025-09-08,2026-01-30,2026-01-30,2026-06-13,week,5

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
2,validation,CBOM,naive_persistence,126,0.042964,0.059218,-0.245459,-0.034424,-0.010808,0.555556,week,5,mature,False,1254,1260,6,2506,1260,2020-10-19,2025-08-27,1,True
1,validation,CBOM,momentum,126,0.041241,0.053707,-0.024420,0.022708,0.006116,0.547619,week,5,mature,False,1254,1260,6,2506,1260,2020-10-19,2025-08-27,2,False
0,validation,CBOM,hist_gradient_boosting,126,0.041974,0.054412,-0.051477,0.006890,-0.019915,0.476190,week,5,mature,False,1254,1260,6,2506,1260,2020-10-19,2025-08-27,3,False
3,validation,CBOM,ridge,126,0.057110,0.072247,-0.853772,-0.137970,-0.188691,0.468254,week,5,mature,False,1254,1260,6,2506,1260,2020-10-19,2025-08-27,4,False
7,validation,MBNK,ridge,107,0.094680,0.107117,-11.783746,0.043888,0.053077,0.532710,week,5,limited_history,True,317,323,6,323,1260,2024-09-05,2025-10-06,1,True
6,validation,MBNK,naive_persistence,107,0.026817,0.035281,-0.386853,-0.123250,-0.138239,0.439252,week,5,limited_history,True,317,323,6,323,1260,2024-09-05,2025-10-06,2,False
4,validation,MBNK,hist_gradient_boosting,107,0.024833,0.033190,-0.227314,-0.363205,-0.311212,0.392523,week,5,limited_history,True,317,323,6,323,1260,2024-09-05,2025-10-06,3,False
5,validation,MBNK,momentum,107,0.025908,0.033969,-0.285618,-0.522973,-0.500735,0.355140,week,5,limited_history,True,317,323,6,323,1260,2024-09-05,2025-10-06,4,False
8,validation,SBER,hist_gradient_boosting,126,0.018699,0.025155,-0.201940,-0.011232,0.019777,0.507937,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,1,True
11,validation,SBER,ridge,126,0.017621,0.023261,-0.027785,0.097441,0.066805,0.484127,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,2,False
10,validation,SBER,naive_persistence,126,0.020417,0.027174,-0.402630,-0.152294,-0.175031,0.460317,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,3,False
9,validation,SBER,momentum,126,0.019919,0.027437,-0.429925,-0.179560,-0.139408,0.428571,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,4,False
15,validation,SBERP,ridge,126,0.016561,0.022423,0.001090,0.118673,0.125531,0.492063,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,1,True
13,validation,SBERP,momentum,126,0.018253,0.024840,-0.225827,0.023712,-0.040060,0.476190,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,2,False
12,validation,SBERP,hist_gradient_boosting,126,0.017802,0.023638,-0.110078,0.170646,0.090324,0.468254,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,3,False
14,validation,SBERP,naive_persistence,126,0.019701,0.026542,-0.399603,-0.146769,-0.174053,0.404762,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,4,False
19,validation,SVCB,ridge,126,0.026622,0.035697,-0.013759,-0.066305,-0.080510,0.571429,week,5,limited_history,True,378,384,6,384,1260,2024-04-27,2025-08-27,1,True
16,validation,SVCB,hist_gradient_boosting,126,0.033322,0.042887,-0.463220,-0.107953,-0.101079,0.515873,week,5,limited_history,True,378,384,6,384,1260,2024-04-27,2025-08-27,2,False
17,validation,SVCB,momentum,126,0.030793,0.040972,-0.335493,-0.132125,-0.105983,0.452381,week,5,limited_history,True,378,384,6,384,1260,2024-04-27,2025-08-27,3,False
18,validation,SVCB,naive_persistence,126,0.031329,0.040032,-0.274924,-0.064384,-0.074130,0.436508,week,5,limited_history,True,378,384,6,384,1260,2024-04-27,2025-08-27,4,False
23,validation,T,ridge,126,0.023720,0.031852,-0.011754,0.100464,0.022626,0.523810,week,5,mature,False,1254,1260,6,1381,1260,2020-09-07,2025-08-19,1,True
21,validation,T,momentum,126,0.023405,0.031995,-0.020867,-0.217321,-0.184006,0.492063,week,5,mature,False,1254,1260,6,1381,1260,2020-09-07,2025-08-19,2,False
20,validation,T,hist_gradient_boosting,126,0.024071,0.031774,-0.006815,0.080593,-0.012834,0.484127,week,5,mature,False,1254,1260,6,1381,1260,2020-09-07,2025-08-19,3,False
22,validation,T,naive_persistence,126,0.026440,0.035288,-0.241785,-0.059696,-0.028271,0.476190,week,5,mature,False,1254,1260,6,1381,1260,2020-09-07,2025-08-19,4,False
26,validation,VTBR,naive_persistence,126,0.024557,0.031739,-0.368296,-0.120858,-0.042301,0.515873,week,5,mature,False,1254,1260,6,4333,1260,2020-10-13,2025-08-27,1,True
24,validation,VTBR,hist_gradient_boosting,126,0.024147,0.030596,-0.271490,0.208087,0.143277,0.476190,week,5,mature,False,1254,1260,6,4333,1260,2020-10-13,2025-08-27,2,False
27,validation,VTBR,ridge,126,0.027799,0.035883,-0.748836,-0.139674,-0.064783,0.452381,week,5,mature,False,1254,1260,6,4333,1260,2020-10-13,2025-08-27,3,False
25,validation,VTBR,momentum,126,0.022139,0.028475,-0.101276,-0.168394,-0.127961,0.420635,week,5,mature,False,1254,1260,6,4333,1260,2020-10-13,2025-08-27,4,False

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
2,validation,CBOM,naive_persistence,126,0.042964,0.059218,-0.245459,-0.034424,-0.010808,0.555556,week,5,mature,False,1254,1260,6,2506,1260,2020-10-19,2025-08-27,1,True
7,validation,MBNK,ridge,107,0.094680,0.107117,-11.783746,0.043888,0.053077,0.532710,week,5,limited_history,True,317,323,6,323,1260,2024-09-05,2025-10-06,1,True
8,validation,SBER,hist_gradient_boosting,126,0.018699,0.025155,-0.201940,-0.011232,0.019777,0.507937,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,1,True
15,validation,SBERP,ridge,126,0.016561,0.022423,0.001090,0.118673,0.125531,0.492063,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,1,True
19,validation,SVCB,ridge,126,0.026622,0.035697,-0.013759,-0.066305,-0.080510,0.571429,week,5,limited_history,True,378,384,6,384,1260,2024-04-27,2025-08-27,1,True
23,validation,T,ridge,126,0.023720,0.031852,-0.011754,0.100464,0.022626,0.523810,week,5,mature,False,1254,1260,6,1381,1260,2020-09-07,2025-08-19,1,True
26,validation,VTBR,naive_persistence,126,0.024557,0.031739,-0.368296,-0.120858,-0.042301,0.515873,week,5,mature,False,1254,1260,6,4333,1260,2020-10-13,2025-08-27,1,True

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,hist_gradient_boosting,126,0.049230,0.090028,0.009173,0.112775,0.035261,0.428571,week,5,mature,False,1254,1260,6,2632,1260,2021-04-20,2026-01-18,3,False,0.476190
1,test,CBOM,momentum,126,0.045301,0.092775,-0.052203,-0.289441,-0.208165,0.507937,week,5,mature,False,1254,1260,6,2632,1260,2021-04-20,2026-01-18,2,False,0.547619
2,test,CBOM,naive_persistence,126,0.051369,0.103285,-0.304112,-0.063626,-0.098463,0.555556,week,5,mature,False,1254,1260,6,2632,1260,2021-04-20,2026-01-18,1,True,0.555556
3,test,CBOM,ridge,126,0.075575,0.129198,-1.040579,0.229357,0.414899,0.523810,week,5,mature,False,1254,1260,6,2632,1260,2021-04-20,2026-01-18,4,False,0.468254
4,test,MBNK,hist_gradient_boosting,107,0.013947,0.017689,-0.232208,NaN,NaN,0.327103,week,5,limited_history,True,424,430,6,430,1260,2024-09-05,2026-02-06,3,False,0.392523
5,test,MBNK,momentum,107,0.014253,0.017562,-0.214535,-0.007463,-0.072528,0.504673,week,5,limited_history,True,424,430,6,430,1260,2024-09-05,2026-02-06,4,False,0.355140
6,test,MBNK,naive_persistence,107,0.014817,0.019018,-0.424342,0.018761,0.064461,0.560748,week,5,limited_history,True,424,430,6,430,1260,2024-09-05,2026-02-06,2,False,0.439252
7,test,MBNK,ridge,107,0.084036,0.100423,-38.712928,0.127854,0.164091,0.691589,week,5,limited_history,True,424,430,6,430,1260,2024-09-05,2026-02-06,1,True,0.532710
8,test,SBER,hist_gradient_boosting,126,0.012301,0.015035,-1.026027,0.188845,0.158689,0.523810,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,1,True,0.507937
9,test,SBER,momentum,126,0.009175,0.011812,-0.250499,0.015127,0.033035,0.507937,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,4,False,0.428571
10,test,SBER,naive_persistence,126,0.009474,0.012013,-0.293530,-0.029871,-0.040576,0.436508,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,3,False,0.460317
11,test,SBER,ridge,126,0.008439,0.010501,0.011608,0.217748,0.216114,0.547619,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,2,False,0.484127
12,test,SBERP,hist_gradient_boosting,126,0.009575,0.011891,-0.357063,0.055610,0.050414,0.484127,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,3,False,0.468254
13,test,SBERP,momentum,126,0.009670,0.012284,-0.448282,-0.201397,-0.173693,0.468254,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,2,False,0.476190
14,test,SBERP,naive_persistence,126,0.009170,0.011543,-0.278806,-0.016076,-0.038614,0.476190,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,4,False,0.404762
15,test,SBERP,ridge,126,0.008096,0.010116,0.017765,0.137427,0.126413,0.587302,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,1,True,0.492063
16,test,SVCB,hist_gradient_boosting,126,0.026444,0.033334,-0.900656,-0.119753,-0.033302,0.492063,week,5,limited_history,True,504,510,6,510,1260,2024-04-27,2026-01-18,2,False,0.515873
17,test,SVCB,momentum,126,0.021046,0.025643,-0.124771,0.090458,0.058287,0.500000,week,5,limited_history,True,504,510,6,510,1260,2024-04-27,2026-01-18,3,False,0.452381
18,test,SVCB,naive_persistence,126,0.020751,0.025709,-0.130637,0.083513,0.114737,0.523810,week,5,limited_history,True,504,510,6,510,1260,2024-04-27,2026-01-18,4,False,0.436508
19,test,SVCB,ridge,126,0.019639,0.024321,-0.011818,-0.181224,-0.094105,0.571429,week,5,limited_history,True,504,510,6,510,1260,2024-04-27,2026-01-18,1,True,0.571429
20,test,T,hist_gradient_boosting,126,0.015729,0.020303,-0.041370,0.257065,0.191169,0.539683,week,5,mature,False,1254,1260,6,1507,1260,2021-03-09,2026-01-12,3,False,0.484127
21,test,T,momentum,126,0.015430,0.020368,-0.048098,0.060139,0.006764,0.492063,week,5,mature,False,1254,1260,6,1507,1260,2021-03-09,2026-01-12,2,False,0.492063
22,test,T,naive_persistence,126,0.017005,0.021431,-0.160295,0.066938,-0.054716,0.436508,week,5,mature,False,1254,1260,6,1507,1260,2021-03-09,2026-01-12,4,False,0.476190
23,test,T,ridge,126,0.015858,0.020495,-0.061234,0.188906,0.151628,0.420635,week,5,mature,False,1254,1260,6,1507,1260,2021-03-09,2026-01-12,1,True,0.523810
24,test,VTBR,hist_gradient_boosting,126,0.041849,0.051052,-0.623823,-0.073292,-0.090220,0.484127,week,5,mature,False,1254,1260,6,4459,1260,2021-04-14,2026-01-18,2,False,0.476190
25,test,VTBR,momentum,126,0.028272,0.039389,0.033359,0.183610,0.220937,0.611111,week,5,mature,False,1254,1260,6,4459,1260,2021-04-14,2026-01-18,4,False,0.420635
26,test,VTBR,naive_persistence,126,0.030503,0.041068,-0.050822,0.133270,0.124125,0.571429,week,5,mature,False,1254,1260,6,4459,1260,2021-04-14,2026-01-18,1,True,0.515873
27,test,VTBR,ridge,126,0.037220,0.050395,-0.582297,0.010101,0.045885,0.531746,week,5,mature,False,1254,1260,6,4459,1260,2021-04-14,2026-01-18,3,False,0.452381

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning
0,0.214283,0.474482,0.248480,252.0,1.909540,7.819554,-0.154210,3.076866,0.009524,6,CBOM,hist_gradient_boosting,overlapping_tranches,126,False
1,-0.136569,-0.254487,0.152930,252.0,-1.664078,-1.954048,-0.270754,-0.939919,0.026984,17,CBOM,momentum,overlapping_tranches,126,False
2,0.053857,0.110614,0.208993,252.0,0.529273,1.096572,-0.142612,0.775630,0.122222,77,CBOM,naive_persistence,overlapping_tranches,126,False
3,0.480102,1.190702,0.264684,252.0,4.498576,20.151122,-0.149173,7.982033,0.019048,12,CBOM,ridge,overlapping_tranches,126,False
4,-0.142081,-0.302962,0.050790,252.0,-5.965041,-8.656953,-0.164066,-1.846584,0.001869,1,MBNK,hist_gradient_boosting,overlapping_tranches,107,False
5,-0.045228,-0.103272,0.033710,252.0,-3.063530,-3.002311,-0.063253,-1.632694,0.041121,22,MBNK,momentum,overlapping_tranches,107,False
6,-0.085749,-0.190338,0.036698,252.0,-5.186620,-4.776796,-0.094866,-2.006395,0.099065,53,MBNK,naive_persistence,overlapping_tranches,107,False
7,-0.019240,-0.044724,0.021229,252.0,-2.106774,-1.221169,-0.021965,-2.036109,0.018692,10,MBNK,ridge,overlapping_tranches,107,False
8,-0.003021,-0.006034,0.007131,252.0,-0.846157,-0.312976,-0.006205,-0.972360,0.012698,8,SBER,hist_gradient_boosting,overlapping_tranches,126,False
9,0.000701,0.001403,0.024956,252.0,0.056202,0.079969,-0.021177,0.066231,0.109524,69,SBER,momentum,overlapping_tranches,126,False
10,-0.005598,-0.011165,0.024886,252.0,-0.448623,-0.662396,-0.023098,-0.483361,0.106349,67,SBER,naive_persistence,overlapping_tranches,126,False
11,0.033893,0.068934,0.027701,252.0,2.488488,4.045575,-0.016959,4.064791,0.071429,45,SBER,ridge,overlapping_tranches,126,False
12,-0.008570,-0.017066,0.008462,252.0,-2.016733,-0.797773,-0.011437,-1.492176,0.019048,12,SBERP,hist_gradient_boosting,overlapping_tranches,126,False
13,0.003548,0.007108,0.022897,252.0,0.310430,0.498685,-0.013445,0.528670,0.111111,70,SBERP,momentum,overlapping_tranches,126,False
14,-0.000467,-0.000934,0.025069,252.0,-0.037244,-0.056316,-0.021890,-0.042652,0.106349,67,SBERP,naive_persistence,overlapping_tranches,126,False
15,0.024419,0.049434,0.023317,252.0,2.120121,3.050123,-0.011807,4.186916,0.074603,47,SBERP,ridge,overlapping_tranches,126,False
16,-0.119802,-0.225251,0.062688,252.0,-3.593219,-5.159972,-0.149553,-1.506164,0.014286,9,SVCB,hist_gradient_boosting,overlapping_tranches,126,False
17,-0.054867,-0.106723,0.056588,252.0,-1.885976,-2.500219,-0.112656,-0.947336,0.098413,62,SVCB,momentum,overlapping_tranches,126,False
18,-0.042053,-0.082338,0.057367,252.0,-1.435287,-1.922554,-0.117914,-0.698283,0.096825,61,SVCB,naive_persistence,overlapping_tranches,126,False
19,-0.032085,-0.063140,0.027353,252.0,-2.308379,-1.203305,-0.032085,-1.967915,0.014286,9,SVCB,ridge,overlapping_tranches,126,False
20,-0.010804,-0.021491,0.044978,252.0,-0.477806,-0.677469,-0.073240,-0.293428,0.020635,13,T,hist_gradient_boosting,overlapping_tranches,126,False
21,-0.000766,-0.001532,0.042569,252.0,-0.035980,-0.055077,-0.057714,-0.026538,0.009524,6,T,momentum,overlapping_tranches,126,False
22,-0.078178,-0.150244,0.047358,252.0,-3.172545,-4.188129,-0.107401,-1.398904,0.109524,69,T,naive_persistence,overlapping_tranches,126,False
23,0.004720,0.009462,0.020764,252.0,0.455709,0.493796,-0.016001,0.591341,0.023810,15,T,ridge,overlapping_tranches,126,False
24,-0.104003,-0.197190,0.053917,252.0,-3.657276,-1.789749,-0.104003,-1.895997,0.020635,13,VTBR,hist_gradient_boosting,overlapping_tranches,126,False
25,0.133328,0.284433,0.071146,252.0,3.997887,7.035621,-0.043316,6.566520,0.031746,20,VTBR,momentum,overlapping_tranches,126,False
26,0.075942,0.157652,0.095365,252.0,1.653150,2.106687,-0.102839,1.533002,0.087302,55,VTBR,naive_persistence,overlapping_tranches,126,False
27,0.047355,0.096953,0.118182,252.0,0.820370,0.944308,-0.187597,0.516814,0.017460,11,VTBR,ridge,overlapping_tranches,126,False
28,0.157045,0.326790,0.570625,50.4,0.572689,1.961804,-0.171059,1.910396,0.230769,6,CBOM,hist_gradient_boosting,non_overlapping,26,False
29,-0.174564,-0.310564,0.352868,50.4,-0.880113,-1.127065,-0.308161,-1.007795,0.269231,7,CBOM,momentum,non_overlapping,26,False
30,-0.099526,-0.183899,0.333361,50.4,-0.551649,-0.712683,-0.260166,-0.706850,0.576923,15,CBOM,naive_persistence,non_overlapping,26,False
31,0.367749,0.835031,0.610667,50.4,1.367407,5.012899,-0.171059,4.881538,0.230769,6,CBOM,ridge,non_overlapping,26,False
32,-0.137625,-0.287663,0.111964,50.4,-2.569239,-3.485425,-0.174636,-1.647213,0.045455,1,MBNK,hist_gradient_boosting,non_overlapping,22,False
33,-0.023673,-0.053405,0.082696,50.4,-0.645794,-0.643441,-0.065574,-0.814421,0.272727,6,MBNK,momentum,non_overlapping,22,False
34,-0.043566,-0.097011,0.050847,50.4,-1.907910,-1.762229,-0.050394,-1.925066,0.636364,14,MBNK,naive_persistence,non_overlapping,22,False
35,0.001257,0.002881,0.009055,50.4,0.318191,1.703499,-0.004079,0.706312,0.181818,4,MBNK,ridge,non_overlapping,22,False
36,-0.003057,-0.005917,0.002954,50.4,-2.003205,-19.199735,-0.003057,-1.935681,0.076923,2,SBER,hist_gradient_boosting,non_overlapping,26,False
37,-0.040805,-0.077583,0.053102,50.4,-1.461017,-1.711850,-0.042285,-1.834755,0.423077,11,SBER,momentum,non_overlapping,26,False
38,0.015113,0.029504,0.060847,50.4,0.484890,1.097066,-0.035937,0.820992,0.500000,13,SBER,naive_persistence,non_overlapping,26,False
39,0.031007,0.060980,0.062748,50.4,0.971828,1.935339,-0.019486,3.129521,0.576923,15,SBER,ridge,non_overlapping,26,False
40,0.013066,0.025484,0.015954,50.4,1.597276,NaN,-0.001499,17.001782,0.153846,4,SBERP,hist_gradient_boosting,non_overlapping,26,False
41,0.016260,0.031760,0.046026,50.4,0.690057,1.165541,-0.024465,1.298186,0.538462,14,SBERP,momentum,non_overlapping,26,False
42,0.000400,0.000775,0.064703,50.4,0.011975,0.020417,-0.036224,0.021390,0.500000,13,SBERP,naive_persistence,non_overlapping,26,False
43,-0.002733,-0.005291,0.041359,50.4,-0.127940,-0.207998,-0.018115,-0.292108,0.500000,13,SBERP,ridge,non_overlapping,26,False
44,-0.136102,-0.246930,0.165504,50.4,-1.491993,-2.576427,-0.179215,-1.377840,0.115385,3,SVCB,hist_gradient_boosting,non_overlapping,26,False
45,-0.087113,-0.161951,0.117909,50.4,-1.373526,-2.040642,-0.128892,-1.256484,0.538462,14,SVCB,momentum,non_overlapping,26,False
46,-0.111925,-0.205541,0.126679,50.4,-1.622536,-2.261406,-0.152568,-1.347208,0.576923,15,SVCB,naive_persistence,non_overlapping,26,False
47,0.000757,0.001469,0.003842,50.4,0.382237,NaN,-0.001499,0.979793,0.076923,2,SVCB,ridge,non_overlapping,26,False
48,-0.023767,-0.045558,0.069905,50.4,-0.651717,-0.881708,-0.066014,-0.690130,0.269231,7,T,hist_gradient_boosting,non_overlapping,26,False
49,0.001182,0.002292,0.086426,50.4,0.026518,0.037938,-0.058862,0.038936,0.076923,2,T,momentum,non_overlapping,26,False
50,-0.092243,-0.171054,0.092801,50.4,-1.843230,-2.430574,-0.106819,-1.601353,0.576923,15,T,naive_persistence,non_overlapping,26,False
51,0.004098,0.007960,0.041928,50.4,0.189840,0.125403,-0.019787,0.402259,0.153846,4,T,ridge,non_overlapping,26,False
52,0.000000,0.000000,0.000000,50.4,NaN,NaN,0.000000,NaN,0.000000,0,VTBR,hist_gradient_boosting,non_overlapping,26,False
53,0.185225,0.390145,0.161968,50.4,2.408782,4.848381,-0.039257,9.938248,0.384615,10,VTBR,momentum,non_overlapping,26,False
54,-0.024315,-0.046596,0.220310,50.4,-0.211503,-0.179768,-0.148228,-0.314354,0.653846,17,VTBR,naive_persistence,non_overlapping,26,False
55,0.096061,0.194588,0.274046,50.4,0.710055,0.743793,-0.189557,1.026538,0.192308,5,VTBR,ridge,non_overlapping,26,False

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=3452
2,test predictions are available,True,rows=3452
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

🏃 View run month-momentum-trial-0 at: http://localhost:5000/#/experiments/2/runs/befd3ecdbaf44a19bbe335d617afdc54
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-1 at: http://localhost:5000/#/experiments/2/runs/7e475b20a3024938bf19a66b9ba1f239
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-2 at: http://localhost:5000/#/experiments/2/runs/1852d51704904f39b713b3b9d7b15e1e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-3 at: http://localhost:5000/#/experiments/2/runs/975df87d4ec54cf59d5741e9f2e88bef
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-4 at: http://localhost:5000/#/experiments/2/runs/0f0ffc0228f945fab31c13210d3fe102
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-5 at: http://localhost:5000/#/experiments/2/runs/3c0fdb97100746839206e458d8169be7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-6 at: http://localhost:5000/#/experiments/2/runs/b4f16f02e769466293af7682ec060f4d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-7 at: http://localhost:5000/#/experiments/2/runs/2ecf2fe0bada467fa30f0b504d82d5f0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-8 at: http://localhost:5000/#/experiments/2/runs/3037ff6fdea24eae93e23f3868d14f10
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-9 at: http://localhost:5000/#/experiments/2/runs/f49bec141dee49c283b9dfaa742bd35d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-10 at: http://localhost:5000/#/experiments/2/runs/fdd16572a00f4fdfb8addc1db3a2d654
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-11 at: http://localhost:5000/#/experiments/2/runs/826d0ae012b54a22bba9ba0d4b360053
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-13 at: http://localhost:5000/#/experiments/2/runs/194a70f22e0c48af9e3addc33bd955ce
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-12 at: http://localhost:5000/#/experiments/2/runs/af49fe8c6d6f4b6da690f8c176c6227f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-14 at: http://localhost:5000/#/experiments/2/runs/98f39da01caa43b0945f5444d65835b3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-15 at: http://localhost:5000/#/experiments/2/runs/908f4a581cc14a3fb648b47fda2f9173
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-16 at: http://localhost:5000/#/experiments/2/runs/e0657ce04dc141d1afef66a43a484edc
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-17 at: http://localhost:5000/#/experiments/2/runs/09965b64a8b14cd6b7aec02a555dbb37
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-18 at: http://localhost:5000/#/experiments/2/runs/9f9f54874d6045f5867d8bba34a77f70
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-19 at: http://localhost:5000/#/experiments/2/runs/3e5da7c8d79a4b6ab11cf14c67734ab3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-21 at: http://localhost:5000/#/experiments/2/runs/1fa253554d72409687de9c665035af0b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-20 at: http://localhost:5000/#/experiments/2/runs/3f6e6403a36f4a9aafc9103eef534ba2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-22 at: http://localhost:5000/#/experiments/2/runs/02dd4dc95c7c415abd563f9dc874b00e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-23 at: http://localhost:5000/#/experiments/2/runs/64c5121945cd4d6abeb4535e981ab06f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-24 at: http://localhost:5000/#/experiments/2/runs/c78ce10c72784472adafc4c7900d5e3f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-0 at: http://localhost:5000/#/experiments/2/runs/76a4730439094bee83aaefa725cfa3ec
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-1 at: http://localhost:5000/#/experiments/2/runs/671db4f362cc460ba44ac9d2c3ef4e8b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-3 at: http://localhost:5000/#/experiments/2/runs/db2b14fd5a284432bedd1e62e9c843e6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-2 at: http://localhost:5000/#/experiments/2/runs/8945eaa8c2f94196936882c65c9bde31
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-4 at: http://localhost:5000/#/experiments/2/runs/ca1088f812014b19a9246d523bdd7ccf
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-5 at: http://localhost:5000/#/experiments/2/runs/18ca1fef8aaf43888af3eb1a1c656103
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-6 at: http://localhost:5000/#/experiments/2/runs/1a69da24c3d24ab1ba3c89ff46b102ea
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-7 at: http://localhost:5000/#/experiments/2/runs/0991607acea44080b341fd1821cf0725
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-8 at: http://localhost:5000/#/experiments/2/runs/de8b61a70ae54752a91d76f9d0208e62
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-9 at: http://localhost:5000/#/experiments/2/runs/186cc315544a4aeb996751e7c2adfff5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-10 at: http://localhost:5000/#/experiments/2/runs/ddefe6e5f8ad40cbac216543cad11d31
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-11 at: http://localhost:5000/#/experiments/2/runs/1407421cc8c7463c87d40b871d6fffb3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-12 at: http://localhost:5000/#/experiments/2/runs/08410eb16d4c45d19d9398a218af6eaf
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-13 at: http://localhost:5000/#/experiments/2/runs/bd50f5c1d99e411faa4cdfe22a4f5a2a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-14 at: http://localhost:5000/#/experiments/2/runs/ed898fe6436a457f9a44ae954851ec39
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-15 at: http://localhost:5000/#/experiments/2/runs/39c75197d96a4f538de86125bf9905e2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-16 at: http://localhost:5000/#/experiments/2/runs/65dd45bc2b17490fbb81fe43215bc6c3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-17 at: http://localhost:5000/#/experiments/2/runs/237413c6de7f4abdb9808efc9b3f8627
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-18 at: http://localhost:5000/#/experiments/2/runs/ae875c677a9e46a59556e4cfcfadbf43
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-19 at: http://localhost:5000/#/experiments/2/runs/888bbde0479e46ba8df7ef88fd3d1c52
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-20 at: http://localhost:5000/#/experiments/2/runs/12a49ec30ba443d8b4349df60d0b83a6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-21 at: http://localhost:5000/#/experiments/2/runs/50f13052f64141b3887f7e0f56722824
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-22 at: http://localhost:5000/#/experiments/2/runs/300c203c27d1410ea92f3015d152e639
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-23 at: http://localhost:5000/#/experiments/2/runs/8c42578afa0d4549aae3e9a9b1819fd4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-24 at: http://localhost:5000/#/experiments/2/runs/2581057945f14879bff958df6eb4f425
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-1 at: http://localhost:5000/#/experiments/2/runs/b7f2ab37cb804559bd886cf8705c3285
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-0 at: http://localhost:5000/#/experiments/2/runs/c1cf0b638d33443b87f6fd59a9b41b81
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-2 at: http://localhost:5000/#/experiments/2/runs/9fd16cfb244d48b9982db3ddeac162a6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-3 at: http://localhost:5000/#/experiments/2/runs/cc4a4bf59ed544f79b141a367773b8f8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-5 at: http://localhost:5000/#/experiments/2/runs/ea0bbe45424e4d0ba3e0d7eb92365150
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-4 at: http://localhost:5000/#/experiments/2/runs/d68c5c798bbe4bcaa279b80e6df15bfb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-6 at: http://localhost:5000/#/experiments/2/runs/0ec6bc06e3ba432899c2ac2a8c01d908
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-8 at: http://localhost:5000/#/experiments/2/runs/d7793ad32d76478d823528dd252d2c74
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-7 at: http://localhost:5000/#/experiments/2/runs/9bd936b93c23465d8261daad9bc2f5e9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-9 at: http://localhost:5000/#/experiments/2/runs/e6e2e0df4b54441aae29f8afbae2afcb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-10 at: http://localhost:5000/#/experiments/2/runs/ceed8b43224841108dd428732b8d3658
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-12 at: http://localhost:5000/#/experiments/2/runs/c8c81a65e9c9448989f155a0b8978ae0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-11 at: http://localhost:5000/#/experiments/2/runs/6fcadcba6f19426fa277241e82256fb9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-14 at: http://localhost:5000/#/experiments/2/runs/57a7e175ae6d4303924ff26174c4a862
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-13 at: http://localhost:5000/#/experiments/2/runs/7e028203fcc1428dbd2cfdff5de4ba1a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-16 at: http://localhost:5000/#/experiments/2/runs/170ca4d98426438abea55a2615481d0f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-15 at: http://localhost:5000/#/experiments/2/runs/9433e95bd15d460db8694e0d4ef67de6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-17 at: http://localhost:5000/#/experiments/2/runs/78ea6ea3e6724f688bc77e6d5593e35f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-18 at: http://localhost:5000/#/experiments/2/runs/7f207dab09d044a8a8ffd39fbe97d549
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-19 at: http://localhost:5000/#/experiments/2/runs/a8744779192e4cdca5f132ce07888977
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-20 at: http://localhost:5000/#/experiments/2/runs/2cd13a6114774b02b7c12ec042bfab2a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-21 at: http://localhost:5000/#/experiments/2/runs/416ba2b2b756440e8487ffa0cafce881
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-22 at: http://localhost:5000/#/experiments/2/runs/4d02293c43e04197b9df3d0284a19e8e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-23 at: http://localhost:5000/#/experiments/2/runs/773a24d4af5d4ada9d69948d1099288e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-24 at: http://localhost:5000/#/experiments/2/runs/5080e34f28aa4d0d86657c9bbff0b947
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-0 at: http://localhost:5000/#/experiments/2/runs/80fa82f55a1841158415c2243cd4c7e0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-1 at: http://localhost:5000/#/experiments/2/runs/d4b10fd3c8974732b7bfa601095a840d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-2 at: http://localhost:5000/#/experiments/2/runs/67568dba88fe4fa294b9edd74d3cd2b2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-3 at: http://localhost:5000/#/experiments/2/runs/52437d46dd4741419a90b70bf881ccae
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-4 at: http://localhost:5000/#/experiments/2/runs/b5b5e729817141b0a6a6343ec0823842
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-5 at: http://localhost:5000/#/experiments/2/runs/dbbd2456a9fb4405b68994c270c60b8d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-6 at: http://localhost:5000/#/experiments/2/runs/0ace4fd283894711918889d6d8ac7853
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-7 at: http://localhost:5000/#/experiments/2/runs/2d2b8ef68be24950ab28850ad23b5563
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-0 at: http://localhost:5000/#/experiments/2/runs/ec3495d84ecb420e9bb0021ad930596f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-1 at: http://localhost:5000/#/experiments/2/runs/b1c2d9d23d4f47339d40d86220768806
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-3 at: http://localhost:5000/#/experiments/2/runs/d7861bd165ff4220b0cb868e07d60c65
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-2 at: http://localhost:5000/#/experiments/2/runs/e3dc368b127b46b386c82f4bcb238ad1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-4 at: http://localhost:5000/#/experiments/2/runs/18e60bd22c2e453494bb6fe6112535e5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-5 at: http://localhost:5000/#/experiments/2/runs/16b495f4c1c74e13af93a5dfa62b9b67
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-6 at: http://localhost:5000/#/experiments/2/runs/20b62d6ab2e24f6cad4a98854155cbea
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-ridge-trial-7 at: http://localhost:5000/#/experiments/2/runs/11025777800c4caca07bcecbcbcdeba7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-0 at: http://localhost:5000/#/experiments/2/runs/03dfb6ea6e3e4addbb5724a7a6c07804
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-1 at: http://localhost:5000/#/experiments/2/runs/90b6a648118a4ea4afdd42429392b148
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-2 at: http://localhost:5000/#/experiments/2/runs/3d3acbd2cc60490aa336622e086735e7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-3 at: http://localhost:5000/#/experiments/2/runs/c2111637c3d941be96b7c87877cd3f07
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-4 at: http://localhost:5000/#/experiments/2/runs/5a343f4beae146c69352579515dfa281
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-5 at: http://localhost:5000/#/experiments/2/runs/516ba8536554427fb6ec606ff46fad08
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-6 at: http://localhost:5000/#/experiments/2/runs/8535ca07065041d8b3ce73f2dc3e7463
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-hist_gradient_boosting-trial-7 at: http://localhost:5000/#/experiments/2/runs/17a0229bdcd04e6db0d36f73d9c650ef
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-1 at: http://localhost:5000/#/experiments/2/runs/ba9f1423809c415f9bbfa0e333aa18e1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-0 at: http://localhost:5000/#/experiments/2/runs/85c84c5f2ff5419e8eeab9caa36fc749
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-2 at: http://localhost:5000/#/experiments/2/runs/2357ebb49a0748bd98c78bb8133f0156
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-3 at: http://localhost:5000/#/experiments/2/runs/199635bff8f74688bee2728bc5b3163d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-5 at: http://localhost:5000/#/experiments/2/runs/04ad763d0eb944cfab6bed7288194999
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-4 at: http://localhost:5000/#/experiments/2/runs/88ca4e8d2251428d89ef0360648c224a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-6 at: http://localhost:5000/#/experiments/2/runs/dcc72f8e36384f84b716e66ff1fea2b5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-7 at: http://localhost:5000/#/experiments/2/runs/76f5fa74c00349bb8b2a31de3169c23c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-9 at: http://localhost:5000/#/experiments/2/runs/ca91adac46d247e49413d4c4fa7f423b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-8 at: http://localhost:5000/#/experiments/2/runs/5eab9c1332334a0eaf7e7da0c892c097
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-10 at: http://localhost:5000/#/experiments/2/runs/38a3efc7ad8e4c078d801f4466bd6bf6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-11 at: http://localhost:5000/#/experiments/2/runs/590e08ddf9a6473c90c37b7270917488
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-momentum-trial-12 at: http://localhost:5000/#/experiments/2/runs/0ed967e46d324f16b3cc3ecafba468b2
🧪 View experiment at: http://localhost:5000/#/experiments/2

,ticker,status,split_quality,limited_history,n_obs,n_train_available,n_train,n_refit_available,n_refit,max_train_rows,n_validation,n_test,train_start,train_end,refit_start,refit_end,validation_start,validation_end,test_start,test_end,train_target_end,refit_target_end,validation_target_end,test_target_end,horizon_name,horizon
0,CBOM,ok,mature,False,2742,2490,1260,2616,1260,1260,126,126,2020-09-25,2025-08-17,2021-03-29,2026-01-05,2025-08-18,2026-01-05,2026-01-06,2026-05-22,2025-09-08,2026-01-30,2026-01-30,2026-06-13,month,21
1,MBNK,ok,limited_history,True,521,313,313,417,417,1260,104,104,2024-09-05,2025-10-02,2024-09-05,2026-01-30,2025-10-03,2026-01-30,2026-01-31,2026-05-22,2025-10-24,2026-02-23,2026-02-23,2026-06-13,month,21
2,SBER,ok,mature,False,4613,4361,1260,4487,1260,1260,126,126,2020-09-25,2025-08-17,2021-03-29,2026-01-05,2025-08-18,2026-01-05,2026-01-06,2026-05-22,2025-09-08,2026-01-30,2026-01-30,2026-06-13,month,21
3,SBERP,ok,mature,False,4613,4361,1260,4487,1260,1260,126,126,2020-09-25,2025-08-17,2021-03-29,2026-01-05,2025-08-18,2026-01-05,2026-01-06,2026-05-22,2025-09-08,2026-01-30,2026-01-30,2026-06-13,month,21
4,SVCB,ok,limited_history,True,620,372,372,496,496,1260,124,124,2024-04-27,2025-08-21,2024-04-27,2026-01-08,2025-08-22,2026-01-08,2026-01-09,2026-05-22,2025-09-12,2026-02-01,2026-02-01,2026-06-13,month,21
5,T,ok,mature,False,1617,1365,1260,1491,1260,1260,126,126,2020-08-14,2025-08-07,2021-02-12,2025-12-25,2025-08-08,2025-12-25,2025-12-26,2026-05-22,2025-08-31,2026-01-24,2026-01-24,2026-06-13,month,21
6,VTBR,ok,mature,False,4569,4317,1260,4443,1260,1260,126,126,2020-09-21,2025-08-17,2021-03-23,2026-01-05,2025-08-18,2026-01-05,2026-01-06,2026-05-22,2025-09-08,2026-01-30,2026-01-30,2026-06-13,month,21

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
0,validation,CBOM,hist_gradient_boosting,126,0.093036,0.113505,-0.048585,0.388619,0.378322,0.777778,month,21,mature,False,1238,1260,22,2490,1260,2020-09-25,2025-07-22,1,True
2,validation,CBOM,naive_persistence,126,0.099125,0.119212,-0.156673,0.041701,0.054734,0.539683,month,21,mature,False,1238,1260,22,2490,1260,2020-09-25,2025-07-22,2,False
1,validation,CBOM,momentum,126,0.097398,0.119820,-0.168507,-0.284121,-0.268013,0.492063,month,21,mature,False,1238,1260,22,2490,1260,2020-09-25,2025-07-22,3,False
3,validation,CBOM,ridge,126,0.146563,0.169979,-1.351587,-0.273428,-0.428385,0.420635,month,21,mature,False,1238,1260,22,2490,1260,2020-09-25,2025-07-22,4,False
7,validation,MBNK,ridge,104,0.060376,0.073583,-3.841647,0.276997,0.014846,0.644231,month,21,limited_history,True,291,313,22,313,1260,2024-09-05,2025-09-08,1,True
5,validation,MBNK,momentum,104,0.038169,0.048485,-1.102135,-0.127077,-0.094170,0.519231,month,21,limited_history,True,291,313,22,313,1260,2024-09-05,2025-09-08,2,False
6,validation,MBNK,naive_persistence,104,0.037827,0.048219,-1.079135,-0.154034,-0.242047,0.480769,month,21,limited_history,True,291,313,22,313,1260,2024-09-05,2025-09-08,3,False
4,validation,MBNK,hist_gradient_boosting,104,0.044877,0.053186,-1.529513,0.379446,0.357186,0.192308,month,21,limited_history,True,291,313,22,313,1260,2024-09-05,2025-09-08,4,False
10,validation,SBER,naive_persistence,126,0.031213,0.038807,-0.149899,-0.051363,-0.087412,0.515873,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,1,True
8,validation,SBER,hist_gradient_boosting,126,0.030958,0.039400,-0.185308,0.495317,0.485675,0.476190,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,2,False
9,validation,SBER,momentum,126,0.032142,0.038763,-0.147281,-0.037751,-0.086530,0.468254,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,3,False
11,validation,SBER,ridge,126,0.031807,0.039980,-0.220420,-0.481181,-0.442346,0.468254,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,4,False
12,validation,SBERP,hist_gradient_boosting,126,0.028662,0.037981,-0.243323,0.061474,0.189155,0.492063,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,1,True
14,validation,SBERP,naive_persistence,126,0.029041,0.036790,-0.166599,-0.065691,-0.117390,0.484127,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,2,False
15,validation,SBERP,ridge,126,0.028750,0.037368,-0.203535,-0.374531,-0.318245,0.476190,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,3,False
13,validation,SBERP,momentum,126,0.029683,0.036549,-0.151376,-0.032408,-0.089854,0.444444,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,4,False
17,validation,SVCB,momentum,124,0.051505,0.073587,-0.159008,0.330616,0.313385,0.580645,month,21,limited_history,True,350,372,22,372,1260,2024-04-27,2025-07-26,1,True
18,validation,SVCB,naive_persistence,124,0.055624,0.076132,-0.240548,0.015528,-0.058316,0.443548,month,21,limited_history,True,350,372,22,372,1260,2024-04-27,2025-07-26,2,False
19,validation,SVCB,ridge,124,0.141102,0.168710,-5.091987,-0.300024,-0.363116,0.354839,month,21,limited_history,True,350,372,22,372,1260,2024-04-27,2025-07-26,3,False
16,validation,SVCB,hist_gradient_boosting,124,0.070733,0.089383,-0.709990,-0.338707,-0.342401,0.314516,month,21,limited_history,True,350,372,22,372,1260,2024-04-27,2025-07-26,4,False
21,validation,T,momentum,126,0.043278,0.051879,0.002100,0.128773,0.148820,0.587302,month,21,mature,False,1238,1260,22,1365,1260,2020-08-14,2025-07-14,1,True
20,validation,T,hist_gradient_boosting,126,0.043250,0.053049,-0.043417,NaN,NaN,0.539683,month,21,mature,False,1238,1260,22,1365,1260,2020-08-14,2025-07-14,2,False
23,validation,T,ridge,126,0.045086,0.056208,-0.171391,-0.231372,-0.257221,0.539683,month,21,mature,False,1238,1260,22,1365,1260,2020-08-14,2025-07-14,3,False
22,validation,T,naive_persistence,126,0.044760,0.053730,-0.070384,0.013566,0.013933,0.452381,month,21,mature,False,1238,1260,22,1365,1260,2020-08-14,2025-07-14,4,False
26,validation,VTBR,naive_persistence,126,0.040148,0.051510,-0.130428,-0.036380,-0.007778,0.515873,month,21,mature,False,1238,1260,22,4317,1260,2020-09-21,2025-07-22,1,True
24,validation,VTBR,hist_gradient_boosting,126,0.046850,0.057060,-0.387130,-0.036226,-0.132030,0.507937,month,21,mature,False,1238,1260,22,4317,1260,2020-09-21,2025-07-22,2,False
25,validation,VTBR,momentum,126,0.039744,0.050885,-0.103155,0.012009,0.039676,0.484127,month,21,mature,False,1238,1260,22,4317,1260,2020-09-21,2025-07-22,3,False
27,validation,VTBR,ridge,126,0.113472,0.129386,-6.132325,-0.322857,-0.226625,0.444444,month,21,mature,False,1238,1260,22,4317,1260,2020-09-21,2025-07-22,4,False

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
0,validation,CBOM,hist_gradient_boosting,126,0.093036,0.113505,-0.048585,0.388619,0.378322,0.777778,month,21,mature,False,1238,1260,22,2490,1260,2020-09-25,2025-07-22,1,True
7,validation,MBNK,ridge,104,0.060376,0.073583,-3.841647,0.276997,0.014846,0.644231,month,21,limited_history,True,291,313,22,313,1260,2024-09-05,2025-09-08,1,True
10,validation,SBER,naive_persistence,126,0.031213,0.038807,-0.149899,-0.051363,-0.087412,0.515873,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,1,True
12,validation,SBERP,hist_gradient_boosting,126,0.028662,0.037981,-0.243323,0.061474,0.189155,0.492063,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,1,True
17,validation,SVCB,momentum,124,0.051505,0.073587,-0.159008,0.330616,0.313385,0.580645,month,21,limited_history,True,350,372,22,372,1260,2024-04-27,2025-07-26,1,True
21,validation,T,momentum,126,0.043278,0.051879,0.002100,0.128773,0.148820,0.587302,month,21,mature,False,1238,1260,22,1365,1260,2020-08-14,2025-07-14,1,True
26,validation,VTBR,naive_persistence,126,0.040148,0.051510,-0.130428,-0.036380,-0.007778,0.515873,month,21,mature,False,1238,1260,22,4317,1260,2020-09-21,2025-07-22,1,True

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,hist_gradient_boosting,126,0.118204,0.146826,-0.180727,-0.595460,-0.557919,0.333333,month,21,mature,False,1238,1260,22,2616,1260,2021-03-29,2025-12-09,1,True,0.777778
1,test,CBOM,momentum,126,0.106287,0.140397,-0.079583,-0.501606,-0.501432,0.412698,month,21,mature,False,1238,1260,22,2616,1260,2021-03-29,2025-12-09,3,False,0.492063
2,test,CBOM,naive_persistence,126,0.107434,0.149980,-0.231998,-0.167621,-0.061099,0.523810,month,21,mature,False,1238,1260,22,2616,1260,2021-03-29,2025-12-09,2,False,0.539683
3,test,CBOM,ridge,126,0.186402,0.241538,-2.195327,0.167960,0.184780,0.396825,month,21,mature,False,1238,1260,22,2616,1260,2021-03-29,2025-12-09,4,False,0.420635
4,test,MBNK,hist_gradient_boosting,104,0.028938,0.035786,-0.486085,-0.304904,-0.277056,0.576923,month,21,limited_history,True,395,417,22,417,1260,2024-09-05,2026-01-05,4,False,0.192308
5,test,MBNK,momentum,104,0.034279,0.039127,-0.776441,0.023662,0.015982,0.528846,month,21,limited_history,True,395,417,22,417,1260,2024-09-05,2026-01-05,2,False,0.519231
6,test,MBNK,naive_persistence,104,0.033716,0.039425,-0.803652,-0.073353,-0.068746,0.509615,month,21,limited_history,True,395,417,22,417,1260,2024-09-05,2026-01-05,3,False,0.480769
7,test,MBNK,ridge,104,0.061310,0.076957,-5.872322,0.383606,0.249536,0.740385,month,21,limited_history,True,395,417,22,417,1260,2024-09-05,2026-01-05,1,True,0.644231
8,test,SBER,hist_gradient_boosting,126,0.011299,0.014679,0.014608,0.587916,0.584692,0.722222,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,2,False,0.476190
9,test,SBER,momentum,126,0.014083,0.018636,-0.588278,0.010913,0.046005,0.539683,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,3,False,0.468254
10,test,SBER,naive_persistence,126,0.014440,0.019163,-0.679299,-0.173842,-0.165894,0.460317,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,1,True,0.515873
11,test,SBER,ridge,126,0.012436,0.016087,-0.183443,-0.313462,-0.269555,0.722222,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,4,False,0.468254
12,test,SBERP,hist_gradient_boosting,126,0.018481,0.021358,-1.223099,0.571995,0.567765,0.634921,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,1,True,0.492063
13,test,SBERP,momentum,126,0.013881,0.018411,-0.652011,0.045213,0.064249,0.563492,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,4,False,0.444444
14,test,SBERP,naive_persistence,126,0.014607,0.019129,-0.783318,-0.192811,-0.207325,0.412698,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,2,False,0.484127
15,test,SBERP,ridge,126,0.012210,0.015738,-0.207123,-0.427014,-0.434547,0.738095,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,3,False,0.476190
16,test,SVCB,hist_gradient_boosting,124,0.050452,0.073400,-1.000012,-0.156543,0.026752,0.685484,month,21,limited_history,True,474,496,22,496,1260,2024-04-27,2025-12-11,4,False,0.314516
17,test,SVCB,momentum,124,0.044157,0.052952,-0.040916,0.056456,0.031396,0.685484,month,21,limited_history,True,474,496,22,496,1260,2024-04-27,2025-12-11,1,True,0.580645
18,test,SVCB,naive_persistence,124,0.043863,0.053004,-0.042926,0.100265,0.149496,0.556452,month,21,limited_history,True,474,496,22,496,1260,2024-04-27,2025-12-11,2,False,0.443548
19,test,SVCB,ridge,124,0.128173,0.139685,-6.243364,0.526623,0.566458,0.653226,month,21,limited_history,True,474,496,22,496,1260,2024-04-27,2025-12-11,3,False,0.354839
20,test,T,hist_gradient_boosting,126,0.032489,0.036365,-0.063414,NaN,NaN,0.642857,month,21,mature,False,1238,1260,22,1491,1260,2021-02-12,2025-12-01,2,False,0.539683
21,test,T,momentum,126,0.033145,0.037385,-0.123909,0.258413,0.187012,0.714286,month,21,mature,False,1238,1260,22,1491,1260,2021-02-12,2025-12-01,1,True,0.587302
22,test,T,naive_persistence,126,0.034190,0.039017,-0.224196,-0.028075,-0.004670,0.555556,month,21,mature,False,1238,1260,22,1491,1260,2021-02-12,2025-12-01,4,False,0.452381
23,test,T,ridge,126,0.032502,0.037081,-0.105733,0.482073,0.430911,0.642857,month,21,mature,False,1238,1260,22,1491,1260,2021-02-12,2025-12-01,3,False,0.539683
24,test,VTBR,hist_gradient_boosting,126,0.098736,0.115078,-0.350583,-0.038885,-0.009168,0.420635,month,21,mature,False,1238,1260,22,4443,1260,2021-03-23,2025-12-09,2,False,0.507937
25,test,VTBR,momentum,126,0.077751,0.099691,-0.013560,0.077275,0.095172,0.579365,month,21,mature,False,1238,1260,22,4443,1260,2021-03-23,2025-12-09,3,False,0.484127
26,test,VTBR,naive_persistence,126,0.077519,0.099563,-0.010966,0.085823,0.086725,0.571429,month,21,mature,False,1238,1260,22,4443,1260,2021-03-23,2025-12-09,1,True,0.515873
27,test,VTBR,ridge,126,0.181884,0.201908,-3.157642,-0.388750,-0.311652,0.325397,month,21,mature,False,1238,1260,22,4443,1260,2021-03-23,2025-12-09,4,False,0.444444

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning
0,-0.010447,-0.020784,0.090047,252.0,-0.230812,-0.495513,-0.131442,-0.158123,0.003023,8,CBOM,hist_gradient_boosting,overlapping_tranches,126,False
1,-0.108146,-0.204596,0.061078,252.0,-3.349759,-4.265798,-0.131553,-1.555239,0.005669,15,CBOM,momentum,overlapping_tranches,126,False
2,0.047283,0.096801,0.075697,252.0,1.278792,2.358569,-0.075795,1.277141,0.029478,78,CBOM,naive_persistence,overlapping_tranches,126,False
3,0.105911,0.223040,0.086624,252.0,2.574794,6.640956,-0.131442,1.696875,0.003401,9,CBOM,ridge,overlapping_tranches,126,False
4,-0.069830,-0.160880,0.019512,252.0,-8.245146,-8.943810,-0.075117,-2.141735,0.003205,7,MBNK,hist_gradient_boosting,overlapping_tranches,104,False
5,-0.055515,-0.129245,0.016308,252.0,-7.925334,-7.904145,-0.061176,-2.112670,0.023810,52,MBNK,momentum,overlapping_tranches,104,False
6,-0.062684,-0.145174,0.016600,252.0,-8.745503,-8.172379,-0.064829,-2.239321,0.024725,54,MBNK,naive_persistence,overlapping_tranches,104,False
7,-0.002301,-0.005566,0.010639,252.0,-0.523213,-0.408001,-0.014310,-0.388994,0.007326,16,MBNK,ridge,overlapping_tranches,104,False
8,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,SBER,hist_gradient_boosting,overlapping_tranches,126,False
9,0.032764,0.066602,0.009384,252.0,7.097276,37.184938,-0.001908,34.905982,0.029478,78,SBER,momentum,overlapping_tranches,126,False
10,0.023687,0.047934,0.008687,252.0,5.517897,18.621725,-0.003761,12.743404,0.026455,70,SBER,naive_persistence,overlapping_tranches,126,False
11,0.006185,0.012409,0.004122,252.0,3.010440,4.750501,-0.001494,8.303526,0.007559,20,SBER,ridge,overlapping_tranches,126,False
12,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,SBERP,hist_gradient_boosting,overlapping_tranches,126,False
13,0.038927,0.079369,0.009514,252.0,8.342019,49.246076,-0.001193,66.518427,0.027211,72,SBERP,momentum,overlapping_tranches,126,False
14,0.025704,0.052069,0.008479,252.0,6.140897,22.656617,-0.002780,18.732152,0.026455,70,SBERP,naive_persistence,overlapping_tranches,126,False
15,0.002446,0.004897,0.002795,252.0,1.752171,2.109130,-0.001460,3.354477,0.006803,18,SBERP,ridge,overlapping_tranches,126,False
16,-0.008062,-0.016316,0.004682,252.0,-3.484925,-1.497330,-0.008287,-1.968908,0.001536,4,SVCB,hist_gradient_boosting,overlapping_tranches,124,False
17,-0.003460,-0.007019,0.034658,252.0,-0.202521,-0.384604,-0.086445,-0.081196,0.004224,11,SVCB,momentum,overlapping_tranches,124,False
18,-0.017877,-0.035995,0.028412,252.0,-1.266884,-1.867574,-0.074030,-0.486223,0.023810,62,SVCB,naive_persistence,overlapping_tranches,124,False
19,-0.000660,-0.001340,0.000662,252.0,-2.024512,-0.458983,-0.000660,-2.031566,0.001536,4,SVCB,ridge,overlapping_tranches,124,False
20,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,T,hist_gradient_boosting,overlapping_tranches,126,False
21,-0.012079,-0.024012,0.019818,252.0,-1.211641,-1.566574,-0.050767,-0.472976,0.004913,13,T,momentum,overlapping_tranches,126,False
22,-0.045208,-0.088373,0.019552,252.0,-4.519954,-5.167874,-0.070826,-1.247745,0.027211,72,T,naive_persistence,overlapping_tranches,126,False
23,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,T,ridge,overlapping_tranches,126,False
24,0.024595,0.049794,0.069003,252.0,0.721626,0.866142,-0.139245,0.357601,0.004913,13,VTBR,hist_gradient_boosting,overlapping_tranches,126,False
25,0.108238,0.228191,0.053488,252.0,4.266206,5.669674,-0.063574,3.589364,0.021164,56,VTBR,momentum,overlapping_tranches,126,False
26,0.108122,0.227935,0.053744,252.0,4.241131,5.769092,-0.063563,3.585987,0.022298,59,VTBR,naive_persistence,overlapping_tranches,126,False
27,-0.063433,-0.122842,0.057586,252.0,-2.133204,-2.130684,-0.149778,-0.820161,0.006425,17,VTBR,ridge,overlapping_tranches,126,False
28,0.023385,0.047318,0.346785,12.0,0.136447,0.616568,-0.134556,0.351659,0.166667,1,CBOM,hist_gradient_boosting,non_overlapping,6,True
29,-0.099513,-0.189122,0.097454,12.0,-1.940641,-1.714602,-0.099513,-1.900487,0.500000,3,CBOM,momentum,non_overlapping,6,True
30,-0.133911,-0.249891,0.132306,12.0,-1.888734,-1.739397,-0.138441,-1.805029,0.666667,4,CBOM,naive_persistence,non_overlapping,6,True
31,0.058381,0.120171,0.340925,12.0,0.352485,0.841361,-0.134556,0.893097,0.333333,2,CBOM,ridge,non_overlapping,6,True
32,-0.026461,-0.062335,0.041546,12.0,-1.500391,NaN,-0.026461,-2.355702,0.200000,1,MBNK,hist_gradient_boosting,non_overlapping,5,True
33,-0.011557,-0.027512,0.013100,12.0,-2.100181,-1.794237,-0.010427,-2.638550,0.400000,2,MBNK,momentum,non_overlapping,5,True
34,-0.081344,-0.184231,0.077575,12.0,-2.374873,-2.374873,-0.080294,-2.294460,0.800000,4,MBNK,naive_persistence,non_overlapping,5,True
35,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,MBNK,ridge,non_overlapping,5,True
36,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,SBER,hist_gradient_boosting,non_overlapping,6,True
37,0.018405,0.037148,0.029582,12.0,1.255753,3.604609,-0.005691,6.527481,0.333333,2,SBER,momentum,non_overlapping,6,True
38,0.045342,0.092740,0.046529,12.0,1.993168,11.021318,-0.007181,12.913949,0.833333,5,SBER,naive_persistence,non_overlapping,6,True
39,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,SBER,ridge,non_overlapping,6,True
40,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,SBERP,hist_gradient_boosting,non_overlapping,6,True
41,0.016863,0.034010,0.030033,12.0,1.132411,2.341543,-0.007402,4.594628,0.333333,2,SBERP,momentum,non_overlapping,6,True
42,0.036106,0.073517,0.040250,12.0,1.826515,6.199097,-0.008890,8.269702,0.833333,5,SBERP,naive_persistence,non_overlapping,6,True
43,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,SBERP,ridge,non_overlapping,6,True
44,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,SVCB,hist_gradient_boosting,non_overlapping,6,True
45,0.067646,0.139867,0.155830,12.0,0.897566,1.245189,-0.047683,2.933295,0.333333,2,SVCB,momentum,non_overlapping,6,True
46,0.051990,0.106683,0.139174,12.0,0.766543,2.324117,-0.036337,2.935898,0.500000,3,SVCB,naive_persistence,non_overlapping,6,True
47,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,SVCB,ridge,non_overlapping,6,True
48,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,T,hist_gradient_boosting,non_overlapping,6,True
49,0.033760,0.068661,0.093312,12.0,0.735821,0.875780,-0.034401,1.995903,0.333333,2,T,momentum,non_overlapping,6,True
50,-0.017178,-0.034061,0.062114,12.0,-0.548362,-0.508272,-0.037293,-0.913322,0.666667,4,T,naive_persistence,non_overlapping,6,True
51,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,T,ridge,non_overlapping,6,True
52,0.082291,0.171355,0.125667,12.0,1.363565,4.550549,-0.016731,10.241517,0.500000,3,VTBR,hist_gradient_boosting,non_overlapping,6,True
53,0.161167,0.348308,0.193595,12.0,1.799157,10.321508,-0.019677,17.701494,0.833333,5,VTBR,momentum,non_overlapping,6,True
54,0.102449,0.215393,0.136540,12.0,1.577513,4.765093,-0.025276,8.521572,0.666667,4,VTBR,naive_persistence,non_overlapping,6,True
55,-0.018205,-0.036079,0.025983,12.0,-1.388546,NaN,-0.018205,-1.981795,0.166667,1,VTBR,ridge,non_overlapping,6,True

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=3432
2,test predictions are available,True,rows=3432
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

## Legacy Diagnostics

Legacy walk-forward OOF training is intentionally not part of the primary notebook flow. Final reports must use `strict_protocol/reports/test_predictions.parquet`; if legacy OOF diagnostics are needed later, keep them in a separate notebook/section and never feed them into final comparison plots.