# 02 Strict Test-Only Table Model Forecasting

This notebook trains one final model per ticker/model family/horizon under the strict protocol. Hyperparameters are tuned only inside the train block, model families are ranked on validation, and all final artifacts for `03_model_comparison.ipynb` are based on test predictions only. Mature tickers use a rolling maximum of the latest 5 trading years before validation/test fitting; shorter-history tickers use all available history and remain flagged.

In [1]:
from pathlib import Path
import sys

cwd = Path.cwd().resolve()
for candidate in [cwd, cwd / "forecasting", cwd.parent, cwd.parent / "forecasting"]:
    if (candidate / "src" / "stock_forecast").exists():
        PROJECT_DIR = candidate
        break
else:
    raise RuntimeError("Cannot locate forecasting project directory with src/stock_forecast")

SRC_DIR = PROJECT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

ARTIFACT_DIR = PROJECT_DIR / "artifacts"
DATA_DIR = ARTIFACT_DIR / "data"
REPORTS_DIR = ARTIFACT_DIR / "reports"
PLOTS_DIR = ARTIFACT_DIR / "plots"
for path in [DATA_DIR, REPORTS_DIR, PLOTS_DIR]:
    path.mkdir(parents=True, exist_ok=True)

print(f"PROJECT_DIR = {PROJECT_DIR}")

PROJECT_DIR = /Users/romankosenkov/Documents/HSE/year-project/forecasting_stock_prices/forecasting

In [2]:
import importlib.util
import pandas as pd
from IPython.display import display

from stock_forecast.artifacts import load_json, load_table
from stock_forecast.models import build_model
from stock_forecast.strict_protocol import run_strict_per_ticker_protocol

pd.set_option("display.max_columns", 160)

## Notebook Constants

In [3]:
FORCE_RETRAIN = False
PRIMARY_METRIC = "directional_accuracy"
RANDOM_STATE = 42
N_TRIALS = 25
OPTUNA_N_JOBS = 2

STRICT_VALIDATION_ROWS = 126
STRICT_TEST_ROWS = 126
MATURE_MIN_ROWS = 1008
LIMITED_HISTORY_MIN_BLOCK_ROWS = 42
MIN_TRAIN_ROWS = 60
STRICT_MAX_TRAIN_ROWS = 1260
INNER_MAX_FOLDS = 3
INNER_MIN_TRAIN_ROWS = 126
LIMITED_HISTORY_N_TRIALS = 8

LSTM_N_TRIALS = 60
LSTM_LIMITED_HISTORY_N_TRIALS = 20
LSTM_OPTUNA_N_JOBS = 1
LSTM_MAX_EPOCHS = 150
LSTM_PATIENCE = 15
LSTM_DEVICE = "auto"
LSTM_ENSEMBLE_SEEDS = [1, 7, 21, 42, 101]

TRANSACTION_COST_BPS = 10
SLIPPAGE_BPS = 5
LONG_THRESHOLD = 0.0
SIGNAL_ANCHOR = "expanding_median"

HORIZONS = [
    {"name": "week", "horizon": 5},
    {"name": "month", "horizon": 21},
]

MOMENTUM_CANDIDATE_COLUMNS = [
    "ret_lag_1",
    "ret_lag_2",
    "ret_lag_3",
    "ret_lag_5",
    "ret_lag_10",
    "ret_lag_20",
    "rolling_ret_mean_5",
    "rolling_ret_mean_10",
    "rolling_ret_mean_20",
    "rolling_ret_mean_60",
]


def with_tuning(config: dict) -> dict:
    return {**config, "n_trials": N_TRIALS, "optuna_n_jobs": OPTUNA_N_JOBS}


def make_lstm_search_space(horizon: int, limited_history: bool = False) -> dict:
    huber_beta_choices = [0.04, 0.08, 0.12] if horizon >= 21 else [0.02, 0.04, 0.06]
    return {
        "lookback": {"type": "categorical", "choices": [20, 40, 60] if limited_history else [20, 40, 60, 90, 126]},
        "hidden_size": {"type": "categorical", "choices": [16, 32, 64, 96, 128]},
        "num_layers": {"type": "categorical", "choices": [1] if limited_history else [1, 2]},
        "input_projection_size": {"type": "categorical", "choices": [0, 32, 64, 128]},
        "lstm_dropout": {"type": "float", "low": 0.0, "high": 0.35},
        "head_dropout": {"type": "float", "low": 0.15, "high": 0.55},
        "learning_rate": {"type": "float", "low": 1e-4, "high": 2e-3, "log": True},
        "weight_decay": {"type": "float", "low": 1e-5, "high": 1e-2, "log": True},
        "batch_size": {"type": "categorical", "choices": [16, 32, 64] if limited_history else [32, 64, 128]},
        "loss": {"type": "categorical", "choices": ["smooth_l1", "mse"]},
        "huber_beta": {"type": "categorical", "choices": huber_beta_choices},
        "feature_clip": {"type": "categorical", "choices": [3.0, 5.0, 8.0]},
        "grad_clip_norm": {"type": "float", "low": 0.5, "high": 2.0},
    }


def make_lstm_config(lstm_feature_cols: list[str], horizon: int) -> dict:
    return {
        "name": "lstm",
        "model_type": "lstm",
        "estimator_factory": build_model,
        "input_mode": "full_frame",
        "feature_cols": lstm_feature_cols,
        "static_params": {
            "max_epochs": LSTM_MAX_EPOCHS,
            "patience": LSTM_PATIENCE,
            "device": LSTM_DEVICE,
        },
        "search_space": make_lstm_search_space(horizon, limited_history=False),
        "limited_history_search_space": make_lstm_search_space(horizon, limited_history=True),
        "post_selection_static_params": {"ensemble_seeds": LSTM_ENSEMBLE_SEEDS},
        "n_trials": LSTM_N_TRIALS,
        "optuna_n_jobs": LSTM_OPTUNA_N_JOBS,
        "limited_history_n_trials": LSTM_LIMITED_HISTORY_N_TRIALS,
        "needs_scaler": False,
    }


def make_model_configs(feature_cols: list[str], lstm_feature_cols: list[str] | None, horizon: int) -> list[dict]:
    momentum_choices = [col for col in MOMENTUM_CANDIDATE_COLUMNS if col in feature_cols]
    configs = [
        {
            "name": "naive_persistence",
            "model_type": "naive_persistence",
            "estimator_factory": build_model,
            "static_params": {},
            "search_space": {},
            "needs_scaler": False,
        },
        with_tuning(
            {
                "name": "momentum",
                "model_type": "momentum",
                "estimator_factory": build_model,
                "static_params": {},
                "search_space": {"column": {"type": "categorical", "choices": momentum_choices}},
                "needs_scaler": False,
            }
        ),
        with_tuning(
            {
                "name": "ridge",
                "model_type": "ridge",
                "estimator_factory": build_model,
                "static_params": {},
                "search_space": {
                    "alpha": {"type": "float", "low": 1e-3, "high": 1e5, "log": True},
                    "solver": {"type": "categorical", "choices": ["auto", "svd", "cholesky", "lsqr"]},
                    "fit_intercept": {"type": "categorical", "choices": [True, False]},
                    "tol": {"type": "float", "low": 1e-6, "high": 1e-2, "log": True},
                },
                "needs_scaler": True,
            }
        ),
        with_tuning(
            {
                "name": "hist_gradient_boosting",
                "model_type": "hist_gradient_boosting",
                "estimator_factory": build_model,
                "static_params": {},
                "search_space": {
                    "max_iter": {"type": "int", "low": 20, "high": 400},
                    "learning_rate": {"type": "float", "low": 1e-3, "high": 0.1, "log": True},
                    "l2_regularization": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
                    "max_leaf_nodes": {"type": "int", "low": 3, "high": 31},
                    "max_depth": {"type": "categorical", "choices": [None, 2, 3, 4, 6, 8]},
                    "min_samples_leaf": {"type": "int", "low": 10, "high": 100},
                    "max_bins": {"type": "int", "low": 32, "high": 255},
                },
                "needs_scaler": False,
            }
        ),
    ]

    if importlib.util.find_spec("lightgbm") is not None:
        configs.append(
            with_tuning(
                {
                    "name": "lightgbm",
                    "model_type": "lightgbm",
                    "estimator_factory": build_model,
                    "static_params": {"objective": "regression", "verbosity": -1, "force_col_wise": True, "n_jobs": 1},
                    "search_space": {
                        "n_estimators": {"type": "int", "low": 25, "high": 400},
                        "learning_rate": {"type": "float", "low": 1e-3, "high": 0.1, "log": True},
                        "num_leaves": {"type": "int", "low": 2, "high": 64},
                        "max_depth": {"type": "categorical", "choices": [-1, 2, 3, 4, 6, 8, 10]},
                        "min_child_samples": {"type": "int", "low": 5, "high": 100},
                        "subsample": {"type": "float", "low": 0.5, "high": 1.0},
                        "subsample_freq": {"type": "int", "low": 1, "high": 10},
                        "colsample_bytree": {"type": "float", "low": 0.5, "high": 1.0},
                        "reg_alpha": {"type": "float", "low": 1e-8, "high": 10.0, "log": True},
                        "reg_lambda": {"type": "float", "low": 1e-3, "high": 100.0, "log": True},
                        "min_split_gain": {"type": "float", "low": 0.0, "high": 1.0},
                    },
                    "needs_scaler": False,
                }
            )
        )

    if importlib.util.find_spec("xgboost") is not None:
        configs.append(
            with_tuning(
                {
                    "name": "xgboost",
                    "model_type": "xgboost",
                    "estimator_factory": build_model,
                    "static_params": {"objective": "reg:squarederror", "verbosity": 0, "n_jobs": 1},
                    "search_space": {
                        "n_estimators": {"type": "int", "low": 25, "high": 400},
                        "learning_rate": {"type": "float", "low": 1e-3, "high": 0.1, "log": True},
                        "max_depth": {"type": "int", "low": 1, "high": 8},
                        "min_child_weight": {"type": "float", "low": 0.1, "high": 20.0, "log": True},
                        "subsample": {"type": "float", "low": 0.5, "high": 1.0},
                        "colsample_bytree": {"type": "float", "low": 0.5, "high": 1.0},
                        "reg_alpha": {"type": "float", "low": 1e-8, "high": 10.0, "log": True},
                        "reg_lambda": {"type": "float", "low": 1e-3, "high": 100.0, "log": True},
                        "gamma": {"type": "float", "low": 0.0, "high": 5.0},
                    },
                    "needs_scaler": False,
                }
            )
        )

    if importlib.util.find_spec("catboost") is not None:
        configs.append(
            with_tuning(
                {
                    "name": "catboost",
                    "model_type": "catboost",
                    "estimator_factory": build_model,
                    "static_params": {
                        "loss_function": "RMSE",
                        "verbose": False,
                        "allow_writing_files": False,
                        "thread_count": 1,
                        "grow_policy": "Depthwise",
                    },
                    "search_space": {
                        "iterations": {"type": "int", "low": 25, "high": 400},
                        "learning_rate": {"type": "float", "low": 1e-3, "high": 0.1, "log": True},
                        "depth": {"type": "int", "low": 2, "high": 8},
                        "l2_leaf_reg": {"type": "float", "low": 1e-2, "high": 100.0, "log": True},
                        "random_strength": {"type": "float", "low": 0.0, "high": 10.0},
                        "bagging_temperature": {"type": "float", "low": 0.0, "high": 10.0},
                        "border_count": {"type": "int", "low": 32, "high": 254},
                        "min_data_in_leaf": {"type": "int", "low": 1, "high": 50},
                    },
                    "needs_scaler": False,
                }
            )
        )

    if importlib.util.find_spec("torch") is not None and lstm_feature_cols:
        configs.append(make_lstm_config(lstm_feature_cols, horizon))

    return configs

## Load EDA Artifacts

In [4]:
horizon_inputs = []
base_feature_cols = None
TORCH_AVAILABLE = importlib.util.find_spec("torch") is not None

for spec in HORIZONS:
    horizon_name = spec["name"]
    horizon_dir = DATA_DIR / "horizons" / horizon_name
    model_dataset_path = horizon_dir / "model_dataset.parquet"
    feature_columns_path = horizon_dir / "feature_columns.json"

    if horizon_name == "week" and not model_dataset_path.exists() and not model_dataset_path.with_suffix(".csv").exists():
        model_dataset_path = DATA_DIR / "model_dataset.parquet"
        feature_columns_path = DATA_DIR / "feature_columns.json"

    if not model_dataset_path.exists() and not model_dataset_path.with_suffix(".csv").exists():
        raise FileNotFoundError(f"Run notebooks/01_eda.ipynb before this notebook; missing {model_dataset_path}")
    if not feature_columns_path.exists():
        raise FileNotFoundError(f"Missing {feature_columns_path}. Run notebooks/01_eda.ipynb first")

    model_df = load_table(model_dataset_path)
    model_df["date"] = pd.to_datetime(model_df["date"])
    feature_payload = load_json(feature_columns_path)
    horizon_feature_cols = feature_payload["feature_columns"]
    target_col = feature_payload["target_column"]
    lstm_feature_cols = None

    if TORCH_AVAILABLE:
        lstm_dir = DATA_DIR / "lstm" / "horizons" / horizon_name
        lstm_model_path = lstm_dir / "model_dataset.parquet"
        lstm_feature_path = lstm_dir / "feature_columns.json"
        if not lstm_model_path.exists() and not lstm_model_path.with_suffix(".csv").exists():
            raise FileNotFoundError(
                f"Missing LSTM artifacts for {horizon_name}: {lstm_model_path}. "
                "Run notebooks/01b_lstm_eda.ipynb before training LSTM."
            )
        if not lstm_feature_path.exists():
            raise FileNotFoundError(f"Missing LSTM feature payload for {horizon_name}: {lstm_feature_path}")
        lstm_payload = load_json(lstm_feature_path)
        if lstm_payload["target_column"] != target_col:
            raise ValueError(f"LSTM target mismatch for {horizon_name}: {lstm_payload['target_column']} != {target_col}")
        model_df = load_table(lstm_model_path)
        model_df["date"] = pd.to_datetime(model_df["date"])
        lstm_feature_cols = lstm_payload["feature_columns"]

    if base_feature_cols is None:
        base_feature_cols = horizon_feature_cols
    elif horizon_feature_cols != base_feature_cols:
        raise ValueError(f"Base feature columns differ for horizon {horizon_name}")

    model_configs = make_model_configs(horizon_feature_cols, lstm_feature_cols, int(feature_payload.get("horizon", spec["horizon"])))
    horizon_inputs.append(
        {
            "horizon_name": feature_payload.get("horizon_name", horizon_name),
            "horizon": int(feature_payload.get("horizon", spec["horizon"])),
            "model_df": model_df,
            "feature_cols": horizon_feature_cols,
            "lstm_feature_cols": lstm_feature_cols,
            "target_col": target_col,
            "model_configs": model_configs,
            "artifact_dir": ARTIFACT_DIR / "horizons" / horizon_name,
        }
    )

    print({
        "horizon": horizon_name,
        "rows": len(model_df),
        "base_features": len(horizon_feature_cols),
        "lstm_features": 0 if lstm_feature_cols is None else len(lstm_feature_cols),
        "target": target_col,
        "models": [model["name"] for model in model_configs],
    })
    display(model_df[["date", "ticker", target_col, *horizon_feature_cols[:6]]].head())

Models: ['naive_persistence', 'momentum', 'ridge', 'hist_gradient_boosting', 'lightgbm', 'xgboost', 'catboost']
{'horizon': 'week', 'rows': 17880, 'features': 127, 'target': 'target_return_5_next_open'}

,date,ticker,target_return_5_next_open,log_close,ret_1,open_close_ret,high_low_range,close_to_high,close_to_low
0,2015-11-09,CBOM,0.013316,1.321756,-0.003992,0.000000,0.000000,0.000000,0.000000
1,2015-11-10,CBOM,0.019908,1.320422,-0.001334,0.004013,0.004005,0.000000,0.004021
2,2015-11-11,CBOM,0.005312,1.319086,-0.001336,0.002677,0.002674,0.000000,0.002681
3,2015-11-12,CBOM,0.010582,1.323088,0.004003,0.000000,0.000000,0.000000,0.000000
4,2015-11-13,CBOM,-0.002649,1.329724,0.006636,0.005305,0.300265,-0.227783,0.005319

{'horizon': 'month', 'rows': 17768, 'features': 127, 'target': 'target_return_21_next_open'}

,date,ticker,target_return_21_next_open,log_close,ret_1,open_close_ret,high_low_range,close_to_high,close_to_low
0,2015-11-09,CBOM,0.027761,1.321756,-0.003992,0.000000,0.000000,0.000000,0.000000
1,2015-11-10,CBOM,0.023842,1.320422,-0.001334,0.004013,0.004005,0.000000,0.004021
2,2015-11-11,CBOM,0.021081,1.319086,-0.001336,0.002677,0.002674,0.000000,0.002681
3,2015-11-12,CBOM,0.021053,1.323088,0.004003,0.000000,0.000000,0.000000,0.000000
4,2015-11-13,CBOM,0.011834,1.329724,0.006636,0.005305,0.300265,-0.227783,0.005319

## Run Strict Protocol

In [5]:
horizon_results = {}

for item in horizon_inputs:
    horizon_name = item["horizon_name"]
    horizon = item["horizon"]
    result = run_strict_per_ticker_protocol(
        model_df=item["model_df"],
        feature_cols=item["feature_cols"],
        target_col=item["target_col"],
        model_configs=item["model_configs"],
        artifact_dir=item["artifact_dir"],
        force_retrain=FORCE_RETRAIN,
        primary_metric=PRIMARY_METRIC,
        random_state=RANDOM_STATE,
        run_metadata={"horizon_name": horizon_name, "horizon": horizon},
        validation_rows=STRICT_VALIDATION_ROWS,
        test_rows=STRICT_TEST_ROWS,
        mature_min_rows=MATURE_MIN_ROWS,
        limited_history_min_block_rows=LIMITED_HISTORY_MIN_BLOCK_ROWS,
        min_train_rows=MIN_TRAIN_ROWS,
        max_train_rows=STRICT_MAX_TRAIN_ROWS,
        inner_max_folds=INNER_MAX_FOLDS,
        inner_min_train_rows=INNER_MIN_TRAIN_ROWS,
        limited_history_n_trials=LIMITED_HISTORY_N_TRIALS,
        transaction_cost_bps=TRANSACTION_COST_BPS,
        slippage_bps=SLIPPAGE_BPS,
        long_threshold=LONG_THRESHOLD,
        signal_anchor=SIGNAL_ANCHOR,
    )
    horizon_results[horizon_name] = result

    print(f"=== Strict protocol: {horizon_name} ({horizon} trading days) ===")
    display(result["outer_splits"])
    display(result["validation_model_ranking"])
    display(result["selected_models_by_ticker"])
    display(result["test_prediction_metrics"])
    display(result["test_signal_metrics"])
    display(result["leakage_audit"])

    failed = result["leakage_audit"][~result["leakage_audit"]["passed"]]
    if not failed.empty:
        raise AssertionError(f"Strict protocol leakage audit failed for {horizon_name}: {failed['check'].tolist()}")

=== Strict protocol: week (5 trading days) ===

,ticker,status,split_quality,limited_history,n_obs,n_train_available,n_train,n_refit_available,n_refit,max_train_rows,n_validation,n_test,train_start,train_end,refit_start,refit_end,validation_start,validation_end,test_start,test_end,train_target_end,refit_target_end,validation_target_end,test_target_end,horizon_name,horizon
0,CBOM,ok,mature,False,2539,2287,1260,2413,1260,1260,126,126,2019-12-02,2024-12-17,2020-06-05,2025-05-23,2024-12-18,2025-05-23,2025-05-26,2025-10-07,2024-12-25,2025-05-31,2025-05-31,2025-10-13,week,5
1,MBNK,ok,limited_history,True,318,190,190,254,254,1260,64,64,2024-09-05,2025-05-21,2024-09-05,2025-07-29,2025-05-22,2025-07-29,2025-07-30,2025-10-07,2025-05-29,2025-08-06,2025-08-06,2025-10-13,week,5
2,SBER,ok,mature,False,4410,4158,1260,4284,1260,1260,126,126,2019-12-02,2024-12-17,2020-06-05,2025-05-23,2024-12-18,2025-05-23,2025-05-26,2025-10-07,2024-12-25,2025-05-31,2025-05-31,2025-10-13,week,5
3,SBERP,ok,mature,False,4410,4158,1260,4284,1260,1260,126,126,2019-12-02,2024-12-17,2020-06-05,2025-05-23,2024-12-18,2025-05-23,2025-05-26,2025-10-07,2024-12-25,2025-05-31,2025-05-31,2025-10-13,week,5
4,SVCB,ok,limited_history,True,417,251,251,334,334,1260,83,83,2024-04-27,2025-04-09,2024-04-27,2025-07-10,2025-04-10,2025-07-10,2025-07-11,2025-10-07,2025-04-15,2025-07-16,2025-07-16,2025-10-13,week,5
5,T,ok,mature,False,1420,1168,1168,1294,1260,1260,126,126,2020-03-13,2024-12-13,2020-04-30,2025-05-21,2024-12-16,2025-05-21,2025-05-22,2025-10-07,2024-12-23,2025-05-29,2025-05-29,2025-10-13,week,5
6,VTBR,ok,mature,False,4366,4114,1260,4240,1260,1260,126,126,2019-11-26,2024-12-17,2020-06-01,2025-05-23,2024-12-18,2025-05-23,2025-05-26,2025-10-07,2024-12-25,2025-05-31,2025-05-31,2025-10-13,week,5

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
3,validation,CBOM,momentum,126,0.050542,0.064387,-0.032487,0.238607,0.135598,0.603175,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,1,True
5,validation,CBOM,ridge,126,0.057839,0.074645,-0.387685,0.016420,0.056540,0.523810,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,2,False
4,validation,CBOM,naive_persistence,126,0.056416,0.070545,-0.239402,0.014613,0.006740,0.500000,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,3,False
2,validation,CBOM,lightgbm,126,0.053503,0.068831,-0.179917,-0.093521,-0.077801,0.452381,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,4,False
1,validation,CBOM,hist_gradient_boosting,126,0.055051,0.070015,-0.220879,-0.089669,-0.068302,0.436508,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,5,False
6,validation,CBOM,xgboost,126,0.051171,0.065275,-0.061157,NaN,NaN,0.420635,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,6,False
0,validation,CBOM,catboost,126,0.052434,0.067718,-0.142078,-0.022527,-0.067333,0.412698,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,7,False
12,validation,MBNK,ridge,64,0.197472,0.248458,-60.245625,0.147357,0.150504,0.640625,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,1,True
11,validation,MBNK,naive_persistence,64,0.029312,0.036138,-0.295647,-0.082903,0.010852,0.546875,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,2,False
13,validation,MBNK,xgboost,64,0.027514,0.032896,-0.073649,NaN,NaN,0.484375,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,3,False
9,validation,MBNK,lightgbm,64,0.027451,0.033000,-0.080418,0.304833,0.387448,0.484375,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,4,False
7,validation,MBNK,catboost,64,0.028403,0.035155,-0.226172,0.109994,0.123581,0.484375,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,5,False
8,validation,MBNK,hist_gradient_boosting,64,0.035755,0.044237,-0.941534,0.355216,0.437084,0.484375,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,6,False
10,validation,MBNK,momentum,64,0.027175,0.032376,-0.039956,-0.334164,-0.254167,0.406250,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,7,False
17,validation,SBER,momentum,126,0.027809,0.039988,-0.045619,-0.168581,-0.124199,0.547619,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,1,True
18,validation,SBER,naive_persistence,126,0.030932,0.042476,-0.179756,0.070894,0.023874,0.500000,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,2,False
19,validation,SBER,ridge,126,0.031266,0.043669,-0.246924,-0.067074,-0.031823,0.476190,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,3,False
16,validation,SBER,lightgbm,126,0.031586,0.043805,-0.254751,-0.129377,-0.067982,0.460317,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,4,False
15,validation,SBER,hist_gradient_boosting,126,0.038939,0.053802,-0.892803,-0.184584,-0.238120,0.436508,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,5,False
14,validation,SBER,catboost,126,0.032469,0.044907,-0.318632,-0.144170,-0.173093,0.404762,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,6,False
20,validation,SBER,xgboost,126,0.027980,0.039929,-0.042492,NaN,NaN,0.396825,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,7,False
23,validation,SBERP,lightgbm,126,0.026205,0.037377,-0.038405,0.010505,0.011066,0.579365,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,1,True
24,validation,SBERP,momentum,126,0.026043,0.037530,-0.046916,-0.164610,-0.114235,0.555556,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,2,False
25,validation,SBERP,naive_persistence,126,0.029373,0.040241,-0.203589,0.066009,0.007076,0.468254,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,3,False
26,validation,SBERP,ridge,126,0.045464,0.060966,-1.762610,-0.034272,0.046215,0.460317,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,4,False
22,validation,SBERP,hist_gradient_boosting,126,0.044821,0.061060,-1.771186,-0.180846,-0.170692,0.452381,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,5,False
27,validation,SBERP,xgboost,126,0.027257,0.038380,-0.094845,-0.130612,-0.155186,0.428571,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,6,False
21,validation,SBERP,catboost,126,0.033189,0.047374,-0.668094,-0.041296,-0.093609,0.404762,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,7,False
32,validation,SVCB,naive_persistence,83,0.034945,0.043822,-0.198469,0.012300,0.005080,0.530120,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,1,True
29,validation,SVCB,hist_gradient_boosting,83,0.039416,0.046900,-0.372750,0.211927,0.190854,0.506024,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,2,False
28,validation,SVCB,catboost,83,0.034641,0.041575,-0.078742,0.130116,0.101969,0.493976,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,3,False
34,validation,SVCB,xgboost,83,0.031829,0.040052,-0.001132,NaN,NaN,0.457831,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,4,False
30,validation,SVCB,lightgbm,83,0.031829,0.040052,-0.001132,NaN,NaN,0.457831,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,5,False
31,validation,SVCB,momentum,83,0.033662,0.042043,-0.103136,-0.148792,-0.198564,0.433735,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,6,False
33,validation,SVCB,ridge,83,0.055330,0.068686,-1.944326,0.020817,0.011985,0.433735,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,7,False
41,validation,T,xgboost,126,0.040494,0.054616,-0.022131,NaN,NaN,0.666667,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,1,True
35,validation,T,catboost,126,0.040835,0.054026,-0.000135,0.233660,0.204445,0.587302,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,2,False
39,validation,T,naive_persistence,126,0.045598,0.059884,-0.228783,-0.008171,-0.000771,0.515873,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,3,False
37,validation,T,lightgbm,126,0.042863,0.056061,-0.076896,0.165772,0.124973,0.507937,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,4,False
38,validation,T,momentum,126,0.045715,0.059992,-0.233237,-0.007885,-0.052952,0.507937,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,5,False
36,validation,T,hist_gradient_boosting,126,0.048508,0.061741,-0.306192,0.144680,0.082427,0.460317,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,6,False
40,validation,T,ridge,126,0.053160,0.067437,-0.558330,-0.039415,-0.040918,0.428571,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,7,False
46,validation,VTBR,naive_persistence,126,0.050889,0.068006,-0.187993,0.048660,0.093267,0.515873,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,1,True
43,validation,VTBR,hist_gradient_boosting,126,0.047585,0.064475,-0.067833,0.189511,0.154225,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,2,False
44,validation,VTBR,lightgbm,126,0.047593,0.064500,-0.068654,NaN,NaN,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,3,False
48,validation,VTBR,xgboost,126,0.047593,0.064501,-0.068673,NaN,NaN,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,4,False
42,validation,VTBR,catboost,126,0.047631,0.064524,-0.069438,-0.147967,-0.217098,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,5,False
47,validation,VTBR,ridge,126,0.047811,0.064616,-0.072497,-0.025602,-0.111739,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,6,False
45,validation,VTBR,momentum,126,0.048376,0.064419,-0.065961,-0.441041,-0.519802,0.269841,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,7,False

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
3,validation,CBOM,momentum,126,0.050542,0.064387,-0.032487,0.238607,0.135598,0.603175,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,1,True
12,validation,MBNK,ridge,64,0.197472,0.248458,-60.245625,0.147357,0.150504,0.640625,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,1,True
17,validation,SBER,momentum,126,0.027809,0.039988,-0.045619,-0.168581,-0.124199,0.547619,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,1,True
23,validation,SBERP,lightgbm,126,0.026205,0.037377,-0.038405,0.010505,0.011066,0.579365,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,1,True
32,validation,SVCB,naive_persistence,83,0.034945,0.043822,-0.198469,0.012300,0.005080,0.530120,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,1,True
41,validation,T,xgboost,126,0.040494,0.054616,-0.022131,NaN,NaN,0.666667,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,1,True
46,validation,VTBR,naive_persistence,126,0.050889,0.068006,-0.187993,0.048660,0.093267,0.515873,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,1,True

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,catboost,126,0.035405,0.045339,-0.177474,0.158048,0.165612,0.444444,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,7,False,0.412698
1,test,CBOM,hist_gradient_boosting,126,0.037630,0.047119,-0.271767,0.086560,0.108110,0.500000,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,5,False,0.436508
2,test,CBOM,lightgbm,126,0.034566,0.043893,-0.103584,0.095166,0.137590,0.515873,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,4,False,0.452381
3,test,CBOM,momentum,126,0.033353,0.042393,-0.029406,-0.104179,-0.196658,0.444444,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,1,True,0.603175
4,test,CBOM,naive_persistence,126,0.035463,0.047183,-0.275220,-0.074744,-0.038584,0.500000,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,3,False,0.500000
5,test,CBOM,ridge,126,0.032458,0.042025,-0.011617,0.180101,0.217746,0.595238,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,2,False,0.523810
6,test,CBOM,xgboost,126,0.032805,0.041804,-0.001034,NaN,NaN,0.507937,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,6,False,0.420635
7,test,MBNK,catboost,64,0.027269,0.036585,0.103646,0.565771,0.588233,0.625000,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,5,False,0.484375
8,test,MBNK,hist_gradient_boosting,64,0.033447,0.041720,-0.165614,-0.183538,-0.163051,0.437500,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,6,False,0.484375
9,test,MBNK,lightgbm,64,0.029140,0.038651,-0.000412,NaN,NaN,0.625000,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,4,False,0.484375
10,test,MBNK,momentum,64,0.028585,0.037068,0.079841,0.464626,0.458608,0.765625,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,7,False,0.406250
11,test,MBNK,naive_persistence,64,0.033019,0.040941,-0.122506,0.094607,0.108562,0.546875,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,2,False,0.546875
12,test,MBNK,ridge,64,0.129126,0.149213,-13.910142,-0.286436,-0.334432,0.531250,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,1,True,0.640625
13,test,MBNK,xgboost,64,0.029163,0.038646,-0.000172,NaN,NaN,0.625000,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,3,False,0.484375
14,test,SBER,catboost,126,0.016372,0.020207,-0.183680,-0.061892,-0.048831,0.452381,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,6,False,0.404762
15,test,SBER,hist_gradient_boosting,126,0.016726,0.020562,-0.225744,-0.037631,-0.054738,0.420635,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,5,False,0.436508
16,test,SBER,lightgbm,126,0.016081,0.019588,-0.112372,0.079393,0.219986,0.412698,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,4,False,0.460317
17,test,SBER,momentum,126,0.015153,0.018714,-0.015273,0.048738,0.055838,0.500000,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,1,True,0.547619
18,test,SBER,naive_persistence,126,0.017608,0.022441,-0.459986,-0.109419,-0.111559,0.492063,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,2,False,0.500000
19,test,SBER,ridge,126,0.017111,0.021165,-0.298572,-0.078742,-0.050625,0.523810,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,3,False,0.476190
20,test,SBER,xgboost,126,0.015424,0.018962,-0.042349,NaN,NaN,0.420635,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,7,False,0.396825
21,test,SBERP,catboost,126,0.018297,0.023118,-0.557861,-0.215403,-0.213348,0.428571,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,7,False,0.404762
22,test,SBERP,hist_gradient_boosting,126,0.017327,0.021357,-0.329561,-0.072210,-0.050928,0.515873,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,5,False,0.452381
23,test,SBERP,lightgbm,126,0.015738,0.019051,-0.057905,NaN,NaN,0.428571,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,1,True,0.579365
24,test,SBERP,momentum,126,0.015328,0.018665,-0.015502,0.006049,0.011114,0.444444,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,2,False,0.555556
25,test,SBERP,naive_persistence,126,0.017389,0.021838,-0.390132,-0.082912,-0.104312,0.460317,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,3,False,0.468254
26,test,SBERP,ridge,126,0.022025,0.028819,-1.420836,-0.128209,-0.114709,0.523810,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,4,False,0.460317
27,test,SBERP,xgboost,126,0.015657,0.018977,-0.049663,0.037588,0.032214,0.428571,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,6,False,0.428571
28,test,SVCB,catboost,83,0.037849,0.046596,-0.439113,0.099414,0.101192,0.578313,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,3,False,0.493976
29,test,SVCB,hist_gradient_boosting,83,0.042731,0.049974,-0.655368,-0.067818,-0.185332,0.361446,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,2,False,0.506024
30,test,SVCB,lightgbm,83,0.031158,0.040797,-0.103211,NaN,NaN,0.722892,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,5,False,0.457831
31,test,SVCB,momentum,83,0.031479,0.041487,-0.140854,-0.009206,-0.007787,0.590361,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,6,False,0.433735
32,test,SVCB,naive_persistence,83,0.033845,0.044182,-0.293877,0.008596,0.016015,0.566265,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,1,True,0.530120
33,test,SVCB,ridge,83,0.066014,0.073114,-2.543266,-0.002353,0.030330,0.373494,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,7,False,0.433735
34,test,SVCB,xgboost,83,0.031158,0.040797,-0.103211,NaN,NaN,0.722892,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,4,False,0.457831
35,test,T,catboost,126,0.024971,0.032278,-0.393143,-0.062429,-0.060391,0.587302,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,2,False,0.587302
36,test,T,hist_gradient_boosting,126,0.030010,0.038294,-0.960866,0.040921,-0.000255,0.571429,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,6,False,0.460317
37,test,T,lightgbm,126,0.025172,0.032551,-0.416807,-0.088388,-0.084472,0.563492,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,4,False,0.507937
38,test,T,momentum,126,0.024882,0.031063,-0.290288,-0.075195,-0.059906,0.436508,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,5,False,0.507937
39,test,T,naive_persistence,126,0.023963,0.030031,-0.205958,0.001774,0.048495,0.547619,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,3,False,0.515873
40,test,T,ridge,126,0.030651,0.038991,-1.032920,-0.061531,-0.022992,0.460317,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,7,False,0.428571
41,test,T,xgboost,126,0.022943,0.028164,-0.060693,NaN,NaN,0.420635,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,1,True,0.666667
42,test,VTBR,catboost,126,0.040978,0.068710,-0.025774,-0.120745,-0.025650,0.587302,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,5,False,0.484127
43,test,VTBR,hist_gradient_boosting,126,0.040910,0.068849,-0.029955,0.047394,-0.064996,0.626984,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,2,False,0.484127
44,test,VTBR,lightgbm,126,0.040983,0.068694,-0.025307,NaN,NaN,0.587302,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,3,False,0.484127
45,test,VTBR,momentum,126,0.041188,0.069146,-0.038842,-0.047587,-0.099825,0.571429,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,7,False,0.269841
46,test,VTBR,naive_persistence,126,0.044167,0.074690,-0.212104,-0.031998,0.055436,0.507937,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,1,True,0.515873
47,test,VTBR,ridge,126,0.040992,0.068773,-0.027659,-0.023955,0.026982,0.587302,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,6,False,0.484127
48,test,VTBR,xgboost,126,0.040982,0.068694,-0.025306,NaN,NaN,0.587302,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,4,False,0.484127

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning
0,-0.033845,-0.066544,0.045028,252.0,-1.477835,-0.627279,-0.036102,-1.843214,0.007937,5,CBOM,catboost,overlapping_tranches,126,False
1,0.026282,0.053256,0.084731,252.0,0.628525,0.639125,-0.072573,0.733820,0.025397,16,CBOM,hist_gradient_boosting,overlapping_tranches,126,False
2,-0.002482,-0.004958,0.053232,252.0,-0.093135,-0.066945,-0.035829,-0.138373,0.022222,14,CBOM,lightgbm,overlapping_tranches,126,False
3,0.016817,0.033916,0.104363,252.0,0.324986,0.472782,-0.148409,0.228534,0.012698,8,CBOM,momentum,overlapping_tranches,126,False
4,-0.011291,-0.022455,0.094523,252.0,-0.237567,-0.296137,-0.115530,-0.194370,0.101587,64,CBOM,naive_persistence,overlapping_tranches,126,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,-0.271229,-0.458451,0.457946,50.4,-1.001104,-1.048342,-0.371570,-1.233822,0.038462,1,VTBR,lightgbm,non_overlapping,26,False
94,-0.013435,-0.025880,0.181197,50.4,-0.142826,-0.117076,-0.119299,-0.216932,0.076923,2,VTBR,momentum,non_overlapping,26,False
95,-0.124212,-0.226710,0.125923,50.4,-1.800388,-1.382856,-0.124212,-1.825182,0.346154,9,VTBR,naive_persistence,non_overlapping,26,False
96,-0.230753,-0.398629,0.453397,50.4,-0.879204,-0.889583,-0.325593,-1.224316,0.192308,5,VTBR,ridge,non_overlapping,26,False
97,-0.271229,-0.458451,0.457946,50.4,-1.001104,-1.048342,-0.371570,-1.233822,0.038462,1,VTBR,xgboost,non_overlapping,26,False

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=5439
2,test predictions are available,True,rows=5439
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

=== Strict protocol: month (21 trading days) ===

,ticker,status,split_quality,limited_history,n_obs,n_train_available,n_train,n_refit_available,n_refit,max_train_rows,n_validation,n_test,train_start,train_end,refit_start,refit_end,validation_start,validation_end,test_start,test_end,train_target_end,refit_target_end,validation_target_end,test_target_end,horizon_name,horizon
0,CBOM,ok,mature,False,2523,2271,1260,2397,1260,1260,126,126,2019-11-08,2024-11-25,2020-05-14,2025-05-06,2024-11-26,2025-05-06,2025-05-07,2025-09-19,2024-12-25,2025-05-31,2025-05-31,2025-10-13,month,21
1,MBNK,ok,limited_history,True,302,182,182,242,242,1260,60,60,2024-09-05,2025-05-13,2024-09-05,2025-07-17,2025-05-14,2025-07-17,2025-07-18,2025-09-19,2025-06-06,2025-08-12,2025-08-12,2025-10-13,month,21
2,SBER,ok,mature,False,4394,4142,1260,4268,1260,1260,126,126,2019-11-08,2024-11-25,2020-05-14,2025-05-06,2024-11-26,2025-05-06,2025-05-07,2025-09-19,2024-12-25,2025-05-31,2025-05-31,2025-10-13,month,21
3,SBERP,ok,mature,False,4394,4142,1260,4268,1260,1260,126,126,2019-11-08,2024-11-25,2020-05-14,2025-05-06,2024-11-26,2025-05-06,2025-05-07,2025-09-19,2024-12-25,2025-05-31,2025-05-31,2025-10-13,month,21
4,SVCB,ok,limited_history,True,401,241,241,321,321,1260,80,80,2024-04-27,2025-03-30,2024-04-27,2025-06-27,2025-03-31,2025-06-27,2025-06-28,2025-09-19,2025-04-23,2025-07-19,2025-07-19,2025-10-13,month,21
5,T,ok,mature,False,1404,1152,1152,1278,1260,1260,126,126,2020-03-13,2024-11-21,2020-04-08,2025-05-04,2024-11-22,2025-05-04,2025-05-05,2025-09-17,2024-12-23,2025-05-29,2025-05-29,2025-10-13,month,21
6,VTBR,ok,mature,False,4350,4098,1260,4224,1260,1260,126,126,2019-11-01,2024-11-25,2020-05-07,2025-05-06,2024-11-26,2025-05-06,2025-05-07,2025-09-19,2024-12-25,2025-05-31,2025-05-31,2025-10-13,month,21

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
5,validation,CBOM,ridge,126,0.183240,0.222773,-1.369922,0.477989,0.525369,0.714286,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,1,True
3,validation,CBOM,momentum,126,0.119886,0.145216,-0.007018,0.380199,0.360192,0.674603,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,2,False
6,validation,CBOM,xgboost,126,0.118405,0.148334,-0.050734,-0.585570,-0.444415,0.619048,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,3,False
1,validation,CBOM,hist_gradient_boosting,126,0.120147,0.149107,-0.061706,-0.573815,-0.495051,0.619048,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,4,False
2,validation,CBOM,lightgbm,126,0.121789,0.149149,-0.062307,-0.537117,-0.469035,0.619048,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,5,False
4,validation,CBOM,naive_persistence,126,0.121137,0.145796,-0.015083,0.113085,0.113995,0.563492,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,6,False
0,validation,CBOM,catboost,126,0.127382,0.155058,-0.148142,-0.262248,-0.323231,0.428571,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,7,False
8,validation,MBNK,hist_gradient_boosting,60,0.048051,0.063459,-0.634216,NaN,NaN,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,1,True
12,validation,MBNK,ridge,60,0.048415,0.063871,-0.655535,-0.121510,-0.160711,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,2,False
13,validation,MBNK,xgboost,60,0.049479,0.064837,-0.705989,NaN,NaN,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,3,False
9,validation,MBNK,lightgbm,60,0.048884,0.065537,-0.743013,0.031892,0.217116,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,4,False
7,validation,MBNK,catboost,60,0.056705,0.071597,-1.080241,0.007056,0.004390,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,5,False
11,validation,MBNK,naive_persistence,60,0.041470,0.052807,-0.131638,-0.060240,-0.013504,0.466667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,6,False
10,validation,MBNK,momentum,60,0.039279,0.050680,-0.042329,-0.547339,-0.607113,0.350000,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,7,False
20,validation,SBER,xgboost,126,0.070686,0.091032,-0.246274,0.045223,0.174429,0.674603,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,1,True
16,validation,SBER,lightgbm,126,0.070912,0.090390,-0.228758,0.063181,0.087967,0.650794,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,2,False
17,validation,SBER,momentum,126,0.071385,0.093202,-0.306422,-0.617897,-0.497113,0.587302,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,3,False
18,validation,SBER,naive_persistence,126,0.073334,0.094695,-0.348590,-0.058763,-0.056564,0.500000,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,4,False
14,validation,SBER,catboost,126,0.077314,0.096541,-0.401697,-0.079571,-0.154148,0.436508,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,5,False
15,validation,SBER,hist_gradient_boosting,126,0.084910,0.103799,-0.620371,-0.039137,-0.348325,0.365079,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,6,False
19,validation,SBER,ridge,126,0.106093,0.126527,-1.407649,-0.043844,-0.116322,0.325397,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,7,False
24,validation,SBERP,momentum,126,0.067932,0.090109,-0.308032,-0.617028,-0.488336,0.587302,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,1,True
25,validation,SBERP,naive_persistence,126,0.070104,0.091572,-0.350851,-0.056267,-0.061237,0.507937,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,2,False
27,validation,SBERP,xgboost,126,0.079303,0.095169,-0.459073,0.132893,0.221867,0.492063,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,3,False
22,validation,SBERP,hist_gradient_boosting,126,0.070498,0.090596,-0.322210,-0.006596,-0.090782,0.452381,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,4,False
26,validation,SBERP,ridge,126,0.087977,0.110537,-0.968344,-0.141481,-0.091990,0.396825,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,5,False
23,validation,SBERP,lightgbm,126,0.092537,0.116213,-1.175691,-0.205689,-0.069295,0.396825,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,6,False
21,validation,SBERP,catboost,126,0.069306,0.090194,-0.310509,-0.020509,-0.059918,0.373016,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,7,False
28,validation,SVCB,catboost,80,0.049196,0.058185,-0.404646,0.168544,0.071613,0.537500,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,1,True
30,validation,SVCB,lightgbm,80,0.040728,0.049342,-0.010144,NaN,NaN,0.475000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,2,False
34,validation,SVCB,xgboost,80,0.041635,0.049958,-0.035510,-0.084479,-0.169505,0.475000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,3,False
32,validation,SVCB,naive_persistence,80,0.046077,0.057084,-0.352023,-0.183871,-0.146953,0.475000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,4,False
29,validation,SVCB,hist_gradient_boosting,80,0.062448,0.074267,-1.288427,0.474920,0.475902,0.475000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,5,False
33,validation,SVCB,ridge,80,0.115187,0.130691,-6.086707,0.017648,0.063971,0.450000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,6,False
31,validation,SVCB,momentum,80,0.042513,0.051191,-0.087274,-0.290474,-0.278504,0.362500,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,7,False
37,validation,T,lightgbm,126,0.081024,0.101506,0.066207,0.429886,0.358647,0.658730,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,1,True
41,validation,T,xgboost,126,0.078313,0.094307,0.193975,0.527946,0.429830,0.634921,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,2,False
35,validation,T,catboost,126,0.090946,0.114076,-0.179369,0.296904,0.246020,0.571429,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,3,False
38,validation,T,momentum,126,0.092551,0.115004,-0.198633,-0.448398,-0.377644,0.547619,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,4,False
39,validation,T,naive_persistence,126,0.095111,0.117665,-0.254743,-0.034656,-0.029651,0.484127,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,5,False
36,validation,T,hist_gradient_boosting,126,0.093159,0.115555,-0.210145,0.272293,0.104840,0.468254,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,6,False
40,validation,T,ridge,126,0.248903,0.301147,-7.219024,-0.255856,-0.363732,0.396825,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,7,False
46,validation,VTBR,naive_persistence,126,0.125237,0.152290,-0.219958,-0.021048,0.009584,0.563492,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,1,True
43,validation,VTBR,hist_gradient_boosting,126,0.127975,0.155414,-0.270529,0.680213,0.674624,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,2,False
48,validation,VTBR,xgboost,126,0.129935,0.157269,-0.301036,NaN,NaN,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,3,False
44,validation,VTBR,lightgbm,126,0.130328,0.157712,-0.308378,NaN,NaN,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,4,False
42,validation,VTBR,catboost,126,0.130637,0.158209,-0.316628,-0.636408,-0.633752,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,5,False
47,validation,VTBR,ridge,126,0.130572,0.158500,-0.321480,-0.379559,-0.461915,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,6,False
45,validation,VTBR,momentum,126,0.125417,0.152021,-0.215659,-0.788769,-0.807856,0.230159,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,7,False

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
5,validation,CBOM,ridge,126,0.183240,0.222773,-1.369922,0.477989,0.525369,0.714286,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,1,True
8,validation,MBNK,hist_gradient_boosting,60,0.048051,0.063459,-0.634216,NaN,NaN,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,1,True
20,validation,SBER,xgboost,126,0.070686,0.091032,-0.246274,0.045223,0.174429,0.674603,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,1,True
24,validation,SBERP,momentum,126,0.067932,0.090109,-0.308032,-0.617028,-0.488336,0.587302,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,1,True
28,validation,SVCB,catboost,80,0.049196,0.058185,-0.404646,0.168544,0.071613,0.537500,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,1,True
37,validation,T,lightgbm,126,0.081024,0.101506,0.066207,0.429886,0.358647,0.658730,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,1,True
46,validation,VTBR,naive_persistence,126,0.125237,0.152290,-0.219958,-0.021048,0.009584,0.563492,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,1,True

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,catboost,126,0.081123,0.097541,0.045514,0.278584,0.291801,0.650794,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,7,False,0.428571
1,test,CBOM,hist_gradient_boosting,126,0.087954,0.099400,0.008791,0.122738,0.184148,0.444444,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,4,False,0.619048
2,test,CBOM,lightgbm,126,0.085770,0.099409,0.008607,0.126055,0.130726,0.634921,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,5,False,0.619048
3,test,CBOM,momentum,126,0.088952,0.100350,-0.010248,-0.109474,-0.080993,0.230159,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,2,False,0.674603
4,test,CBOM,naive_persistence,126,0.086153,0.100820,-0.019735,0.059501,0.029639,0.531746,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,6,False,0.563492
5,test,CBOM,ridge,126,0.083977,0.104455,-0.094590,0.295857,0.288057,0.619048,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,1,True,0.714286
6,test,CBOM,xgboost,126,0.085955,0.098517,0.026311,0.203773,0.405381,0.761905,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,3,False,0.619048
7,test,MBNK,catboost,60,0.086232,0.099695,-0.006644,0.611376,0.607669,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,5,False,0.516667
8,test,MBNK,hist_gradient_boosting,60,0.093132,0.112907,-0.291115,0.692720,0.669023,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,1,True,0.516667
9,test,MBNK,lightgbm,60,0.089818,0.102366,-0.061292,NaN,NaN,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,4,False,0.516667
10,test,MBNK,momentum,60,0.090073,0.099464,-0.001979,0.326823,0.337983,0.650000,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,7,False,0.350000
11,test,MBNK,naive_persistence,60,0.090140,0.099190,0.003546,0.148747,0.188108,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,6,False,0.466667
12,test,MBNK,ridge,60,0.088560,0.100420,-0.021329,0.735418,0.731703,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,2,False,0.516667
13,test,MBNK,xgboost,60,0.089739,0.101507,-0.043557,NaN,NaN,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,3,False,0.516667
14,test,SBER,catboost,126,0.032716,0.043991,-0.840044,-0.375818,-0.406320,0.436508,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,5,False,0.436508
15,test,SBER,hist_gradient_boosting,126,0.032145,0.043101,-0.766346,-0.322505,-0.302903,0.380952,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,6,False,0.365079
16,test,SBER,lightgbm,126,0.031838,0.042016,-0.678545,-0.100167,-0.129104,0.436508,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,2,False,0.650794
17,test,SBER,momentum,126,0.026862,0.033841,-0.088906,0.121294,0.104594,0.468254,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,3,False,0.587302
18,test,SBER,naive_persistence,126,0.028016,0.035573,-0.203240,-0.025953,-0.021822,0.515873,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,4,False,0.500000
19,test,SBER,ridge,126,0.041409,0.052413,-1.612061,-0.542822,-0.472504,0.317460,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,7,False,0.325397
20,test,SBER,xgboost,126,0.029667,0.039133,-0.456110,-0.109751,-0.122691,0.436508,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,1,True,0.674603
21,test,SBERP,catboost,126,0.028961,0.037834,-0.385962,-0.537652,-0.550698,0.444444,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,7,False,0.373016
22,test,SBERP,hist_gradient_boosting,126,0.027167,0.036136,-0.264366,0.025891,0.058368,0.547619,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,4,False,0.452381
23,test,SBERP,lightgbm,126,0.032844,0.042219,-0.725804,-0.100698,-0.046047,0.492063,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,6,False,0.396825
24,test,SBERP,momentum,126,0.026347,0.033303,-0.073888,0.073826,0.063091,0.460317,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,1,True,0.587302
25,test,SBERP,naive_persistence,126,0.027744,0.034818,-0.173762,-0.018249,-0.034871,0.507937,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,2,False,0.507937
26,test,SBERP,ridge,126,0.036753,0.046715,-1.112961,-0.517035,-0.529299,0.293651,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,5,False,0.396825
27,test,SBERP,xgboost,126,0.029714,0.038812,-0.458555,-0.192972,-0.190608,0.444444,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,3,False,0.492063
28,test,SVCB,catboost,80,0.080655,0.091611,-0.311304,0.068007,-0.002039,0.675000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,1,True,0.537500
29,test,SVCB,hist_gradient_boosting,80,0.081612,0.093901,-0.377678,0.150758,0.073605,0.650000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,5,False,0.475000
30,test,SVCB,lightgbm,80,0.085220,0.095473,-0.424206,NaN,NaN,0.750000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,2,False,0.475000
31,test,SVCB,momentum,80,0.090264,0.101868,-0.621370,0.192280,0.198125,0.712500,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,7,False,0.362500
32,test,SVCB,naive_persistence,80,0.088765,0.101648,-0.614375,0.106442,0.093601,0.575000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,4,False,0.475000
33,test,SVCB,ridge,80,0.175367,0.200214,-5.263246,-0.081648,-0.039475,0.275000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,6,False,0.450000
34,test,SVCB,xgboost,80,0.085373,0.096046,-0.441335,0.013120,0.010378,0.750000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,3,False,0.475000
35,test,T,catboost,126,0.053665,0.064726,-1.169029,0.162653,0.178181,0.555556,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,3,False,0.571429
36,test,T,hist_gradient_boosting,126,0.059888,0.072889,-1.750643,0.071071,0.051651,0.571429,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,6,False,0.468254
37,test,T,lightgbm,126,0.043574,0.051598,-0.378378,0.346850,0.317302,0.571429,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,1,True,0.658730
38,test,T,momentum,126,0.034712,0.044426,-0.021818,-0.373278,-0.421738,0.357143,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,4,False,0.547619
39,test,T,naive_persistence,126,0.036556,0.045987,-0.094901,-0.005215,-0.052094,0.444444,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,5,False,0.484127
40,test,T,ridge,126,0.062094,0.079948,-2.309153,0.523435,0.418049,0.619048,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,7,False,0.396825
41,test,T,xgboost,126,0.036056,0.042651,0.058169,0.314870,0.222635,0.579365,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,2,False,0.634921
42,test,VTBR,catboost,126,0.086263,0.117670,-0.193583,-0.073635,-0.243561,0.753968,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,5,False,0.325397
43,test,VTBR,hist_gradient_boosting,126,0.089547,0.120046,-0.242278,0.003297,-0.105883,0.619048,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,2,False,0.325397
44,test,VTBR,lightgbm,126,0.086025,0.117505,-0.190238,NaN,NaN,0.753968,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,4,False,0.325397
45,test,VTBR,momentum,126,0.090487,0.122833,-0.300628,-0.225935,-0.051201,0.642857,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,7,False,0.230159
46,test,VTBR,naive_persistence,126,0.093762,0.126968,-0.389670,-0.111032,-0.052919,0.484127,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,1,True,0.563492
47,test,VTBR,ridge,126,0.086499,0.117972,-0.199717,-0.185563,-0.327292,0.753968,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,6,False,0.325397
48,test,VTBR,xgboost,126,0.087311,0.118642,-0.213385,-0.131789,-0.179564,0.753968,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,3,False,0.325397

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning
0,0.037363,0.076123,0.068148,252.0,1.117020,1.495781,-0.104831,0.726151,0.006425,17,CBOM,catboost,overlapping_tranches,126,False
1,-0.001399,-0.002795,0.075787,252.0,-0.036885,-0.069218,-0.134123,-0.020842,0.000378,1,CBOM,hist_gradient_boosting,overlapping_tranches,126,False
2,-0.001399,-0.002795,0.075787,252.0,-0.036885,-0.069218,-0.134123,-0.020842,0.000378,1,CBOM,lightgbm,overlapping_tranches,126,False
3,-0.014546,-0.028881,0.048624,252.0,-0.593971,-1.041034,-0.118213,-0.244313,0.001512,4,CBOM,momentum,overlapping_tranches,126,False
4,-0.012382,-0.024611,0.054982,252.0,-0.447618,-0.507900,-0.071354,-0.344910,0.023054,61,CBOM,naive_persistence,overlapping_tranches,126,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,-0.275729,-0.475432,0.484772,12.0,-0.980733,-1.108389,-0.334896,-1.419641,0.166667,1,VTBR,lightgbm,non_overlapping,6,True
94,-0.194649,-0.351409,0.491674,12.0,-0.714720,-0.627244,-0.260439,-1.349297,0.333333,2,VTBR,momentum,non_overlapping,6,True
95,-0.288406,-0.493633,0.420495,12.0,-1.173933,-0.986322,-0.261547,-1.887358,0.666667,4,VTBR,naive_persistence,non_overlapping,6,True
96,-0.275729,-0.475432,0.484772,12.0,-0.980733,-1.108389,-0.334896,-1.419641,0.166667,1,VTBR,ridge,non_overlapping,6,True
97,-0.283522,-0.486659,0.482137,12.0,-1.009379,-1.185626,-0.342052,-1.422764,0.500000,3,VTBR,xgboost,non_overlapping,6,True

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=5390
2,test predictions are available,True,rows=5390
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

## Legacy Diagnostics

Legacy walk-forward OOF training is intentionally not part of the primary notebook flow. Final reports must use `strict_protocol/reports/test_predictions.parquet`; if legacy OOF diagnostics are needed later, keep them in a separate notebook/section and never feed them into final comparison plots.