# 02b Per-Ticker LSTM Strict Forecasting

Use this notebook when you want to train only the per-ticker LSTM. It writes LSTM artifacts into an isolated `lstm_only/strict_protocol` artifact tree. Run `03_model_comparison.ipynb` afterward to compare these LSTM results with table-model and global-LSTM results.

In [1]:
from pathlib import Path
import os
import sys

cwd = Path.cwd().resolve()
for candidate in [cwd, cwd / "forecasting", cwd.parent, cwd.parent / "forecasting"]:
    if (candidate / "src" / "stock_forecast").exists():
        PROJECT_DIR = candidate
        break
else:
    raise RuntimeError("Cannot locate forecasting project directory with src/stock_forecast")

SRC_DIR = PROJECT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

ARTIFACT_DIR = PROJECT_DIR / "artifacts"
DATA_DIR = ARTIFACT_DIR / "data"
REPORTS_DIR = ARTIFACT_DIR / "reports"
for path in [DATA_DIR, REPORTS_DIR]:
    path.mkdir(parents=True, exist_ok=True)

print(f"PROJECT_DIR = {PROJECT_DIR}")

PROJECT_DIR = /home/sapce/forecasting_stock_prices/forecasting

In [2]:
import importlib.util

import pandas as pd
from IPython.display import display

from stock_forecast.artifacts import load_json, load_table
from stock_forecast.mlflow_tracking import MLflowRunConfig, log_strict_protocol_result, mlflow_horizon_run
from stock_forecast.models import build_model
from stock_forecast.strict_protocol import run_strict_per_ticker_protocol

pd.set_option("display.max_columns", 180)

## Constants

In [3]:
if importlib.util.find_spec("torch") is None:
    raise ImportError("PyTorch is required for this notebook. Install the forecasting[deep] extra.")

FORCE_RETRAIN = True  # set True when you want to retune/retrain LSTM even if matching cache exists
PRIMARY_METRIC = "directional_accuracy"
RANDOM_STATE = 42

STRICT_VALIDATION_ROWS = 126
STRICT_TEST_ROWS = 126
MATURE_MIN_ROWS = 1008
LIMITED_HISTORY_MIN_BLOCK_ROWS = 42
MIN_TRAIN_ROWS = 60
STRICT_MAX_TRAIN_ROWS = 1260
INNER_MAX_FOLDS = 3
INNER_MIN_TRAIN_ROWS = 126
LIMITED_HISTORY_N_TRIALS = 20

LSTM_N_TRIALS = 60
LSTM_OPTUNA_N_JOBS = 1
LSTM_MAX_EPOCHS = 150
LSTM_PATIENCE = 15
LSTM_DEVICE = "auto"
LSTM_ENSEMBLE_SEEDS = [1, 7, 21, 42, 101]

TRANSACTION_COST_BPS = 10
SLIPPAGE_BPS = 5
LONG_THRESHOLD = 0.0
SIGNAL_ANCHOR = "expanding_median"

MLFLOW_ENABLED = os.environ.get("MLFLOW_ENABLED", "true").strip().lower() in {"1", "true", "yes", "y"}
MLFLOW_TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI", "http://localhost:5000")
MLFLOW_EXPERIMENT_NAME = os.environ.get("MLFLOW_EXPERIMENT_NAME", "stock_return_forecasting_research")
MLFLOW_LOG_OPTUNA_TRIALS = os.environ.get("MLFLOW_LOG_OPTUNA_TRIALS", "true").strip().lower() in {"1", "true", "yes", "y"}

LSTM_ONLY_ARTIFACT_NAME = "lstm_only"

HORIZONS = [
    {"name": "week", "horizon": 5},
    {"name": "month", "horizon": 21},
]

In [4]:
def make_lstm_search_space(horizon: int, limited_history: bool = False) -> dict:
    huber_beta_choices = [0.04, 0.08, 0.12] if horizon >= 21 else [0.02, 0.04, 0.06]
    return {
        "lookback": {"type": "categorical", "choices": [20, 40, 60] if limited_history else [20, 40, 60, 90, 126]},
        "hidden_size": {"type": "categorical", "choices": [16, 32, 64, 96, 128]},
        "num_layers": {"type": "categorical", "choices": [1] if limited_history else [1, 2]},
        "input_projection_size": {"type": "categorical", "choices": [0, 32, 64, 128]},
        "lstm_dropout": {"type": "float", "low": 0.0, "high": 0.35},
        "head_dropout": {"type": "float", "low": 0.15, "high": 0.55},
        "learning_rate": {"type": "float", "low": 1e-4, "high": 2e-3, "log": True},
        "weight_decay": {"type": "float", "low": 1e-5, "high": 1e-2, "log": True},
        "batch_size": {"type": "categorical", "choices": [16, 32, 64] if limited_history else [32, 64, 128]},
        "loss": {"type": "categorical", "choices": ["smooth_l1", "huber", "mse"]},
        "huber_beta": {"type": "categorical", "choices": huber_beta_choices},
        "feature_clip": {"type": "categorical", "choices": [3.0, 5.0, 8.0]},
        "grad_clip_norm": {"type": "float", "low": 0.5, "high": 2.0},
    }


def make_lstm_config(lstm_feature_cols: list[str], horizon: int) -> dict:
    return {
        "name": "lstm",
        "model_type": "lstm",
        "estimator_factory": build_model,
        "input_mode": "full_frame",
        "feature_cols": lstm_feature_cols,
        "static_params": {
            "max_epochs": LSTM_MAX_EPOCHS,
            "patience": LSTM_PATIENCE,
            "device": LSTM_DEVICE,
        },
        "search_space": make_lstm_search_space(horizon, limited_history=False),
        "limited_history_search_space": make_lstm_search_space(horizon, limited_history=True),
        "post_selection_static_params": {"ensemble_seeds": LSTM_ENSEMBLE_SEEDS},
        "n_trials": LSTM_N_TRIALS,
        "optuna_n_jobs": LSTM_OPTUNA_N_JOBS,
        "limited_history_n_trials": LIMITED_HISTORY_N_TRIALS,
        "needs_scaler": False,
    }

## Load LSTM Data Artifacts

In [5]:
horizon_inputs = []

for spec in HORIZONS:
    horizon_name = spec["name"]
    horizon = int(spec["horizon"])
    base_feature_payload = load_json(DATA_DIR / "horizons" / horizon_name / "feature_columns.json")
    target_col = base_feature_payload["target_column"]

    lstm_dir = DATA_DIR / "lstm" / "horizons" / horizon_name
    lstm_model_path = lstm_dir / "model_dataset.parquet"
    lstm_feature_path = lstm_dir / "feature_columns.json"
    if not lstm_model_path.exists() and not lstm_model_path.with_suffix(".csv").exists():
        raise FileNotFoundError(
            f"Missing LSTM data for {horizon_name}: {lstm_model_path}. "
            "Run notebooks/01b_lstm_eda.ipynb first."
        )
    if not lstm_feature_path.exists():
        raise FileNotFoundError(f"Missing LSTM feature payload for {horizon_name}: {lstm_feature_path}")

    lstm_payload = load_json(lstm_feature_path)
    if lstm_payload["target_column"] != target_col:
        raise ValueError(f"LSTM target mismatch for {horizon_name}: {lstm_payload['target_column']} != {target_col}")

    model_df = load_table(lstm_model_path)
    model_df["date"] = pd.to_datetime(model_df["date"])
    lstm_feature_cols = lstm_payload["feature_columns"]
    model_configs = [make_lstm_config(lstm_feature_cols, horizon)]

    horizon_inputs.append({
        "horizon_name": horizon_name,
        "horizon": horizon,
        "model_df": model_df,
        "feature_cols": base_feature_payload["feature_columns"],
        "lstm_feature_cols": lstm_feature_cols,
        "target_col": target_col,
        "model_configs": model_configs,
        "lstm_only_artifact_dir": ARTIFACT_DIR / "horizons" / horizon_name / LSTM_ONLY_ARTIFACT_NAME,
    })

    print({
        "horizon": horizon_name,
        "rows": len(model_df),
        "lstm_features": len(lstm_feature_cols),
        "target": target_col,
        "lstm_only_artifact_dir": str((ARTIFACT_DIR / "horizons" / horizon_name / LSTM_ONLY_ARTIFACT_NAME).relative_to(PROJECT_DIR)),
    })
    display(model_df[["date", "ticker", target_col, *lstm_feature_cols[:6]]].head())

{'horizon': 'week', 'rows': 19407, 'lstm_features': 160, 'target': 'target_return_5_next_open', 'lstm_only_artifact_dir': 'artifacts/horizons/week/lstm_only'}

,date,ticker,target_return_5_next_open,log_close,ret_1,open_close_ret,high_low_range,close_to_high,close_to_low
0,2015-11-09,CBOM,0.013316,1.321756,-0.003992,0.000000,0.000000,0.000000,0.000000
1,2015-11-10,CBOM,0.019908,1.320422,-0.001334,0.004013,0.004005,0.000000,0.004021
2,2015-11-11,CBOM,0.005312,1.319086,-0.001336,0.002677,0.002674,0.000000,0.002681
3,2015-11-12,CBOM,0.010582,1.323088,0.004003,0.000000,0.000000,0.000000,0.000000
4,2015-11-13,CBOM,-0.002649,1.329724,0.006636,0.005305,0.300265,-0.227783,0.005319

{'horizon': 'month', 'rows': 19295, 'lstm_features': 160, 'target': 'target_return_21_next_open', 'lstm_only_artifact_dir': 'artifacts/horizons/month/lstm_only'}

,date,ticker,target_return_21_next_open,log_close,ret_1,open_close_ret,high_low_range,close_to_high,close_to_low
0,2015-11-09,CBOM,0.027761,1.321756,-0.003992,0.000000,0.000000,0.000000,0.000000
1,2015-11-10,CBOM,0.023842,1.320422,-0.001334,0.004013,0.004005,0.000000,0.004021
2,2015-11-11,CBOM,0.021081,1.319086,-0.001336,0.002677,0.002674,0.000000,0.002681
3,2015-11-12,CBOM,0.021053,1.323088,0.004003,0.000000,0.000000,0.000000,0.000000
4,2015-11-13,CBOM,0.011834,1.329724,0.006636,0.005305,0.300265,-0.227783,0.005319

## Train LSTM Only

In [6]:
lstm_results = {}

for item in horizon_inputs:
    horizon_name = item["horizon_name"]
    horizon = item["horizon"]
    mlflow_config = MLflowRunConfig(
        tracking_uri=MLFLOW_TRACKING_URI,
        experiment_name=MLFLOW_EXPERIMENT_NAME,
        notebook_name="02b_lstm_forecasting",
        horizon_name=horizon_name,
        horizon=horizon,
        enabled=MLFLOW_ENABLED,
        log_optuna_trials=MLFLOW_LOG_OPTUNA_TRIALS,
    )
    mlflow_params = {
        "primary_metric": PRIMARY_METRIC,
        "force_retrain": FORCE_RETRAIN,
        "random_state": RANDOM_STATE,
        "lstm_n_trials": LSTM_N_TRIALS,
        "lstm_optuna_n_jobs": LSTM_OPTUNA_N_JOBS,
        "lstm_max_epochs": LSTM_MAX_EPOCHS,
        "lstm_patience": LSTM_PATIENCE,
        "lstm_ensemble_seeds": LSTM_ENSEMBLE_SEEDS,
        "feature_count": len(item["lstm_feature_cols"]),
        "target_col": item["target_col"],
        "validation_rows": STRICT_VALIDATION_ROWS,
        "test_rows": STRICT_TEST_ROWS,
        "transaction_cost_bps": TRANSACTION_COST_BPS,
        "slippage_bps": SLIPPAGE_BPS,
        "signal_anchor": SIGNAL_ANCHOR,
    }
    with mlflow_horizon_run(
        mlflow_config,
        params=mlflow_params,
        tags={"training_protocol": "strict_per_ticker_lstm", "training_notebook": "02b_lstm_forecasting"},
    ) as mlflow_run:
        result = run_strict_per_ticker_protocol(
            model_df=item["model_df"],
            feature_cols=item["feature_cols"],
            target_col=item["target_col"],
            model_configs=item["model_configs"],
            artifact_dir=item["lstm_only_artifact_dir"],
            force_retrain=FORCE_RETRAIN,
            primary_metric=PRIMARY_METRIC,
            random_state=RANDOM_STATE,
            run_metadata={
                "horizon_name": horizon_name,
                "horizon": horizon,
                "training_notebook": "02b_lstm_forecasting",
                "lstm_only_run": True,
            },
            validation_rows=STRICT_VALIDATION_ROWS,
            test_rows=STRICT_TEST_ROWS,
            mature_min_rows=MATURE_MIN_ROWS,
            limited_history_min_block_rows=LIMITED_HISTORY_MIN_BLOCK_ROWS,
            min_train_rows=MIN_TRAIN_ROWS,
            max_train_rows=STRICT_MAX_TRAIN_ROWS,
            inner_max_folds=INNER_MAX_FOLDS,
            inner_min_train_rows=INNER_MIN_TRAIN_ROWS,
            limited_history_n_trials=LIMITED_HISTORY_N_TRIALS,
            transaction_cost_bps=TRANSACTION_COST_BPS,
            slippage_bps=SLIPPAGE_BPS,
            long_threshold=LONG_THRESHOLD,
            signal_anchor=SIGNAL_ANCHOR,
            mlflow_trial_logger=mlflow_run.trial_logger,
        )
        log_strict_protocol_result(
            result,
            params=mlflow_params,
            tags={"training_protocol": "strict_per_ticker_lstm", "training_notebook": "02b_lstm_forecasting"},
        )
    lstm_results[horizon_name] = result

    print(f"=== LSTM-only strict protocol: {horizon_name} ({horizon} trading days) ===")
    display(result["validation_model_ranking"])
    display(result["test_prediction_metrics"])
    display(result["test_signal_metrics"])
    display(result["leakage_audit"])

    failed = result["leakage_audit"][~result["leakage_audit"]["passed"]]
    if not failed.empty:
        raise AssertionError(f"LSTM-only leakage audit failed for {horizon_name}: {failed['check'].tolist()}")

🏃 View run week-lstm-trial-0 at: http://localhost:5000/#/experiments/2/runs/03ed658f96194ee1b2e6d5b35c11ccc9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-1 at: http://localhost:5000/#/experiments/2/runs/37c082008e3b44fc9d96c94e600d616f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-2 at: http://localhost:5000/#/experiments/2/runs/9410e6f8a39a450aa61291ddb6bb21ba
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-3 at: http://localhost:5000/#/experiments/2/runs/1339f015fbba4605bfc4ecab1e937756
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-4 at: http://localhost:5000/#/experiments/2/runs/f4520b6c14de4a22aeba2ed27687a3c9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-5 at: http://localhost:5000/#/experiments/2/runs/27d735a50ba34c608a9f40e24c105086
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-6 at: http://localhost:5000/#/experiments/2/runs/3b86258ae64f42428380cb78f4652efe
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-7 at: http://localhost:5000/#/experiments/2/runs/bde0faeafc6d4ff5a4645df95274509a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-8 at: http://localhost:5000/#/experiments/2/runs/3ebf602195e44a3981d6d5ee5f52a5ed
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-9 at: http://localhost:5000/#/experiments/2/runs/4fcf9a4acbdc496594085f956c8c580e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-10 at: http://localhost:5000/#/experiments/2/runs/83dd7c9490364adca3bb4a3459133ce0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-11 at: http://localhost:5000/#/experiments/2/runs/17539d16bb2f448bbd8b4c02e283bddf
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-12 at: http://localhost:5000/#/experiments/2/runs/e1dfb034547e43f995d3ceff959deb4c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-13 at: http://localhost:5000/#/experiments/2/runs/6598b1e3cdbd43549cd022673c812cb3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-14 at: http://localhost:5000/#/experiments/2/runs/67c5fcbb57d74337af23795d630c349d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-15 at: http://localhost:5000/#/experiments/2/runs/9a68163fc30b47c08b05be273dee2eb1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-16 at: http://localhost:5000/#/experiments/2/runs/16d74b4eee4241349591abac3f332fb3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-17 at: http://localhost:5000/#/experiments/2/runs/b29a5f433a1d46caaf015dad0b2302a7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-18 at: http://localhost:5000/#/experiments/2/runs/e400b2c19fa54fbfa75025631f52e6f3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-19 at: http://localhost:5000/#/experiments/2/runs/488e29fe09a8498393e72ea8ad4756a8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-20 at: http://localhost:5000/#/experiments/2/runs/13840267d041422dbd98bd9250abf963
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-21 at: http://localhost:5000/#/experiments/2/runs/58599fabe611470d8b62ef852ab5484a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-22 at: http://localhost:5000/#/experiments/2/runs/6484fb2f61464e5a9861280e37d81e1a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-23 at: http://localhost:5000/#/experiments/2/runs/63ae3ec189e44c9a8e29bbacaa7d969d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-24 at: http://localhost:5000/#/experiments/2/runs/2da78236047f46e6bb06b194ba75e4a7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-25 at: http://localhost:5000/#/experiments/2/runs/8c535dc662934306ac50fb5149b8b224
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-26 at: http://localhost:5000/#/experiments/2/runs/d9b589a23412483f9652764b0f3858b0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-27 at: http://localhost:5000/#/experiments/2/runs/537cb058faaa4df281050d2caec25019
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-28 at: http://localhost:5000/#/experiments/2/runs/0950308a0ab94b34b1f955d5b38a96e5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-29 at: http://localhost:5000/#/experiments/2/runs/4957e220e4064a11b0af44a78c9073f6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-30 at: http://localhost:5000/#/experiments/2/runs/f63cf7fe2a544e6ba722df6800699cb5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-31 at: http://localhost:5000/#/experiments/2/runs/e89bb4ec89e043b68b3cdb4ecb605012
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-32 at: http://localhost:5000/#/experiments/2/runs/e4e53b3c318f4c048486f5e1749759f5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-33 at: http://localhost:5000/#/experiments/2/runs/9e001597bc714c869472dd969f3356b6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-34 at: http://localhost:5000/#/experiments/2/runs/1d277e4c750842328e3ab45650c1612f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-35 at: http://localhost:5000/#/experiments/2/runs/3ca03c53219c4061ad4f747727965355
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-36 at: http://localhost:5000/#/experiments/2/runs/bc364b171e85436092a352d22ddf6a28
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-37 at: http://localhost:5000/#/experiments/2/runs/983f9eaaaac3436a8ed2c257926a1ba0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-38 at: http://localhost:5000/#/experiments/2/runs/8ac617932eee43dc9c10c3393ba752d2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-39 at: http://localhost:5000/#/experiments/2/runs/5badcf1e31604763867000aa5866146a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-40 at: http://localhost:5000/#/experiments/2/runs/d819ca41a14346ab91102e66ad1a4db6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-41 at: http://localhost:5000/#/experiments/2/runs/af5260b479c24a70add18949b31334c5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-42 at: http://localhost:5000/#/experiments/2/runs/12ac7c17fbf7456193ac7d2175190f34
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-43 at: http://localhost:5000/#/experiments/2/runs/47ae0bf7c1e6477c9a09753f2bdc0073
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-44 at: http://localhost:5000/#/experiments/2/runs/bed62b5d1fd84195941dfd33a5cb18bb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-45 at: http://localhost:5000/#/experiments/2/runs/1bd1ffaf883240e08ed780795f8178b3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-46 at: http://localhost:5000/#/experiments/2/runs/0903248528ac4ae6be7ea8862e37f75d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-47 at: http://localhost:5000/#/experiments/2/runs/aa28e42fdbce44c1bc5f3b5f5281fe0a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-48 at: http://localhost:5000/#/experiments/2/runs/d6a5e0692474481fb874eaf97be0ac53
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-49 at: http://localhost:5000/#/experiments/2/runs/6de3296305ea40179b65b887e8994e5f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-50 at: http://localhost:5000/#/experiments/2/runs/d0e4881cdce0442d800a5aa2ce5d1670
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-51 at: http://localhost:5000/#/experiments/2/runs/16cf1fc856864cf6b30601f147d87cba
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-52 at: http://localhost:5000/#/experiments/2/runs/e8bead28aeac400aa552fe0857f5146d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-53 at: http://localhost:5000/#/experiments/2/runs/1e11fa3f8fce4b069b67b208a8414a4a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-54 at: http://localhost:5000/#/experiments/2/runs/a3af0b720880482abdaaa8f3d72b3ea7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-55 at: http://localhost:5000/#/experiments/2/runs/aba55b2732bc40feb4d6dc19764946aa
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-56 at: http://localhost:5000/#/experiments/2/runs/cae766a6382a451c91eedc2cecddbccb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-57 at: http://localhost:5000/#/experiments/2/runs/417849ef17e54694a06930fa0c0620fc
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-58 at: http://localhost:5000/#/experiments/2/runs/a49b79b98f2347c6b221659ef0d204a9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-59 at: http://localhost:5000/#/experiments/2/runs/712172c599f945898c45129165f73971
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-0 at: http://localhost:5000/#/experiments/2/runs/8bf6604eae2946f383ba5a73f1d0f7da
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-1 at: http://localhost:5000/#/experiments/2/runs/40d4c659d098404084f842f6a7be5aaa
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-2 at: http://localhost:5000/#/experiments/2/runs/c25b8097349d42eb840aedc1d7e3aa43
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-3 at: http://localhost:5000/#/experiments/2/runs/13303a7972e0423fb88b91afe0440511
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-4 at: http://localhost:5000/#/experiments/2/runs/ccd2013b54ce431dacb1e504bc39ab90
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-5 at: http://localhost:5000/#/experiments/2/runs/180951815a54430e8343a5308b58c4aa
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-6 at: http://localhost:5000/#/experiments/2/runs/0ff79bbd252b4cf7a3ae013581fce675
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-7 at: http://localhost:5000/#/experiments/2/runs/83543acbf15e4ec2a17b7cd78089bec5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-8 at: http://localhost:5000/#/experiments/2/runs/8cd3aa52407f49088df6c31e76b4a07b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-9 at: http://localhost:5000/#/experiments/2/runs/118e8b25ddb8415daac0888984dd8278
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-10 at: http://localhost:5000/#/experiments/2/runs/7dd7cb412a8446c58d7f58287b1b8c3c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-11 at: http://localhost:5000/#/experiments/2/runs/1def6b2b1b934c34841c87e9747543db
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-12 at: http://localhost:5000/#/experiments/2/runs/6da5a9a6553c4883b922ed463f719f99
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-13 at: http://localhost:5000/#/experiments/2/runs/fd6cc8c1b64f428c91780174665fdb5e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-14 at: http://localhost:5000/#/experiments/2/runs/124236e2235743a0a1abde2737b888fe
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-15 at: http://localhost:5000/#/experiments/2/runs/83cd0c6c4d3f42aebf557c8da6cb91d9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-16 at: http://localhost:5000/#/experiments/2/runs/4f58125454034aa8a9ce1b771890cae1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-17 at: http://localhost:5000/#/experiments/2/runs/f9b842a4307d44b4a1b4ea850f3f63b5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-18 at: http://localhost:5000/#/experiments/2/runs/b10662a358d94a2a8ed596a4da758f6f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-19 at: http://localhost:5000/#/experiments/2/runs/7aeb0cc1bd00493f9be9fea5966eac1b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-0 at: http://localhost:5000/#/experiments/2/runs/1011bd599bc44afd9f96c7a865b89d8d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-1 at: http://localhost:5000/#/experiments/2/runs/5233bc92f18e4950a093e313cb0e4325
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-2 at: http://localhost:5000/#/experiments/2/runs/05ad5236a65c4b71b5764cab955f8e5c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-3 at: http://localhost:5000/#/experiments/2/runs/39e2ef183e0d4b9999f7419f7e1fcdb9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-4 at: http://localhost:5000/#/experiments/2/runs/f5d525eada9b48af813aae75bbc29e47
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-5 at: http://localhost:5000/#/experiments/2/runs/739dd54aaeae4c91b714a3321dbbc4a0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-6 at: http://localhost:5000/#/experiments/2/runs/443afc2e56e146b2922fb070180efeeb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-7 at: http://localhost:5000/#/experiments/2/runs/5f19b96c840d4b80b9f7a2380beab19c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-8 at: http://localhost:5000/#/experiments/2/runs/c42927e3dcc048e0a90f317b30635034
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-9 at: http://localhost:5000/#/experiments/2/runs/19b4f8f090b241ccbabc6d53ea885ee6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-10 at: http://localhost:5000/#/experiments/2/runs/f8276574ecf34aab97263e7276924a1d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-11 at: http://localhost:5000/#/experiments/2/runs/82f008c78c5d4934bb7619ad67944c9d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-12 at: http://localhost:5000/#/experiments/2/runs/de5767bb26014cb9826f4228ccd79335
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-13 at: http://localhost:5000/#/experiments/2/runs/cbb3e1c3e3d548e8bc7adb2d1272d072
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-14 at: http://localhost:5000/#/experiments/2/runs/ad4d5a247c2841afa2ed24a095211230
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-15 at: http://localhost:5000/#/experiments/2/runs/db42a8f2939f4a3ba3cff0ab6bf019df
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-16 at: http://localhost:5000/#/experiments/2/runs/843c5407138245d6a023b429f500a4ce
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-17 at: http://localhost:5000/#/experiments/2/runs/38be0d9257734a119419bb8f00da4617
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-18 at: http://localhost:5000/#/experiments/2/runs/8bbe9e33974742d79d7900f14f403e67
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-19 at: http://localhost:5000/#/experiments/2/runs/6ae6ea023d78430ca668deeda2ce2db9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-20 at: http://localhost:5000/#/experiments/2/runs/88a4fbe83f004a838d409352c8bcffb4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-21 at: http://localhost:5000/#/experiments/2/runs/a82f7044f46448ed898701f0611fc107
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-22 at: http://localhost:5000/#/experiments/2/runs/c6fe7e29d9104ba8b2a83e5ab6870015
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-23 at: http://localhost:5000/#/experiments/2/runs/d8b7a2b51e5e4f1a90165cc2ced599a4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-24 at: http://localhost:5000/#/experiments/2/runs/32c8c7d1326c490f9a9c168e3e6c4963
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-25 at: http://localhost:5000/#/experiments/2/runs/eb19896d08fa4bbdaa9de59c923f2f3e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-26 at: http://localhost:5000/#/experiments/2/runs/8dca5a833c044c3ba3411b15d45d604f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-27 at: http://localhost:5000/#/experiments/2/runs/e28a23e135ef4b83abe5a3cea1a14114
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-28 at: http://localhost:5000/#/experiments/2/runs/938fc92d183442d0b94f718b3b363f35
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-29 at: http://localhost:5000/#/experiments/2/runs/2bbdc8c55a9c4e5792d1ed023dd0407e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-30 at: http://localhost:5000/#/experiments/2/runs/b93e31646e4745048bf00c7012fc1e7d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-31 at: http://localhost:5000/#/experiments/2/runs/c9d774f785c94422bc6cc3ad35ee2010
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-32 at: http://localhost:5000/#/experiments/2/runs/6e49f8ae9c6d4c3d90ca6a8306678b6f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-33 at: http://localhost:5000/#/experiments/2/runs/bdd525229f794cddac8e8f0b7865eee5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-34 at: http://localhost:5000/#/experiments/2/runs/1878efdc3e4b4c69a48593fc54522ec4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-35 at: http://localhost:5000/#/experiments/2/runs/a4273b0ee2394bf684a2f6eff78be4ee
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-36 at: http://localhost:5000/#/experiments/2/runs/3bf20f61cd7148809260e8180765021c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-lstm-trial-37 at: http://localhost:5000/#/experiments/2/runs/da485011a7744908b89631a8e6d7323a

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
0,validation,CBOM,lstm,126,0.040798,0.053580,-0.019573,0.127722,0.160861,0.539683,week,5,mature,False,1254,1260,6,2506,1260,2020-10-19,2025-08-27,1,True
1,validation,MBNK,lstm,107,0.031755,0.039951,-0.778303,0.049785,0.040224,0.467290,week,5,limited_history,True,317,323,6,323,1260,2024-09-05,2025-10-06,1,True
2,validation,SBER,lstm,126,0.018986,0.024399,-0.130739,0.109235,0.093501,0.492063,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,1,True
3,validation,SBERP,lstm,126,0.017720,0.023213,-0.070505,0.032317,0.001749,0.460317,week,5,mature,False,1254,1260,6,4377,1260,2020-10-19,2025-08-27,1,True
4,validation,SVCB,lstm,126,0.030408,0.039251,-0.225646,-0.091873,-0.117846,0.547619,week,5,limited_history,True,378,384,6,384,1260,2024-04-27,2025-08-27,1,True
5,validation,T,lstm,126,0.024632,0.032218,-0.035112,-0.021386,-0.086086,0.468254,week,5,mature,False,1254,1260,6,1381,1260,2020-09-07,2025-08-19,1,True
6,validation,VTBR,lstm,126,0.022967,0.028678,-0.117038,-0.020879,0.051612,0.492063,week,5,mature,False,1254,1260,6,4333,1260,2020-10-13,2025-08-27,1,True

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,lstm,126,0.049306,0.092517,-0.046358,-0.134147,-0.135856,0.388889,week,5,mature,False,1254,1260,6,2632,1260,2021-04-20,2026-01-18,1,True,0.539683
1,test,MBNK,lstm,107,0.013236,0.016505,-0.072765,0.152652,0.130146,0.644860,week,5,limited_history,True,424,430,6,430,1260,2024-09-05,2026-02-06,1,True,0.467290
2,test,SBER,lstm,126,0.010453,0.012837,-0.476896,0.289453,0.265836,0.571429,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,1,True,0.492063
3,test,SBERP,lstm,126,0.007950,0.009783,0.081467,0.319072,0.301957,0.571429,week,5,mature,False,1254,1260,6,4503,1260,2021-04-20,2026-01-18,1,True,0.460317
4,test,SVCB,lstm,126,0.024117,0.031398,-0.686307,-0.041226,0.024735,0.571429,week,5,limited_history,True,504,510,6,510,1260,2024-04-27,2026-01-18,1,True,0.547619
5,test,T,lstm,126,0.015213,0.019959,-0.006354,0.131045,0.181648,0.595238,week,5,mature,False,1254,1260,6,1507,1260,2021-03-09,2026-01-12,1,True,0.468254
6,test,VTBR,lstm,126,0.030230,0.041466,-0.071279,-0.109071,-0.168924,0.468254,week,5,mature,False,1254,1260,6,4459,1260,2021-04-14,2026-01-18,1,True,0.492063

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning
0,-0.150949,-0.279112,0.060210,252.0,-4.635654,-4.630435,-0.161643,-1.726712,0.036508,23,CBOM,lstm,overlapping_tranches,126,False
1,-0.095360,-0.210242,0.046923,252.0,-4.480557,-5.530781,-0.117536,-1.788745,0.052336,28,MBNK,lstm,overlapping_tranches,107,False
2,0.040769,0.083199,0.022798,252.0,3.649421,5.818833,-0.010386,8.010645,0.034921,22,SBER,lstm,overlapping_tranches,126,False
3,0.046662,0.095501,0.020093,252.0,4.753003,13.557603,-0.005332,17.910154,0.036508,23,SBERP,lstm,overlapping_tranches,126,False
4,-0.051624,-0.100583,0.029740,252.0,-3.382037,-2.506247,-0.069910,-1.438744,0.015873,10,SVCB,lstm,overlapping_tranches,126,False
5,-0.012485,-0.024815,0.036265,252.0,-0.684260,-0.847128,-0.047910,-0.517954,0.014286,9,T,lstm,overlapping_tranches,126,False
6,-0.013680,-0.027173,0.081764,252.0,-0.332338,-0.451132,-0.125093,-0.217226,0.020635,13,VTBR,lstm,overlapping_tranches,126,False
7,-0.152279,-0.274027,0.173587,50.4,-1.578615,-1.721590,-0.191957,-1.427541,0.269231,7,CBOM,lstm,non_overlapping,26,False
8,-0.114536,-0.243214,0.104851,50.4,-2.319625,-3.169364,-0.152538,-1.594448,0.227273,5,MBNK,lstm,non_overlapping,22,False
9,0.057656,0.114784,0.050989,50.4,2.251165,13.893202,-0.004551,25.221640,0.384615,10,SBER,lstm,non_overlapping,26,False
10,0.055416,0.110212,0.051066,50.4,2.158238,10.457387,-0.005458,20.194139,0.500000,13,SBERP,lstm,non_overlapping,26,False
11,-0.044940,-0.085276,0.053466,50.4,-1.594953,-1.069142,-0.047595,-1.791711,0.153846,4,SVCB,lstm,non_overlapping,26,False
12,-0.025872,-0.049543,0.078122,50.4,-0.634170,-0.730236,-0.046013,-1.076719,0.269231,7,T,lstm,non_overlapping,26,False
13,0.034037,0.067031,0.163428,50.4,0.410159,0.686224,-0.091538,0.732278,0.346154,9,VTBR,lstm,non_overlapping,26,False

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=863
2,test predictions are available,True,rows=863
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

🏃 View run month-lstm-trial-0 at: http://localhost:5000/#/experiments/2/runs/e5d461150143416288a5cab213e7152e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-1 at: http://localhost:5000/#/experiments/2/runs/2bbdcff97e2b4311b841199d67961387
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-2 at: http://localhost:5000/#/experiments/2/runs/87bdd5e7562b44edbfbcb08d0e10a112
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-3 at: http://localhost:5000/#/experiments/2/runs/1dc65f5b59c041349e2fbc7cc3aed616
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-4 at: http://localhost:5000/#/experiments/2/runs/4a6e8866b60949878f72ffb2c12fee76
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-5 at: http://localhost:5000/#/experiments/2/runs/27856929ee29427eb49d01086fffdc39
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-6 at: http://localhost:5000/#/experiments/2/runs/5bbe30379103481094b90e495b46ab5a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-7 at: http://localhost:5000/#/experiments/2/runs/94bf02aa64f44eb5ac5affd067e2114f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-8 at: http://localhost:5000/#/experiments/2/runs/a7cc6cf3059947db90c8bbf0b666568c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-9 at: http://localhost:5000/#/experiments/2/runs/cadd16f0ff0242a89d37786b338937cf
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-10 at: http://localhost:5000/#/experiments/2/runs/3f97fca4f9c04511b939f4ee6782a2fb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-11 at: http://localhost:5000/#/experiments/2/runs/edfc85d420f243959364089e92570ec0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-12 at: http://localhost:5000/#/experiments/2/runs/ae1e922ba9ae49fe98e051330141ddd1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-13 at: http://localhost:5000/#/experiments/2/runs/7f0d2c2e9b8c48809966f3c78233aa1e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-14 at: http://localhost:5000/#/experiments/2/runs/31360e00b484470c9c52a14eee823b3b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-15 at: http://localhost:5000/#/experiments/2/runs/b749eec515ba49369cf57ae249afc0ba
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-16 at: http://localhost:5000/#/experiments/2/runs/9d3cb7f2c4044acb9d0b1c7f2f87fb08
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-17 at: http://localhost:5000/#/experiments/2/runs/741484623fb84a96bd277a522cc77321
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-18 at: http://localhost:5000/#/experiments/2/runs/f7a8e8cdd54b4d318591639d13facb95
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-19 at: http://localhost:5000/#/experiments/2/runs/f3d32f859f8b44308691922c12684bb7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-20 at: http://localhost:5000/#/experiments/2/runs/bf6c479c67504d768e5941a5e3169988
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-21 at: http://localhost:5000/#/experiments/2/runs/dfa377b674a047ec81c507cd4963876b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-22 at: http://localhost:5000/#/experiments/2/runs/d16cc783597f4afd8591ec0f29a8f64c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-23 at: http://localhost:5000/#/experiments/2/runs/2f93997c946943369585bd3ca8d228ad
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-24 at: http://localhost:5000/#/experiments/2/runs/319b6ca7894948de8ee3ee06d9642542
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-25 at: http://localhost:5000/#/experiments/2/runs/43277ff324994faab3f213a76990d4f0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-26 at: http://localhost:5000/#/experiments/2/runs/48d3f0a8aae7496cbe08ac27ce9b3a39
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-27 at: http://localhost:5000/#/experiments/2/runs/006851e9414d40819b28e91df9535f09
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-28 at: http://localhost:5000/#/experiments/2/runs/18873ff34c8440a8b70c78ffa249d0a0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-29 at: http://localhost:5000/#/experiments/2/runs/9b0deaa2d8cc46fca64ee29d01355730
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-30 at: http://localhost:5000/#/experiments/2/runs/21cd07f45e0e426ebcbf45bd1a1529cd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-31 at: http://localhost:5000/#/experiments/2/runs/ec8518d58cc94f2ca04b51a758418c1a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-32 at: http://localhost:5000/#/experiments/2/runs/42b58f1c48ce4d1ea7f77d351e477aa3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-33 at: http://localhost:5000/#/experiments/2/runs/6aca1c9f6bb048209a1c24d155548240
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-34 at: http://localhost:5000/#/experiments/2/runs/c47653dde1d1440db96ece95d81d7093
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-35 at: http://localhost:5000/#/experiments/2/runs/0f5f1e7c841a47668cdb4966afa09649
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-36 at: http://localhost:5000/#/experiments/2/runs/733af5fb10074264b688284431b1755e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-37 at: http://localhost:5000/#/experiments/2/runs/f54febbcdbec4c30a8034c5d5f6cc555
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-38 at: http://localhost:5000/#/experiments/2/runs/b9d6edbb9ac549cbb2bee80e57479952
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-39 at: http://localhost:5000/#/experiments/2/runs/ecb46cb9fce0487fa438771bfd35bdbd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-40 at: http://localhost:5000/#/experiments/2/runs/c9e5a088d12f46baace6e2d2e8e840ef
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-41 at: http://localhost:5000/#/experiments/2/runs/ecb31837ffaf409eaee741501f3ca72d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-42 at: http://localhost:5000/#/experiments/2/runs/4ed1f780b8d84a1eacf8ee5267f7219d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-43 at: http://localhost:5000/#/experiments/2/runs/4dc8a30792fb496994b6e96dfa3780b0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-44 at: http://localhost:5000/#/experiments/2/runs/8f011d6b2404471a998be08535b18202
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-45 at: http://localhost:5000/#/experiments/2/runs/6dfbc17749ea4148a26e08caf0942aca
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-46 at: http://localhost:5000/#/experiments/2/runs/3987dd78179742ddb90fca4a2dc752b8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-47 at: http://localhost:5000/#/experiments/2/runs/5d4c8ba7e81247bca4e5a208cf868b35
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-48 at: http://localhost:5000/#/experiments/2/runs/6d85c27ae16f43c18d72c9a52c83b864
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-49 at: http://localhost:5000/#/experiments/2/runs/5c39933853cc43458cd531b7a2a999ee
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-50 at: http://localhost:5000/#/experiments/2/runs/5d1c63ecef7d4ccfa6f07b67e48d3afb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-51 at: http://localhost:5000/#/experiments/2/runs/3dd7038df5974bf4846c6037e0b5b1fd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-52 at: http://localhost:5000/#/experiments/2/runs/f07f48aec450435f983f9c4764ba267f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-53 at: http://localhost:5000/#/experiments/2/runs/d758782b68224136b11b56f4f70626c8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-54 at: http://localhost:5000/#/experiments/2/runs/3eb218b885164ba39417617534820488
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-55 at: http://localhost:5000/#/experiments/2/runs/d20a1f16080d48f5b1957eb6e00a3cb3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-56 at: http://localhost:5000/#/experiments/2/runs/70b419b8c8044660939547409bbf8fb1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-57 at: http://localhost:5000/#/experiments/2/runs/c5bf5386a25f491e8eb74e075df1d2c5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-58 at: http://localhost:5000/#/experiments/2/runs/8e893ad6c056439086bffc53316e7172
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-59 at: http://localhost:5000/#/experiments/2/runs/923625cf4b894293829054bb0f5365d7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-0 at: http://localhost:5000/#/experiments/2/runs/3c17861fb70d4d95a7d30cacda405589
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-1 at: http://localhost:5000/#/experiments/2/runs/fd255dc274b2402191839a6ed030f1ca
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-2 at: http://localhost:5000/#/experiments/2/runs/b1b0318a13024fff94bc0672e1853891
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-3 at: http://localhost:5000/#/experiments/2/runs/5fa47787c3d54f769de27938d76d3da3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-4 at: http://localhost:5000/#/experiments/2/runs/85ea719c8b174a1c948ec3fe31bcf670
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-5 at: http://localhost:5000/#/experiments/2/runs/e724eb6e196f44a98a5f6c6afc192cb8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-6 at: http://localhost:5000/#/experiments/2/runs/0c4ff88e5e4b467caf4e6df0936d6f31
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-7 at: http://localhost:5000/#/experiments/2/runs/4d051c35b34d45a7a161493d036e42eb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-8 at: http://localhost:5000/#/experiments/2/runs/5b37aaa609554f45baac3147880cc561
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-9 at: http://localhost:5000/#/experiments/2/runs/18437a51966047d6a435a0488f26220b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-10 at: http://localhost:5000/#/experiments/2/runs/ee350f0554db4f4393044aa4002b47aa
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-11 at: http://localhost:5000/#/experiments/2/runs/6537aae1105444ae88728d8aa21396a3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-12 at: http://localhost:5000/#/experiments/2/runs/480fd3d5f5114155a79abf232869b2f5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-13 at: http://localhost:5000/#/experiments/2/runs/43ffb17f8d59410bb42ffe8376c5d484
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-14 at: http://localhost:5000/#/experiments/2/runs/bc89134c8e804041bc3b2b06446e296c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-15 at: http://localhost:5000/#/experiments/2/runs/35b567b897b840f9bae21228fb41c6a6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-16 at: http://localhost:5000/#/experiments/2/runs/1a8be146b1df40aeaf7a16dcc38121a5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-17 at: http://localhost:5000/#/experiments/2/runs/1591a8226ff84dd7ac82d0be15c0e7ae
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-18 at: http://localhost:5000/#/experiments/2/runs/56bc7f08dee6445c8649660e2c3a0c37
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-19 at: http://localhost:5000/#/experiments/2/runs/a14177767b2d4bb694199c8a18efbf63
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-0 at: http://localhost:5000/#/experiments/2/runs/6994db12ad764e258192a82a9ebe6235
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-1 at: http://localhost:5000/#/experiments/2/runs/73ac8acbe14b455aad2ca7c8f59c33d0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-2 at: http://localhost:5000/#/experiments/2/runs/fa56383b5ae74152acb79a620e0abdac
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-3 at: http://localhost:5000/#/experiments/2/runs/6f92b4701f654a5494355976ec87a4e5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-4 at: http://localhost:5000/#/experiments/2/runs/5fb65c5e19954adab4de600bdc5776ff
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-5 at: http://localhost:5000/#/experiments/2/runs/c3fc9296d8b3450c84f3593c18e8da2d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-6 at: http://localhost:5000/#/experiments/2/runs/08bfd784b14048f1b677bbb471731401
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-7 at: http://localhost:5000/#/experiments/2/runs/5d7d60ba44cb40b294ba58ec2a8de4e5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-8 at: http://localhost:5000/#/experiments/2/runs/702b04c32bde46e0b6cb1209e111a9ae
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-9 at: http://localhost:5000/#/experiments/2/runs/12a6e36dae294116aad63893bc5a245d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-10 at: http://localhost:5000/#/experiments/2/runs/37ec130d982a4bc1b06fe08f04481e82
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-11 at: http://localhost:5000/#/experiments/2/runs/cd50c9b0865e49ca822e286b13b55f0a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-12 at: http://localhost:5000/#/experiments/2/runs/4e56234f3f5848bba2d3fe63c2595830
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-13 at: http://localhost:5000/#/experiments/2/runs/0d29ae00f77141a4babf0dac31dddb88
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-14 at: http://localhost:5000/#/experiments/2/runs/28f5a45dae014982b0d75328d997c4a0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-15 at: http://localhost:5000/#/experiments/2/runs/024ea55300024ea6a7198dd2af4defd8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-16 at: http://localhost:5000/#/experiments/2/runs/a960830c5d844060b54c6ab69caed9d4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-17 at: http://localhost:5000/#/experiments/2/runs/fe50bca3c2054348b99ffa4c20be1d0e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-18 at: http://localhost:5000/#/experiments/2/runs/91d38814ea714d9c855b8622c23e66cd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-19 at: http://localhost:5000/#/experiments/2/runs/d6bac15439304af19f4b6626f3a993c1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-20 at: http://localhost:5000/#/experiments/2/runs/c1e6d84362b34e19b7f026a07ed9cc54
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-21 at: http://localhost:5000/#/experiments/2/runs/69e1044d59a94a03adb8326c6e699536
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-22 at: http://localhost:5000/#/experiments/2/runs/6929b9dcb021486d9dfa87740921ff0b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-23 at: http://localhost:5000/#/experiments/2/runs/90be7c130278424781df50d0d658376b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-24 at: http://localhost:5000/#/experiments/2/runs/5a0de87ecb3249688252fd21c8728ce4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-25 at: http://localhost:5000/#/experiments/2/runs/e9592dc738764bce9cebc00abafe5e2f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-26 at: http://localhost:5000/#/experiments/2/runs/7eb4493cac0a48d991671e4b48a12e9b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-27 at: http://localhost:5000/#/experiments/2/runs/ede52c4caf1440dfb205d3870c968f6f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-28 at: http://localhost:5000/#/experiments/2/runs/bc5893c189f94f82bc689f01a6f0035e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-29 at: http://localhost:5000/#/experiments/2/runs/6c19bb2af64e44f5bf4d3bef789a6d8c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-30 at: http://localhost:5000/#/experiments/2/runs/2abdcfbc15cf4c9b95fca4541381b8d6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-31 at: http://localhost:5000/#/experiments/2/runs/c9465426ee0b48b1ac0a46c6adc1f656
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-32 at: http://localhost:5000/#/experiments/2/runs/3fb3234f08dc4aa393007fa26a145b48
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-33 at: http://localhost:5000/#/experiments/2/runs/4374648e7f4c4986832e831e5c5ea165
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-34 at: http://localhost:5000/#/experiments/2/runs/f60bb6770dbb45499b4a4e9aadbd0e96
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-35 at: http://localhost:5000/#/experiments/2/runs/f105ddb8ebf0466895fc8ac88d1229ad
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-lstm-trial-36 at: http://localhost:5000/#/experiments/2/runs/ca0ca42679c2410a8ecb22a77a1b2fe9
🧪 View experiment at: http://localhost:5000/#/experiments/2

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
0,validation,CBOM,lstm,126,0.092275,0.108165,0.047765,0.439552,0.476493,0.658730,month,21,mature,False,1238,1260,22,2490,1260,2020-09-25,2025-07-22,1,True
1,validation,MBNK,lstm,104,0.038649,0.045623,-0.861250,0.018551,-0.038835,0.778846,month,21,limited_history,True,291,313,22,313,1260,2024-09-05,2025-09-08,1,True
2,validation,SBER,lstm,126,0.046689,0.058747,-1.635128,-0.119352,-0.043708,0.460317,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,1,True
3,validation,SBERP,lstm,126,0.045689,0.056901,-1.790630,-0.470200,-0.403813,0.380952,month,21,mature,False,1238,1260,22,4361,1260,2020-09-25,2025-07-22,1,True
4,validation,SVCB,lstm,124,0.065022,0.083662,-0.498071,-0.259292,-0.285759,0.354839,month,21,limited_history,True,350,372,22,372,1260,2024-04-27,2025-07-26,1,True
5,validation,T,lstm,126,0.046046,0.055880,-0.157750,-0.190266,-0.178685,0.452381,month,21,mature,False,1238,1260,22,1365,1260,2020-08-14,2025-07-14,1,True
6,validation,VTBR,lstm,126,0.063580,0.072411,-1.233909,-0.281288,-0.236541,0.492063,month,21,mature,False,1238,1260,22,4317,1260,2020-09-21,2025-07-22,1,True

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,lstm,126,0.167949,0.182458,-0.823342,-0.096922,-0.090676,0.365079,month,21,mature,False,1238,1260,22,2616,1260,2021-03-29,2025-12-09,1,True,0.658730
1,test,MBNK,lstm,104,0.045377,0.051883,-2.123606,-0.382999,-0.304225,0.211538,month,21,limited_history,True,395,417,22,417,1260,2024-09-05,2026-01-05,1,True,0.778846
2,test,SBER,lstm,126,0.015344,0.019473,-0.734067,0.587379,0.542773,0.698413,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,1,True,0.460317
3,test,SBERP,lstm,126,0.016853,0.019394,-0.832970,0.372887,0.397183,0.738095,month,21,mature,False,1238,1260,22,4487,1260,2021-03-29,2025-12-09,1,True,0.380952
4,test,SVCB,lstm,124,0.040215,0.052134,-0.008997,0.144790,0.096636,0.669355,month,21,limited_history,True,474,496,22,496,1260,2024-04-27,2025-12-11,1,True,0.354839
5,test,T,lstm,126,0.039992,0.045812,-0.687692,-0.565901,-0.543727,0.396825,month,21,mature,False,1238,1260,22,1491,1260,2021-02-12,2025-12-01,1,True,0.452381
6,test,VTBR,lstm,126,0.090983,0.113733,-0.319198,-0.575229,-0.596382,0.357143,month,21,mature,False,1238,1260,22,4443,1260,2021-03-23,2025-12-09,1,True,0.492063

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning
0,0.087485,0.182623,0.082664,252.0,2.209220,6.167579,-0.131442,1.389386,0.000756,2,CBOM,lstm,overlapping_tranches,126,False
1,-0.035372,-0.083563,0.013676,252.0,-6.110315,-4.237457,-0.035372,-2.362397,0.004579,10,MBNK,lstm,overlapping_tranches,104,False
2,0.056362,0.115900,0.010590,252.0,10.944537,86.053387,-0.000628,184.440845,0.002268,6,SBER,lstm,overlapping_tranches,126,False
3,0.027840,0.056456,0.007893,252.0,7.152237,258.267234,-0.000201,281.394064,0.006047,16,SBERP,lstm,overlapping_tranches,126,False
4,-0.034055,-0.067993,0.015273,252.0,-4.451794,-2.855042,-0.036519,-1.861825,0.003072,8,SVCB,lstm,overlapping_tranches,124,False
5,-0.075821,-0.145892,0.016243,252.0,-8.981792,-9.048413,-0.076924,-1.896586,0.006803,18,T,lstm,overlapping_tranches,126,False
6,-0.058384,-0.113360,0.060793,252.0,-1.864680,-2.141747,-0.151714,-0.747193,0.003401,9,VTBR,lstm,overlapping_tranches,126,False
7,0.058381,0.120171,0.340925,12.0,0.352485,0.841361,-0.134556,0.893097,0.333333,2,CBOM,lstm,non_overlapping,6,True
8,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,MBNK,lstm,non_overlapping,5,True
9,0.026047,0.052773,0.033127,12.0,1.593030,NaN,-0.001499,35.208427,0.666667,4,SBER,lstm,non_overlapping,6,True
10,0.072147,0.149498,0.047914,12.0,3.120116,NaN,-0.001499,99.740182,0.333333,2,SBERP,lstm,non_overlapping,6,True
11,0.023896,0.048364,0.036003,12.0,1.343336,NaN,-0.001499,32.266642,0.333333,2,SVCB,lstm,non_overlapping,6,True
12,-0.097940,-0.186288,0.090205,12.0,-2.065150,-1.889688,-0.097940,-1.902060,0.333333,2,T,lstm,non_overlapping,6,True
13,0.192522,0.422109,0.223284,12.0,1.890459,10.914605,-0.041585,10.150594,0.500000,3,VTBR,lstm,non_overlapping,6,True

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=858
2,test predictions are available,True,rows=858
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

## Next Step

Run `03_model_comparison.ipynb` after this notebook. The comparison notebook loads `lstm_only` reports directly and combines them with table-model and optional global-LSTM reports.