# 02b LSTM-Only Strict Forecasting

Use this notebook when table-model artifacts from `02_table_model_forecasting.ipynb` are already acceptable and you want to iterate only on the per-ticker LSTM. It trains LSTM models into an isolated `lstm_only/strict_protocol` artifact tree, then merges LSTM rows into the main strict reports so `03_model_comparison.ipynb` can compare all models without rerunning table models.

In [1]:
from pathlib import Path
import sys

cwd = Path.cwd().resolve()
for candidate in [cwd, cwd / "forecasting", cwd.parent, cwd.parent / "forecasting"]:
    if (candidate / "src" / "stock_forecast").exists():
        PROJECT_DIR = candidate
        break
else:
    raise RuntimeError("Cannot locate forecasting project directory with src/stock_forecast")

SRC_DIR = PROJECT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

ARTIFACT_DIR = PROJECT_DIR / "artifacts"
DATA_DIR = ARTIFACT_DIR / "data"
REPORTS_DIR = ARTIFACT_DIR / "reports"
for path in [DATA_DIR, REPORTS_DIR]:
    path.mkdir(parents=True, exist_ok=True)

print(f"PROJECT_DIR = {PROJECT_DIR}")

PROJECT_DIR = /home/sapce/forecasting_stock_prices/forecasting

In [2]:
import importlib.util
import json
import shutil

import pandas as pd
from IPython.display import display

from stock_forecast.artifacts import load_json, load_table, save_json, save_table
from stock_forecast.models import build_model
from stock_forecast.strict_protocol import (
    run_strict_per_ticker_protocol,
    strict_protocol_leakage_audit,
    _strict_metrics,
    _validation_ranking,
)
from stock_forecast.utils import ensure_dir

pd.set_option("display.max_columns", 180)

## Constants

In [3]:
if importlib.util.find_spec("torch") is None:
    raise ImportError("PyTorch is required for this notebook. Install the forecasting[deep] extra.")

FORCE_RETRAIN = True  # set True when you want to retune/retrain LSTM even if matching cache exists
PRIMARY_METRIC = "directional_accuracy"
RANDOM_STATE = 42

STRICT_VALIDATION_ROWS = 126
STRICT_TEST_ROWS = 126
MATURE_MIN_ROWS = 1008
LIMITED_HISTORY_MIN_BLOCK_ROWS = 42
MIN_TRAIN_ROWS = 60
STRICT_MAX_TRAIN_ROWS = 1260
INNER_MAX_FOLDS = 3
INNER_MIN_TRAIN_ROWS = 126
LIMITED_HISTORY_N_TRIALS = 20

LSTM_N_TRIALS = 60
LSTM_OPTUNA_N_JOBS = 1
LSTM_MAX_EPOCHS = 150
LSTM_PATIENCE = 15
LSTM_DEVICE = "auto"
LSTM_ENSEMBLE_SEEDS = [1, 7, 21, 42, 101]

TRANSACTION_COST_BPS = 10
SLIPPAGE_BPS = 5
LONG_THRESHOLD = 0.0
SIGNAL_ANCHOR = "expanding_median"

MERGE_LSTM_INTO_MAIN_STRICT_REPORTS = True
LSTM_ONLY_ARTIFACT_NAME = "lstm_only"

HORIZONS = [
    {"name": "week", "horizon": 5},
    {"name": "month", "horizon": 21},
]

In [4]:
def make_lstm_search_space(horizon: int, limited_history: bool = False) -> dict:
    huber_beta_choices = [0.04, 0.08, 0.12] if horizon >= 21 else [0.02, 0.04, 0.06]
    return {
        "lookback": {"type": "categorical", "choices": [20, 40, 60] if limited_history else [20, 40, 60, 90, 126]},
        "hidden_size": {"type": "categorical", "choices": [16, 32, 64, 96, 128]},
        "num_layers": {"type": "categorical", "choices": [1] if limited_history else [1, 2]},
        "input_projection_size": {"type": "categorical", "choices": [0, 32, 64, 128]},
        "lstm_dropout": {"type": "float", "low": 0.0, "high": 0.35},
        "head_dropout": {"type": "float", "low": 0.15, "high": 0.55},
        "learning_rate": {"type": "float", "low": 1e-4, "high": 2e-3, "log": True},
        "weight_decay": {"type": "float", "low": 1e-5, "high": 1e-2, "log": True},
        "batch_size": {"type": "categorical", "choices": [16, 32, 64] if limited_history else [32, 64, 128]},
        "loss": {"type": "categorical", "choices": ["smooth_l1", "huber", "mse"]},
        "huber_beta": {"type": "categorical", "choices": huber_beta_choices},
        "feature_clip": {"type": "categorical", "choices": [3.0, 5.0, 8.0]},
        "grad_clip_norm": {"type": "float", "low": 0.5, "high": 2.0},
    }


def make_lstm_config(lstm_feature_cols: list[str], horizon: int) -> dict:
    return {
        "name": "lstm",
        "model_type": "lstm",
        "estimator_factory": build_model,
        "input_mode": "full_frame",
        "feature_cols": lstm_feature_cols,
        "static_params": {
            "max_epochs": LSTM_MAX_EPOCHS,
            "patience": LSTM_PATIENCE,
            "device": LSTM_DEVICE,
        },
        "search_space": make_lstm_search_space(horizon, limited_history=False),
        "limited_history_search_space": make_lstm_search_space(horizon, limited_history=True),
        "post_selection_static_params": {"ensemble_seeds": LSTM_ENSEMBLE_SEEDS},
        "n_trials": LSTM_N_TRIALS,
        "optuna_n_jobs": LSTM_OPTUNA_N_JOBS,
        "limited_history_n_trials": LIMITED_HISTORY_N_TRIALS,
        "needs_scaler": False,
    }

## Load LSTM Data Artifacts

In [5]:
horizon_inputs = []

for spec in HORIZONS:
    horizon_name = spec["name"]
    horizon = int(spec["horizon"])
    base_feature_payload = load_json(DATA_DIR / "horizons" / horizon_name / "feature_columns.json")
    target_col = base_feature_payload["target_column"]

    lstm_dir = DATA_DIR / "lstm" / "horizons" / horizon_name
    lstm_model_path = lstm_dir / "model_dataset.parquet"
    lstm_feature_path = lstm_dir / "feature_columns.json"
    if not lstm_model_path.exists() and not lstm_model_path.with_suffix(".csv").exists():
        raise FileNotFoundError(
            f"Missing LSTM data for {horizon_name}: {lstm_model_path}. "
            "Run notebooks/01b_lstm_eda.ipynb first."
        )
    if not lstm_feature_path.exists():
        raise FileNotFoundError(f"Missing LSTM feature payload for {horizon_name}: {lstm_feature_path}")

    lstm_payload = load_json(lstm_feature_path)
    if lstm_payload["target_column"] != target_col:
        raise ValueError(f"LSTM target mismatch for {horizon_name}: {lstm_payload['target_column']} != {target_col}")

    model_df = load_table(lstm_model_path)
    model_df["date"] = pd.to_datetime(model_df["date"])
    lstm_feature_cols = lstm_payload["feature_columns"]
    model_configs = [make_lstm_config(lstm_feature_cols, horizon)]

    horizon_inputs.append({
        "horizon_name": horizon_name,
        "horizon": horizon,
        "model_df": model_df,
        "feature_cols": base_feature_payload["feature_columns"],
        "lstm_feature_cols": lstm_feature_cols,
        "target_col": target_col,
        "model_configs": model_configs,
        "lstm_only_artifact_dir": ARTIFACT_DIR / "horizons" / horizon_name / LSTM_ONLY_ARTIFACT_NAME,
        "main_artifact_dir": ARTIFACT_DIR / "horizons" / horizon_name,
    })

    print({
        "horizon": horizon_name,
        "rows": len(model_df),
        "lstm_features": len(lstm_feature_cols),
        "target": target_col,
        "lstm_only_artifact_dir": str((ARTIFACT_DIR / "horizons" / horizon_name / LSTM_ONLY_ARTIFACT_NAME).relative_to(PROJECT_DIR)),
    })
    display(model_df[["date", "ticker", target_col, *lstm_feature_cols[:6]]].head())

{'horizon': 'week', 'rows': 17880, 'lstm_features': 160, 'target': 'target_return_5_next_open', 'lstm_only_artifact_dir': 'artifacts/horizons/week/lstm_only'}

,date,ticker,target_return_5_next_open,log_close,ret_1,open_close_ret,high_low_range,close_to_high,close_to_low
0,2015-11-09,CBOM,0.013316,1.321756,-0.003992,0.000000,0.000000,0.000000,0.000000
1,2015-11-10,CBOM,0.019908,1.320422,-0.001334,0.004013,0.004005,0.000000,0.004021
2,2015-11-11,CBOM,0.005312,1.319086,-0.001336,0.002677,0.002674,0.000000,0.002681
3,2015-11-12,CBOM,0.010582,1.323088,0.004003,0.000000,0.000000,0.000000,0.000000
4,2015-11-13,CBOM,-0.002649,1.329724,0.006636,0.005305,0.300265,-0.227783,0.005319

{'horizon': 'month', 'rows': 17768, 'lstm_features': 160, 'target': 'target_return_21_next_open', 'lstm_only_artifact_dir': 'artifacts/horizons/month/lstm_only'}

,date,ticker,target_return_21_next_open,log_close,ret_1,open_close_ret,high_low_range,close_to_high,close_to_low
0,2015-11-09,CBOM,0.027761,1.321756,-0.003992,0.000000,0.000000,0.000000,0.000000
1,2015-11-10,CBOM,0.023842,1.320422,-0.001334,0.004013,0.004005,0.000000,0.004021
2,2015-11-11,CBOM,0.021081,1.319086,-0.001336,0.002677,0.002674,0.000000,0.002681
3,2015-11-12,CBOM,0.021053,1.323088,0.004003,0.000000,0.000000,0.000000,0.000000
4,2015-11-13,CBOM,0.011834,1.329724,0.006636,0.005305,0.300265,-0.227783,0.005319

## Train LSTM Only

In [6]:
lstm_results = {}

for item in horizon_inputs:
    horizon_name = item["horizon_name"]
    horizon = item["horizon"]
    result = run_strict_per_ticker_protocol(
        model_df=item["model_df"],
        feature_cols=item["feature_cols"],
        target_col=item["target_col"],
        model_configs=item["model_configs"],
        artifact_dir=item["lstm_only_artifact_dir"],
        force_retrain=FORCE_RETRAIN,
        primary_metric=PRIMARY_METRIC,
        random_state=RANDOM_STATE,
        run_metadata={
            "horizon_name": horizon_name,
            "horizon": horizon,
            "training_notebook": "02b_lstm_forecasting",
            "lstm_only_run": True,
        },
        validation_rows=STRICT_VALIDATION_ROWS,
        test_rows=STRICT_TEST_ROWS,
        mature_min_rows=MATURE_MIN_ROWS,
        limited_history_min_block_rows=LIMITED_HISTORY_MIN_BLOCK_ROWS,
        min_train_rows=MIN_TRAIN_ROWS,
        max_train_rows=STRICT_MAX_TRAIN_ROWS,
        inner_max_folds=INNER_MAX_FOLDS,
        inner_min_train_rows=INNER_MIN_TRAIN_ROWS,
        limited_history_n_trials=LIMITED_HISTORY_N_TRIALS,
        transaction_cost_bps=TRANSACTION_COST_BPS,
        slippage_bps=SLIPPAGE_BPS,
        long_threshold=LONG_THRESHOLD,
        signal_anchor=SIGNAL_ANCHOR,
    )
    lstm_results[horizon_name] = result

    print(f"=== LSTM-only strict protocol: {horizon_name} ({horizon} trading days) ===")
    display(result["validation_model_ranking"])
    display(result["test_prediction_metrics"])
    display(result["test_signal_metrics"])
    display(result["leakage_audit"])

    failed = result["leakage_audit"][~result["leakage_audit"]["passed"]]
    if not failed.empty:
        raise AssertionError(f"LSTM-only leakage audit failed for {horizon_name}: {failed['check'].tolist()}")

=== LSTM-only strict protocol: week (5 trading days) ===

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
0,validation,CBOM,lstm,126,0.050201,0.064949,-0.050582,0.017727,0.013129,0.460317,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,1,True
1,validation,MBNK,lstm,64,0.035874,0.047401,-1.229204,0.213218,0.205311,0.656250,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,1,True
2,validation,SBER,lstm,126,0.028419,0.040303,-0.062120,-0.032598,0.024960,0.515873,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,1,True
3,validation,SBERP,lstm,126,0.034334,0.047882,-0.704068,0.120428,0.151940,0.500000,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,1,True
4,validation,SVCB,lstm,83,0.042029,0.050334,-0.581120,0.130747,0.230637,0.469880,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,1,True
5,validation,T,lstm,126,0.044666,0.058931,-0.190015,0.015704,0.016627,0.476190,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,1,True
6,validation,VTBR,lstm,126,0.047678,0.065448,-0.100276,0.072973,0.091876,0.515873,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,1,True

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,lstm,126,0.032930,0.042199,-0.020033,0.044701,0.079877,0.539683,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,1,True,0.460317
1,test,MBNK,lstm,64,0.027314,0.039385,-0.038791,0.387282,0.447253,0.625000,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,1,True,0.656250
2,test,SBER,lstm,126,0.016785,0.020871,-0.262785,-0.107531,-0.158221,0.484127,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,1,True,0.515873
3,test,SBERP,lstm,126,0.018960,0.023584,-0.621203,-0.069474,-0.081893,0.476190,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,1,True,0.500000
4,test,SVCB,lstm,83,0.028785,0.038361,0.024605,0.205835,0.122455,0.698795,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,1,True,0.469880
5,test,T,lstm,126,0.022514,0.028851,-0.113026,0.035315,0.064411,0.603175,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,1,True,0.476190
6,test,VTBR,lstm,126,0.041385,0.069702,-0.055636,0.020533,0.059114,0.563492,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,1,True,0.515873

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning
0,0.032482,0.066018,0.112762,252.0,0.585464,0.894060,-0.145398,0.454050,0.014286,9,CBOM,lstm,overlapping_tranches,126,False
1,0.105406,0.483771,0.095615,252.0,5.059591,9.187456,-0.035494,13.629735,0.018750,6,MBNK,lstm,overlapping_tranches,64,False
2,-0.076245,-0.146676,0.044104,252.0,-3.325693,-3.973706,-0.112215,-1.307100,0.022222,14,SBER,lstm,overlapping_tranches,126,False
3,-0.059965,-0.116334,0.058124,252.0,-2.001478,-3.330499,-0.110333,-1.054386,0.030159,19,SBERP,lstm,overlapping_tranches,126,False
4,-0.133801,-0.353455,0.118152,252.0,-2.991526,-4.601191,-0.231166,-1.529013,0.028916,12,SVCB,lstm,overlapping_tranches,83,False
5,-0.011244,-0.022361,0.059983,252.0,-0.372783,-0.426275,-0.096451,-0.231835,0.049206,31,T,lstm,overlapping_tranches,126,False
6,-0.228242,-0.404389,0.211392,252.0,-1.912979,-1.706576,-0.308063,-1.312682,0.020635,13,VTBR,lstm,overlapping_tranches,126,False
7,0.131492,0.270578,0.262557,50.4,1.030551,1.957683,-0.140755,1.922329,0.192308,5,CBOM,lstm,non_overlapping,26,False
8,0.043339,0.178783,0.220048,50.4,0.812473,1.154788,-0.094292,1.896052,0.153846,2,MBNK,lstm,non_overlapping,13,False
9,-0.043073,-0.081807,0.095230,50.4,-0.859040,-1.148620,-0.113110,-0.723244,0.230769,6,SBER,lstm,non_overlapping,26,False
10,-0.031922,-0.060953,0.137346,50.4,-0.443789,-0.840761,-0.102087,-0.597064,0.038462,1,SBERP,lstm,non_overlapping,26,False
11,-0.148983,-0.380149,0.277648,50.4,-1.369177,-2.779346,-0.257957,-1.473692,0.294118,5,SVCB,lstm,non_overlapping,17,False
12,-0.054271,-0.102521,0.152950,50.4,-0.670291,-0.703612,-0.112137,-0.914248,0.500000,13,T,lstm,non_overlapping,26,False
13,-0.208696,-0.364753,0.455041,50.4,-0.801582,-0.792127,-0.317646,-1.148299,0.269231,7,VTBR,lstm,non_overlapping,26,False

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=777
2,test predictions are available,True,rows=777
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

=== LSTM-only strict protocol: month (21 trading days) ===

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
0,validation,CBOM,lstm,126,0.112675,0.140781,0.053557,0.265516,0.378274,0.484127,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,1,True
1,validation,MBNK,lstm,60,0.100523,0.132065,-6.077864,-0.413370,-0.396388,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,1,True
2,validation,SBER,lstm,126,0.078237,0.100344,-0.514296,-0.134038,-0.124559,0.452381,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,1,True
3,validation,SBERP,lstm,126,0.071503,0.097143,-0.520221,-0.057074,0.009392,0.563492,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,1,True
4,validation,SVCB,lstm,80,0.062049,0.075518,-1.366177,-0.233437,-0.225809,0.412500,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,1,True
5,validation,T,lstm,126,0.137494,0.173093,-1.715325,-0.304818,-0.289947,0.412698,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,1,True
6,validation,VTBR,lstm,126,0.127768,0.157085,-0.297985,-0.361763,-0.435315,0.404762,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,1,True

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,lstm,126,0.083184,0.104529,-0.096135,0.006361,-0.099531,0.539683,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,1,True,0.484127
1,test,MBNK,lstm,60,0.086591,0.117168,-0.390413,0.549681,0.553154,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,1,True,0.516667
2,test,SBER,lstm,126,0.042874,0.058081,-2.207627,-0.411589,-0.360498,0.404762,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,1,True,0.452381
3,test,SBERP,lstm,126,0.047963,0.061628,-2.677400,-0.587746,-0.592585,0.396825,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,1,True,0.563492
4,test,SVCB,lstm,80,0.082769,0.097270,-0.478333,-0.114033,-0.237084,0.575000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,1,True,0.412500
5,test,T,lstm,126,0.052956,0.060317,-0.883572,0.076077,0.099957,0.476190,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,1,True,0.412698
6,test,VTBR,lstm,126,0.092710,0.121403,-0.270523,0.424351,0.483879,0.531746,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,1,True,0.404762

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning
0,-0.084907,-0.162605,0.066523,252.0,-2.444355,-3.866116,-0.133474,-1.218252,0.002646,7,CBOM,lstm,overlapping_tranches,126,False
1,0.052121,0.237871,0.037271,252.0,6.382200,12.574307,-0.018113,13.132851,0.004762,6,MBNK,lstm,overlapping_tranches,60,False
2,-0.052468,-0.102183,0.022904,252.0,-4.461264,-4.952927,-0.078066,-1.308921,0.004157,11,SBER,lstm,overlapping_tranches,126,False
3,-0.068013,-0.131400,0.022450,252.0,-5.853017,-6.984339,-0.092607,-1.418905,0.006425,17,SBERP,lstm,overlapping_tranches,126,False
4,-0.136553,-0.370287,0.053174,252.0,-6.963633,-8.722467,-0.154443,-2.397568,0.006548,11,SVCB,lstm,overlapping_tranches,80,False
5,-0.002389,-0.004773,0.027097,252.0,-0.176128,-0.189565,-0.060760,-0.078549,0.010204,27,T,lstm,overlapping_tranches,126,False
6,-0.081151,-0.155716,0.055556,252.0,-2.802876,-2.911595,-0.125272,-1.243022,0.005669,15,VTBR,lstm,overlapping_tranches,126,False
7,0.024683,0.049975,0.361228,12.0,0.138346,0.273552,-0.075375,0.663013,0.166667,1,CBOM,lstm,non_overlapping,6,True
8,0.005674,0.022890,0.016028,12.0,1.428136,NaN,-0.001499,15.271650,0.666667,2,MBNK,lstm,non_overlapping,3,True
9,-0.069335,-0.133862,0.053126,12.0,-2.519688,-3.076817,-0.069335,-1.930665,0.166667,1,SBER,lstm,non_overlapping,6,True
10,-0.022692,-0.044870,0.074293,12.0,-0.603954,-0.799939,-0.055028,-0.815394,0.500000,3,SBERP,lstm,non_overlapping,6,True
11,0.000000,0.000000,0.000000,12.0,NaN,NaN,0.000000,NaN,0.000000,0,SVCB,lstm,non_overlapping,4,True
12,0.065084,0.134403,0.190667,12.0,0.704912,1.059681,-0.071103,1.890262,0.500000,3,T,lstm,non_overlapping,6,True
13,-0.025072,-0.049516,0.245032,12.0,-0.202078,-0.536958,-0.109018,-0.454197,0.500000,3,VTBR,lstm,non_overlapping,6,True

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=770
2,test predictions are available,True,rows=770
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

## Merge LSTM Rows Into Main Strict Reports

In [7]:
def table_exists(path: Path) -> bool:
    return path.exists() or path.with_suffix(".csv").exists()


def load_optional_table(path: Path) -> pd.DataFrame:
    return load_table(path) if table_exists(path) else pd.DataFrame()


def drop_model_rows(frame: pd.DataFrame, model_name: str = "lstm") -> pd.DataFrame:
    if frame.empty or "model_name" not in frame.columns:
        return frame.copy()
    return frame[frame["model_name"].astype(str) != model_name].copy()


def merge_model_rows(base: pd.DataFrame, addition: pd.DataFrame, model_name: str = "lstm") -> pd.DataFrame:
    if addition.empty:
        return drop_model_rows(base, model_name)
    return pd.concat([drop_model_rows(base, model_name), addition.copy()], ignore_index=True)


def merge_best_params(base_reports: Path, lstm_reports: Path) -> list[dict]:
    base_path = base_reports / "best_params.json"
    lstm_path = lstm_reports / "best_params.json"
    base_rows = load_json(base_path) if base_path.exists() else []
    lstm_rows = load_json(lstm_path) if lstm_path.exists() else []
    merged_rows = [row for row in base_rows if row.get("model_name") != "lstm"] + lstm_rows
    save_json(merged_rows, base_path)
    table = pd.DataFrame(merged_rows)
    if not table.empty and "best_params" in table.columns:
        table["best_params"] = table["best_params"].map(lambda value: json.dumps(value, sort_keys=True))
    save_table(table, base_reports / "best_params.parquet")
    return merged_rows


def copy_lstm_payloads(lstm_root: Path, main_root: Path) -> None:
    for subdir in ["models", "hyperparams"]:
        src = lstm_root / subdir / "lstm"
        dst = main_root / subdir / "lstm"
        if src.exists():
            ensure_dir(dst.parent)
            shutil.copytree(src, dst, dirs_exist_ok=True)


def merge_lstm_into_main(item: dict, result: dict) -> dict[str, pd.DataFrame]:
    main_root = item["main_artifact_dir"] / "strict_protocol"
    main_reports = main_root / "reports"
    lstm_root = item["lstm_only_artifact_dir"] / "strict_protocol"
    lstm_reports = lstm_root / "reports"
    ensure_dir(main_reports)

    required_main = [
        "validation_predictions.parquet",
        "test_predictions.parquet",
        "test_signal_equity.parquet",
        "test_signal_metrics.parquet",
    ]
    missing = [name for name in required_main if not table_exists(main_reports / name)]
    if missing:
        raise FileNotFoundError(
            f"Cannot merge LSTM into {main_reports}; missing existing table-model reports: {missing}. "
            "Run notebooks/02_table_model_forecasting.ipynb first, or set MERGE_LSTM_INTO_MAIN_STRICT_REPORTS = False."
        )

    copy_lstm_payloads(lstm_root, main_root)

    validation_predictions = merge_model_rows(
        load_table(main_reports / "validation_predictions.parquet"),
        result["validation_predictions"],
    )
    test_predictions = merge_model_rows(
        load_table(main_reports / "test_predictions.parquet"),
        result["test_predictions"],
    )
    validation_metrics = _strict_metrics(validation_predictions, "validation")
    ranking = _validation_ranking(validation_metrics, PRIMARY_METRIC)
    selected_models = ranking[ranking["is_validation_selected"]].copy() if not ranking.empty else pd.DataFrame()
    test_metrics = _strict_metrics(test_predictions, "test")
    if not ranking.empty and not test_metrics.empty:
        enrich = ranking[["ticker", "model_name", "validation_rank", "is_validation_selected", f"validation_{PRIMARY_METRIC}"]]
        test_metrics = test_metrics.merge(enrich, on=["ticker", "model_name"], how="left")

    signal_equity = merge_model_rows(load_table(main_reports / "test_signal_equity.parquet"), result["test_signal_equity"])
    signal_metrics = merge_model_rows(load_table(main_reports / "test_signal_metrics.parquet"), result["test_signal_metrics"])
    inner_tuning_metrics = merge_model_rows(
        load_optional_table(main_reports / "inner_tuning_metrics.parquet"),
        result.get("inner_tuning_metrics", pd.DataFrame()),
    )

    outer_splits = load_table(main_reports / "outer_splits.parquet") if table_exists(main_reports / "outer_splits.parquet") else result["outer_splits"]
    leakage_audit = strict_protocol_leakage_audit(
        outer_splits=outer_splits,
        validation_predictions=validation_predictions,
        test_predictions=test_predictions,
        models_dir=main_root / "models",
    )

    save_table(outer_splits, main_reports / "outer_splits.parquet")
    save_table(validation_predictions, main_reports / "validation_predictions.parquet")
    save_table(test_predictions, main_reports / "test_predictions.parquet")
    save_table(validation_metrics, main_reports / "validation_prediction_metrics.parquet")
    save_table(ranking, main_reports / "validation_model_ranking.parquet")
    save_table(selected_models, main_reports / "selected_models_by_ticker.parquet")
    save_table(test_metrics, main_reports / "test_prediction_metrics.parquet")
    save_table(signal_equity, main_reports / "test_signal_equity.parquet")
    save_table(signal_metrics, main_reports / "test_signal_metrics.parquet")
    save_table(leakage_audit, main_reports / "leakage_audit.parquet")
    if not inner_tuning_metrics.empty:
        save_table(inner_tuning_metrics, main_reports / "inner_tuning_metrics.parquet")
    merge_best_params(main_reports, lstm_reports)

    return {
        "validation_model_ranking": ranking,
        "selected_models_by_ticker": selected_models,
        "test_prediction_metrics": test_metrics,
        "test_signal_metrics": signal_metrics,
        "leakage_audit": leakage_audit,
    }


merged_results = {}
if MERGE_LSTM_INTO_MAIN_STRICT_REPORTS:
    for item in horizon_inputs:
        horizon_name = item["horizon_name"]
        merged = merge_lstm_into_main(item, lstm_results[horizon_name])
        merged_results[horizon_name] = merged
        print(f"=== Merged LSTM into main strict reports: {horizon_name} ===")
        display(merged["validation_model_ranking"])
        display(merged["test_prediction_metrics"])
        display(merged["leakage_audit"])
        failed = merged["leakage_audit"][~merged["leakage_audit"]["passed"]]
        if not failed.empty:
            raise AssertionError(f"Merged strict leakage audit failed for {horizon_name}: {failed['check'].tolist()}")
else:
    print("Skipping merge. LSTM-only artifacts remain under artifacts/horizons/{horizon}/lstm_only/strict_protocol.")

=== Merged LSTM into main strict reports: week ===

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
4,validation,CBOM,momentum,126,0.050542,0.064387,-0.032487,0.238607,0.135598,0.603175,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,1,True
6,validation,CBOM,ridge,126,0.057839,0.074645,-0.387685,0.016420,0.056540,0.523810,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,2,False
5,validation,CBOM,naive_persistence,126,0.056416,0.070545,-0.239402,0.014613,0.006740,0.500000,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,3,False
3,validation,CBOM,lstm,126,0.050201,0.064949,-0.050582,0.017727,0.013129,0.460317,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,4,False
2,validation,CBOM,lightgbm,126,0.053503,0.068831,-0.179917,-0.093521,-0.077801,0.452381,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,5,False
1,validation,CBOM,hist_gradient_boosting,126,0.055051,0.070015,-0.220879,-0.089669,-0.068302,0.436508,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,6,False
7,validation,CBOM,xgboost,126,0.051171,0.065275,-0.061157,NaN,NaN,0.420635,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,7,False
0,validation,CBOM,catboost,126,0.052434,0.067718,-0.142078,-0.022527,-0.067333,0.412698,week,5,mature,False,1254,1260,6,2287,1260,2019-12-02,2024-12-09,8,False
11,validation,MBNK,lstm,64,0.035874,0.047401,-1.229204,0.213218,0.205311,0.656250,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,1,True
14,validation,MBNK,ridge,64,0.197472,0.248458,-60.245625,0.147357,0.150504,0.640625,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,2,False
13,validation,MBNK,naive_persistence,64,0.029312,0.036138,-0.295647,-0.082903,0.010852,0.546875,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,3,False
15,validation,MBNK,xgboost,64,0.027514,0.032896,-0.073649,NaN,NaN,0.484375,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,4,False
10,validation,MBNK,lightgbm,64,0.027451,0.033000,-0.080418,0.304833,0.387448,0.484375,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,5,False
8,validation,MBNK,catboost,64,0.028403,0.035155,-0.226172,0.109994,0.123581,0.484375,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,6,False
9,validation,MBNK,hist_gradient_boosting,64,0.035755,0.044237,-0.941534,0.355216,0.437084,0.484375,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,7,False
12,validation,MBNK,momentum,64,0.027175,0.032376,-0.039956,-0.334164,-0.254167,0.406250,week,5,limited_history,True,184,190,6,190,1260,2024-09-05,2025-05-15,8,False
20,validation,SBER,momentum,126,0.027809,0.039988,-0.045619,-0.168581,-0.124199,0.547619,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,1,True
19,validation,SBER,lstm,126,0.028419,0.040303,-0.062120,-0.032598,0.024960,0.515873,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,2,False
21,validation,SBER,naive_persistence,126,0.030932,0.042476,-0.179756,0.070894,0.023874,0.500000,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,3,False
22,validation,SBER,ridge,126,0.031266,0.043669,-0.246924,-0.067074,-0.031823,0.476190,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,4,False
18,validation,SBER,lightgbm,126,0.031586,0.043805,-0.254751,-0.129377,-0.067982,0.460317,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,5,False
17,validation,SBER,hist_gradient_boosting,126,0.038939,0.053802,-0.892803,-0.184584,-0.238120,0.436508,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,6,False
16,validation,SBER,catboost,126,0.032469,0.044907,-0.318632,-0.144170,-0.173093,0.404762,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,7,False
23,validation,SBER,xgboost,126,0.027980,0.039929,-0.042492,NaN,NaN,0.396825,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,8,False
26,validation,SBERP,lightgbm,126,0.026205,0.037377,-0.038405,0.010505,0.011066,0.579365,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,1,True
28,validation,SBERP,momentum,126,0.026043,0.037530,-0.046916,-0.164610,-0.114235,0.555556,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,2,False
27,validation,SBERP,lstm,126,0.034334,0.047882,-0.704068,0.120428,0.151940,0.500000,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,3,False
29,validation,SBERP,naive_persistence,126,0.029373,0.040241,-0.203589,0.066009,0.007076,0.468254,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,4,False
30,validation,SBERP,ridge,126,0.045464,0.060966,-1.762610,-0.034272,0.046215,0.460317,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,5,False
25,validation,SBERP,hist_gradient_boosting,126,0.044821,0.061060,-1.771186,-0.180846,-0.170692,0.452381,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,6,False
31,validation,SBERP,xgboost,126,0.027257,0.038380,-0.094845,-0.130612,-0.155186,0.428571,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,7,False
24,validation,SBERP,catboost,126,0.033189,0.047374,-0.668094,-0.041296,-0.093609,0.404762,week,5,mature,False,1254,1260,6,4158,1260,2019-12-02,2024-12-09,8,False
37,validation,SVCB,naive_persistence,83,0.034945,0.043822,-0.198469,0.012300,0.005080,0.530120,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,1,True
33,validation,SVCB,hist_gradient_boosting,83,0.039416,0.046900,-0.372750,0.211927,0.190854,0.506024,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,2,False
32,validation,SVCB,catboost,83,0.034641,0.041575,-0.078742,0.130116,0.101969,0.493976,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,3,False
35,validation,SVCB,lstm,83,0.042029,0.050334,-0.581120,0.130747,0.230637,0.469880,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,4,False
39,validation,SVCB,xgboost,83,0.031829,0.040052,-0.001132,NaN,NaN,0.457831,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,5,False
34,validation,SVCB,lightgbm,83,0.031829,0.040052,-0.001132,NaN,NaN,0.457831,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,6,False
36,validation,SVCB,momentum,83,0.033662,0.042043,-0.103136,-0.148792,-0.198564,0.433735,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,7,False
38,validation,SVCB,ridge,83,0.055330,0.068686,-1.944326,0.020817,0.011985,0.433735,week,5,limited_history,True,245,251,6,251,1260,2024-04-27,2025-04-03,8,False
47,validation,T,xgboost,126,0.040494,0.054616,-0.022131,NaN,NaN,0.666667,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,1,True
40,validation,T,catboost,126,0.040835,0.054026,-0.000135,0.233660,0.204445,0.587302,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,2,False
45,validation,T,naive_persistence,126,0.045598,0.059884,-0.228783,-0.008171,-0.000771,0.515873,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,3,False
42,validation,T,lightgbm,126,0.042863,0.056061,-0.076896,0.165772,0.124973,0.507937,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,4,False
44,validation,T,momentum,126,0.045715,0.059992,-0.233237,-0.007885,-0.052952,0.507937,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,5,False
43,validation,T,lstm,126,0.044666,0.058931,-0.190015,0.015704,0.016627,0.476190,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,6,False
41,validation,T,hist_gradient_boosting,126,0.048508,0.061741,-0.306192,0.144680,0.082427,0.460317,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,7,False
46,validation,T,ridge,126,0.053160,0.067437,-0.558330,-0.039415,-0.040918,0.428571,week,5,mature,False,1162,1168,6,1168,1260,2020-03-13,2024-12-05,8,False
51,validation,VTBR,lstm,126,0.047678,0.065448,-0.100276,0.072973,0.091876,0.515873,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,1,True
53,validation,VTBR,naive_persistence,126,0.050889,0.068006,-0.187993,0.048660,0.093267,0.515873,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,2,False
49,validation,VTBR,hist_gradient_boosting,126,0.047585,0.064475,-0.067833,0.189511,0.154225,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,3,False
50,validation,VTBR,lightgbm,126,0.047593,0.064500,-0.068654,NaN,NaN,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,4,False
55,validation,VTBR,xgboost,126,0.047593,0.064501,-0.068673,NaN,NaN,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,5,False
48,validation,VTBR,catboost,126,0.047631,0.064524,-0.069438,-0.147967,-0.217098,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,6,False
54,validation,VTBR,ridge,126,0.047811,0.064616,-0.072497,-0.025602,-0.111739,0.484127,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,7,False
52,validation,VTBR,momentum,126,0.048376,0.064419,-0.065961,-0.441041,-0.519802,0.269841,week,5,mature,False,1254,1260,6,4114,1260,2019-11-26,2024-12-09,8,False

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,catboost,126,0.035405,0.045339,-0.177474,0.158048,0.165612,0.444444,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,8,False,0.412698
1,test,CBOM,hist_gradient_boosting,126,0.037630,0.047119,-0.271767,0.086560,0.108110,0.500000,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,6,False,0.436508
2,test,CBOM,lightgbm,126,0.034566,0.043893,-0.103584,0.095166,0.137590,0.515873,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,5,False,0.452381
3,test,CBOM,lstm,126,0.032930,0.042199,-0.020033,0.044701,0.079877,0.539683,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,4,False,0.460317
4,test,CBOM,momentum,126,0.033353,0.042393,-0.029406,-0.104179,-0.196658,0.444444,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,1,True,0.603175
5,test,CBOM,naive_persistence,126,0.035463,0.047183,-0.275220,-0.074744,-0.038584,0.500000,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,3,False,0.500000
6,test,CBOM,ridge,126,0.032458,0.042025,-0.011617,0.180101,0.217746,0.595238,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,2,False,0.523810
7,test,CBOM,xgboost,126,0.032805,0.041804,-0.001034,NaN,NaN,0.507937,week,5,mature,False,1254,1260,6,2413,1260,2020-06-05,2025-05-17,7,False,0.420635
8,test,MBNK,catboost,64,0.027269,0.036585,0.103646,0.565771,0.588233,0.625000,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,6,False,0.484375
9,test,MBNK,hist_gradient_boosting,64,0.033447,0.041720,-0.165614,-0.183538,-0.163051,0.437500,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,7,False,0.484375
10,test,MBNK,lightgbm,64,0.029140,0.038651,-0.000412,NaN,NaN,0.625000,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,5,False,0.484375
11,test,MBNK,lstm,64,0.027314,0.039385,-0.038791,0.387282,0.447253,0.625000,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,1,True,0.656250
12,test,MBNK,momentum,64,0.028585,0.037068,0.079841,0.464626,0.458608,0.765625,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,8,False,0.406250
13,test,MBNK,naive_persistence,64,0.033019,0.040941,-0.122506,0.094607,0.108562,0.546875,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,3,False,0.546875
14,test,MBNK,ridge,64,0.129126,0.149213,-13.910142,-0.286436,-0.334432,0.531250,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,2,False,0.640625
15,test,MBNK,xgboost,64,0.029163,0.038646,-0.000172,NaN,NaN,0.625000,week,5,limited_history,True,248,254,6,254,1260,2024-09-05,2025-07-23,4,False,0.484375
16,test,SBER,catboost,126,0.016372,0.020207,-0.183680,-0.061892,-0.048831,0.452381,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,7,False,0.404762
17,test,SBER,hist_gradient_boosting,126,0.016726,0.020562,-0.225744,-0.037631,-0.054738,0.420635,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,6,False,0.436508
18,test,SBER,lightgbm,126,0.016081,0.019588,-0.112372,0.079393,0.219986,0.412698,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,5,False,0.460317
19,test,SBER,lstm,126,0.016785,0.020871,-0.262785,-0.107531,-0.158221,0.484127,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,2,False,0.515873
20,test,SBER,momentum,126,0.015153,0.018714,-0.015273,0.048738,0.055838,0.500000,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,1,True,0.547619
21,test,SBER,naive_persistence,126,0.017608,0.022441,-0.459986,-0.109419,-0.111559,0.492063,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,3,False,0.500000
22,test,SBER,ridge,126,0.017111,0.021165,-0.298572,-0.078742,-0.050625,0.523810,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,4,False,0.476190
23,test,SBER,xgboost,126,0.015424,0.018962,-0.042349,NaN,NaN,0.420635,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,8,False,0.396825
24,test,SBERP,catboost,126,0.018297,0.023118,-0.557861,-0.215403,-0.213348,0.428571,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,8,False,0.404762
25,test,SBERP,hist_gradient_boosting,126,0.017327,0.021357,-0.329561,-0.072210,-0.050928,0.515873,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,6,False,0.452381
26,test,SBERP,lightgbm,126,0.015738,0.019051,-0.057905,NaN,NaN,0.428571,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,1,True,0.579365
27,test,SBERP,lstm,126,0.018960,0.023584,-0.621203,-0.069474,-0.081893,0.476190,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,3,False,0.500000
28,test,SBERP,momentum,126,0.015328,0.018665,-0.015502,0.006049,0.011114,0.444444,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,2,False,0.555556
29,test,SBERP,naive_persistence,126,0.017389,0.021838,-0.390132,-0.082912,-0.104312,0.460317,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,4,False,0.468254
30,test,SBERP,ridge,126,0.022025,0.028819,-1.420836,-0.128209,-0.114709,0.523810,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,5,False,0.460317
31,test,SBERP,xgboost,126,0.015657,0.018977,-0.049663,0.037588,0.032214,0.428571,week,5,mature,False,1254,1260,6,4284,1260,2020-06-05,2025-05-17,7,False,0.428571
32,test,SVCB,catboost,83,0.037849,0.046596,-0.439113,0.099414,0.101192,0.578313,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,3,False,0.493976
33,test,SVCB,hist_gradient_boosting,83,0.042731,0.049974,-0.655368,-0.067818,-0.185332,0.361446,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,2,False,0.506024
34,test,SVCB,lightgbm,83,0.031158,0.040797,-0.103211,NaN,NaN,0.722892,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,6,False,0.457831
35,test,SVCB,lstm,83,0.028785,0.038361,0.024605,0.205835,0.122455,0.698795,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,4,False,0.469880
36,test,SVCB,momentum,83,0.031479,0.041487,-0.140854,-0.009206,-0.007787,0.590361,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,7,False,0.433735
37,test,SVCB,naive_persistence,83,0.033845,0.044182,-0.293877,0.008596,0.016015,0.566265,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,1,True,0.530120
38,test,SVCB,ridge,83,0.066014,0.073114,-2.543266,-0.002353,0.030330,0.373494,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,8,False,0.433735
39,test,SVCB,xgboost,83,0.031158,0.040797,-0.103211,NaN,NaN,0.722892,week,5,limited_history,True,328,334,6,334,1260,2024-04-27,2025-07-04,5,False,0.457831
40,test,T,catboost,126,0.024971,0.032278,-0.393143,-0.062429,-0.060391,0.587302,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,2,False,0.587302
41,test,T,hist_gradient_boosting,126,0.030010,0.038294,-0.960866,0.040921,-0.000255,0.571429,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,7,False,0.460317
42,test,T,lightgbm,126,0.025172,0.032551,-0.416807,-0.088388,-0.084472,0.563492,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,4,False,0.507937
43,test,T,lstm,126,0.022514,0.028851,-0.113026,0.035315,0.064411,0.603175,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,6,False,0.476190
44,test,T,momentum,126,0.024882,0.031063,-0.290288,-0.075195,-0.059906,0.436508,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,5,False,0.507937
45,test,T,naive_persistence,126,0.023963,0.030031,-0.205958,0.001774,0.048495,0.547619,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,3,False,0.515873
46,test,T,ridge,126,0.030651,0.038991,-1.032920,-0.061531,-0.022992,0.460317,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,8,False,0.428571
47,test,T,xgboost,126,0.022943,0.028164,-0.060693,NaN,NaN,0.420635,week,5,mature,False,1254,1260,6,1294,1260,2020-04-30,2025-05-15,1,True,0.666667
48,test,VTBR,catboost,126,0.040978,0.068710,-0.025774,-0.120745,-0.025650,0.587302,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,6,False,0.484127
49,test,VTBR,hist_gradient_boosting,126,0.040910,0.068849,-0.029955,0.047394,-0.064996,0.626984,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,3,False,0.484127
50,test,VTBR,lightgbm,126,0.040983,0.068694,-0.025307,NaN,NaN,0.587302,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,4,False,0.484127
51,test,VTBR,lstm,126,0.041385,0.069702,-0.055636,0.020533,0.059114,0.563492,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,1,True,0.515873
52,test,VTBR,momentum,126,0.041188,0.069146,-0.038842,-0.047587,-0.099825,0.571429,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,8,False,0.269841
53,test,VTBR,naive_persistence,126,0.044167,0.074690,-0.212104,-0.031998,0.055436,0.507937,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,2,False,0.515873
54,test,VTBR,ridge,126,0.040992,0.068773,-0.027659,-0.023955,0.026982,0.587302,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,7,False,0.484127
55,test,VTBR,xgboost,126,0.040982,0.068694,-0.025306,NaN,NaN,0.587302,week,5,mature,False,1254,1260,6,4240,1260,2020-06-01,2025-05-17,5,False,0.484127

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=6216
2,test predictions are available,True,rows=6216
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

=== Merged LSTM into main strict reports: month ===

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,validation_directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_train_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected
6,validation,CBOM,ridge,126,0.183240,0.222773,-1.369922,0.477989,0.525369,0.714286,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,1,True
4,validation,CBOM,momentum,126,0.119886,0.145216,-0.007018,0.380199,0.360192,0.674603,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,2,False
7,validation,CBOM,xgboost,126,0.118405,0.148334,-0.050734,-0.585570,-0.444415,0.619048,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,3,False
1,validation,CBOM,hist_gradient_boosting,126,0.120147,0.149107,-0.061706,-0.573815,-0.495051,0.619048,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,4,False
2,validation,CBOM,lightgbm,126,0.121789,0.149149,-0.062307,-0.537117,-0.469035,0.619048,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,5,False
5,validation,CBOM,naive_persistence,126,0.121137,0.145796,-0.015083,0.113085,0.113995,0.563492,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,6,False
3,validation,CBOM,lstm,126,0.112675,0.140781,0.053557,0.265516,0.378274,0.484127,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,7,False
0,validation,CBOM,catboost,126,0.127382,0.155058,-0.148142,-0.262248,-0.323231,0.428571,month,21,mature,False,1238,1260,22,2271,1260,2019-11-08,2024-10-24,8,False
9,validation,MBNK,hist_gradient_boosting,60,0.048051,0.063459,-0.634216,NaN,NaN,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,1,True
14,validation,MBNK,ridge,60,0.048415,0.063871,-0.655535,-0.121510,-0.160711,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,2,False
15,validation,MBNK,xgboost,60,0.049479,0.064837,-0.705989,NaN,NaN,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,3,False
10,validation,MBNK,lightgbm,60,0.048884,0.065537,-0.743013,0.031892,0.217116,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,4,False
8,validation,MBNK,catboost,60,0.056705,0.071597,-1.080241,0.007056,0.004390,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,5,False
11,validation,MBNK,lstm,60,0.100523,0.132065,-6.077864,-0.413370,-0.396388,0.516667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,6,False
13,validation,MBNK,naive_persistence,60,0.041470,0.052807,-0.131638,-0.060240,-0.013504,0.466667,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,7,False
12,validation,MBNK,momentum,60,0.039279,0.050680,-0.042329,-0.547339,-0.607113,0.350000,month,21,limited_history,True,160,182,22,182,1260,2024-09-05,2025-04-17,8,False
23,validation,SBER,xgboost,126,0.070686,0.091032,-0.246274,0.045223,0.174429,0.674603,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,1,True
18,validation,SBER,lightgbm,126,0.070912,0.090390,-0.228758,0.063181,0.087967,0.650794,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,2,False
20,validation,SBER,momentum,126,0.071385,0.093202,-0.306422,-0.617897,-0.497113,0.587302,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,3,False
21,validation,SBER,naive_persistence,126,0.073334,0.094695,-0.348590,-0.058763,-0.056564,0.500000,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,4,False
19,validation,SBER,lstm,126,0.078237,0.100344,-0.514296,-0.134038,-0.124559,0.452381,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,5,False
16,validation,SBER,catboost,126,0.077314,0.096541,-0.401697,-0.079571,-0.154148,0.436508,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,6,False
17,validation,SBER,hist_gradient_boosting,126,0.084910,0.103799,-0.620371,-0.039137,-0.348325,0.365079,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,7,False
22,validation,SBER,ridge,126,0.106093,0.126527,-1.407649,-0.043844,-0.116322,0.325397,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,8,False
28,validation,SBERP,momentum,126,0.067932,0.090109,-0.308032,-0.617028,-0.488336,0.587302,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,1,True
27,validation,SBERP,lstm,126,0.071503,0.097143,-0.520221,-0.057074,0.009392,0.563492,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,2,False
29,validation,SBERP,naive_persistence,126,0.070104,0.091572,-0.350851,-0.056267,-0.061237,0.507937,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,3,False
31,validation,SBERP,xgboost,126,0.079303,0.095169,-0.459073,0.132893,0.221867,0.492063,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,4,False
25,validation,SBERP,hist_gradient_boosting,126,0.070498,0.090596,-0.322210,-0.006596,-0.090782,0.452381,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,5,False
30,validation,SBERP,ridge,126,0.087977,0.110537,-0.968344,-0.141481,-0.091990,0.396825,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,6,False
26,validation,SBERP,lightgbm,126,0.092537,0.116213,-1.175691,-0.205689,-0.069295,0.396825,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,7,False
24,validation,SBERP,catboost,126,0.069306,0.090194,-0.310509,-0.020509,-0.059918,0.373016,month,21,mature,False,1238,1260,22,4142,1260,2019-11-08,2024-10-24,8,False
32,validation,SVCB,catboost,80,0.049196,0.058185,-0.404646,0.168544,0.071613,0.537500,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,1,True
34,validation,SVCB,lightgbm,80,0.040728,0.049342,-0.010144,NaN,NaN,0.475000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,2,False
39,validation,SVCB,xgboost,80,0.041635,0.049958,-0.035510,-0.084479,-0.169505,0.475000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,3,False
37,validation,SVCB,naive_persistence,80,0.046077,0.057084,-0.352023,-0.183871,-0.146953,0.475000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,4,False
33,validation,SVCB,hist_gradient_boosting,80,0.062448,0.074267,-1.288427,0.474920,0.475902,0.475000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,5,False
38,validation,SVCB,ridge,80,0.115187,0.130691,-6.086707,0.017648,0.063971,0.450000,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,6,False
35,validation,SVCB,lstm,80,0.062049,0.075518,-1.366177,-0.233437,-0.225809,0.412500,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,7,False
36,validation,SVCB,momentum,80,0.042513,0.051191,-0.087274,-0.290474,-0.278504,0.362500,month,21,limited_history,True,219,241,22,241,1260,2024-04-27,2025-03-04,8,False
42,validation,T,lightgbm,126,0.081024,0.101506,0.066207,0.429886,0.358647,0.658730,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,1,True
47,validation,T,xgboost,126,0.078313,0.094307,0.193975,0.527946,0.429830,0.634921,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,2,False
40,validation,T,catboost,126,0.090946,0.114076,-0.179369,0.296904,0.246020,0.571429,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,3,False
44,validation,T,momentum,126,0.092551,0.115004,-0.198633,-0.448398,-0.377644,0.547619,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,4,False
45,validation,T,naive_persistence,126,0.095111,0.117665,-0.254743,-0.034656,-0.029651,0.484127,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,5,False
41,validation,T,hist_gradient_boosting,126,0.093159,0.115555,-0.210145,0.272293,0.104840,0.468254,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,6,False
43,validation,T,lstm,126,0.137494,0.173093,-1.715325,-0.304818,-0.289947,0.412698,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,7,False
46,validation,T,ridge,126,0.248903,0.301147,-7.219024,-0.255856,-0.363732,0.396825,month,21,mature,False,1130,1152,22,1152,1260,2020-03-13,2024-10-22,8,False
53,validation,VTBR,naive_persistence,126,0.125237,0.152290,-0.219958,-0.021048,0.009584,0.563492,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,1,True
51,validation,VTBR,lstm,126,0.127768,0.157085,-0.297985,-0.361763,-0.435315,0.404762,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,2,False
49,validation,VTBR,hist_gradient_boosting,126,0.127975,0.155414,-0.270529,0.680213,0.674624,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,3,False
55,validation,VTBR,xgboost,126,0.129935,0.157269,-0.301036,NaN,NaN,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,4,False
50,validation,VTBR,lightgbm,126,0.130328,0.157712,-0.308378,NaN,NaN,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,5,False
48,validation,VTBR,catboost,126,0.130637,0.158209,-0.316628,-0.636408,-0.633752,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,6,False
54,validation,VTBR,ridge,126,0.130572,0.158500,-0.321480,-0.379559,-0.461915,0.325397,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,7,False
52,validation,VTBR,momentum,126,0.125417,0.152021,-0.215659,-0.788769,-0.807856,0.230159,month,21,mature,False,1238,1260,22,4098,1260,2019-11-01,2024-10-24,8,False

,split_role,ticker,model_name,n_obs,mae,rmse,r2,pearson,spearman,directional_accuracy,horizon_name,horizon,split_quality,limited_history,n_train,n_train_before_purge,n_train_purged,n_refit_available,max_train_rows,train_start,train_end,validation_rank,is_validation_selected,validation_directional_accuracy
0,test,CBOM,catboost,126,0.081123,0.097541,0.045514,0.278584,0.291801,0.650794,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,8,False,0.428571
1,test,CBOM,hist_gradient_boosting,126,0.087954,0.099400,0.008791,0.122738,0.184148,0.444444,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,4,False,0.619048
2,test,CBOM,lightgbm,126,0.085770,0.099409,0.008607,0.126055,0.130726,0.634921,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,5,False,0.619048
3,test,CBOM,lstm,126,0.083184,0.104529,-0.096135,0.006361,-0.099531,0.539683,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,7,False,0.484127
4,test,CBOM,momentum,126,0.088952,0.100350,-0.010248,-0.109474,-0.080993,0.230159,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,2,False,0.674603
5,test,CBOM,naive_persistence,126,0.086153,0.100820,-0.019735,0.059501,0.029639,0.531746,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,6,False,0.563492
6,test,CBOM,ridge,126,0.083977,0.104455,-0.094590,0.295857,0.288057,0.619048,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,1,True,0.714286
7,test,CBOM,xgboost,126,0.085955,0.098517,0.026311,0.203773,0.405381,0.761905,month,21,mature,False,1238,1260,22,2397,1260,2020-05-14,2025-04-11,3,False,0.619048
8,test,MBNK,catboost,60,0.086232,0.099695,-0.006644,0.611376,0.607669,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,5,False,0.516667
9,test,MBNK,hist_gradient_boosting,60,0.093132,0.112907,-0.291115,0.692720,0.669023,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,1,True,0.516667
10,test,MBNK,lightgbm,60,0.089818,0.102366,-0.061292,NaN,NaN,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,4,False,0.516667
11,test,MBNK,lstm,60,0.086591,0.117168,-0.390413,0.549681,0.553154,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,6,False,0.516667
12,test,MBNK,momentum,60,0.090073,0.099464,-0.001979,0.326823,0.337983,0.650000,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,8,False,0.350000
13,test,MBNK,naive_persistence,60,0.090140,0.099190,0.003546,0.148747,0.188108,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,7,False,0.466667
14,test,MBNK,ridge,60,0.088560,0.100420,-0.021329,0.735418,0.731703,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,2,False,0.516667
15,test,MBNK,xgboost,60,0.089739,0.101507,-0.043557,NaN,NaN,0.533333,month,21,limited_history,True,220,242,22,242,1260,2024-09-05,2025-06-25,3,False,0.516667
16,test,SBER,catboost,126,0.032716,0.043991,-0.840044,-0.375818,-0.406320,0.436508,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,6,False,0.436508
17,test,SBER,hist_gradient_boosting,126,0.032145,0.043101,-0.766346,-0.322505,-0.302903,0.380952,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,7,False,0.365079
18,test,SBER,lightgbm,126,0.031838,0.042016,-0.678545,-0.100167,-0.129104,0.436508,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,2,False,0.650794
19,test,SBER,lstm,126,0.042874,0.058081,-2.207627,-0.411589,-0.360498,0.404762,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,5,False,0.452381
20,test,SBER,momentum,126,0.026862,0.033841,-0.088906,0.121294,0.104594,0.468254,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,3,False,0.587302
21,test,SBER,naive_persistence,126,0.028016,0.035573,-0.203240,-0.025953,-0.021822,0.515873,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,4,False,0.500000
22,test,SBER,ridge,126,0.041409,0.052413,-1.612061,-0.542822,-0.472504,0.317460,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,8,False,0.325397
23,test,SBER,xgboost,126,0.029667,0.039133,-0.456110,-0.109751,-0.122691,0.436508,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,1,True,0.674603
24,test,SBERP,catboost,126,0.028961,0.037834,-0.385962,-0.537652,-0.550698,0.444444,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,8,False,0.373016
25,test,SBERP,hist_gradient_boosting,126,0.027167,0.036136,-0.264366,0.025891,0.058368,0.547619,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,5,False,0.452381
26,test,SBERP,lightgbm,126,0.032844,0.042219,-0.725804,-0.100698,-0.046047,0.492063,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,7,False,0.396825
27,test,SBERP,lstm,126,0.047963,0.061628,-2.677400,-0.587746,-0.592585,0.396825,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,2,False,0.563492
28,test,SBERP,momentum,126,0.026347,0.033303,-0.073888,0.073826,0.063091,0.460317,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,1,True,0.587302
29,test,SBERP,naive_persistence,126,0.027744,0.034818,-0.173762,-0.018249,-0.034871,0.507937,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,3,False,0.507937
30,test,SBERP,ridge,126,0.036753,0.046715,-1.112961,-0.517035,-0.529299,0.293651,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,6,False,0.396825
31,test,SBERP,xgboost,126,0.029714,0.038812,-0.458555,-0.192972,-0.190608,0.444444,month,21,mature,False,1238,1260,22,4268,1260,2020-05-14,2025-04-11,4,False,0.492063
32,test,SVCB,catboost,80,0.080655,0.091611,-0.311304,0.068007,-0.002039,0.675000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,1,True,0.537500
33,test,SVCB,hist_gradient_boosting,80,0.081612,0.093901,-0.377678,0.150758,0.073605,0.650000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,5,False,0.475000
34,test,SVCB,lightgbm,80,0.085220,0.095473,-0.424206,NaN,NaN,0.750000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,2,False,0.475000
35,test,SVCB,lstm,80,0.082769,0.097270,-0.478333,-0.114033,-0.237084,0.575000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,7,False,0.412500
36,test,SVCB,momentum,80,0.090264,0.101868,-0.621370,0.192280,0.198125,0.712500,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,8,False,0.362500
37,test,SVCB,naive_persistence,80,0.088765,0.101648,-0.614375,0.106442,0.093601,0.575000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,4,False,0.475000
38,test,SVCB,ridge,80,0.175367,0.200214,-5.263246,-0.081648,-0.039475,0.275000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,6,False,0.450000
39,test,SVCB,xgboost,80,0.085373,0.096046,-0.441335,0.013120,0.010378,0.750000,month,21,limited_history,True,299,321,22,321,1260,2024-04-27,2025-06-02,3,False,0.475000
40,test,T,catboost,126,0.053665,0.064726,-1.169029,0.162653,0.178181,0.555556,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,3,False,0.571429
41,test,T,hist_gradient_boosting,126,0.059888,0.072889,-1.750643,0.071071,0.051651,0.571429,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,6,False,0.468254
42,test,T,lightgbm,126,0.043574,0.051598,-0.378378,0.346850,0.317302,0.571429,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,1,True,0.658730
43,test,T,lstm,126,0.052956,0.060317,-0.883572,0.076077,0.099957,0.476190,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,7,False,0.412698
44,test,T,momentum,126,0.034712,0.044426,-0.021818,-0.373278,-0.421738,0.357143,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,4,False,0.547619
45,test,T,naive_persistence,126,0.036556,0.045987,-0.094901,-0.005215,-0.052094,0.444444,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,5,False,0.484127
46,test,T,ridge,126,0.062094,0.079948,-2.309153,0.523435,0.418049,0.619048,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,8,False,0.396825
47,test,T,xgboost,126,0.036056,0.042651,0.058169,0.314870,0.222635,0.579365,month,21,mature,False,1238,1260,22,1278,1260,2020-04-08,2025-04-09,2,False,0.634921
48,test,VTBR,catboost,126,0.086263,0.117670,-0.193583,-0.073635,-0.243561,0.753968,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,6,False,0.325397
49,test,VTBR,hist_gradient_boosting,126,0.089547,0.120046,-0.242278,0.003297,-0.105883,0.619048,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,3,False,0.325397
50,test,VTBR,lightgbm,126,0.086025,0.117505,-0.190238,NaN,NaN,0.753968,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,5,False,0.325397
51,test,VTBR,lstm,126,0.092710,0.121403,-0.270523,0.424351,0.483879,0.531746,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,2,False,0.404762
52,test,VTBR,momentum,126,0.090487,0.122833,-0.300628,-0.225935,-0.051201,0.642857,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,8,False,0.230159
53,test,VTBR,naive_persistence,126,0.093762,0.126968,-0.389670,-0.111032,-0.052919,0.484127,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,1,True,0.563492
54,test,VTBR,ridge,126,0.086499,0.117972,-0.199717,-0.185563,-0.327292,0.753968,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,7,False,0.325397
55,test,VTBR,xgboost,126,0.087311,0.118642,-0.213385,-0.131789,-0.179564,0.753968,month,21,mature,False,1238,1260,22,4224,1260,2020-05-07,2025-04-11,4,False,0.325397

,check,passed,details
0,strict outer splits are available,True,split_rows=7
1,validation predictions are available,True,rows=6160
2,test predictions are available,True,rows=6160
3,outer split dates are chronological,True,bad_rows=0
4,train and refit windows respect max_train_rows,True,"train_over_cap=0, refit_over_cap=0"
5,validation predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match outer split dates,True,"out_of_window=0, wrong_role=0"
7,final refit target dates end before test starts,True,overlap_rows=0
8,final model payloads exist for test predictions,True,missing_models=0

## Next Step

Run `03_model_comparison.ipynb` after this notebook. If merge is enabled, it will load the main strict reports and include LSTM together with the previously trained table models.