# 02c Global LSTM Strict Forecasting

Train one pooled/global LSTM across all available ticker series with calendar-global purging and profit/risk validation selection.

In [1]:
from pathlib import Path
import os
import sys

cwd = Path.cwd().resolve()
for candidate in [cwd, cwd / "forecasting", cwd.parent, cwd.parent / "forecasting"]:
    if (candidate / "src" / "stock_forecast").exists():
        PROJECT_DIR = candidate
        break
else:
    raise RuntimeError("Cannot locate forecasting project directory with src/stock_forecast")

SRC_DIR = PROJECT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

ARTIFACT_DIR = PROJECT_DIR / "artifacts"
DATA_DIR = ARTIFACT_DIR / "data"
REPORTS_DIR = ARTIFACT_DIR / "reports"
GLOBAL_LSTM_DATA_DIR = DATA_DIR / "global_lstm"
GLOBAL_LSTM_OUTPUT_DIR = Path(os.environ.get("GLOBAL_LSTM_OUTPUT_DIR", ARTIFACT_DIR / "horizons")).expanduser().resolve()
for path in [DATA_DIR, REPORTS_DIR]:
    path.mkdir(parents=True, exist_ok=True)


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(PROJECT_DIR))
    except ValueError:
        return str(path)


print(f"PROJECT_DIR = {PROJECT_DIR}")

PROJECT_DIR = /home/sapce/forecasting_stock_prices/forecasting

In [2]:
import importlib.util
import pandas as pd
from IPython.display import display

from stock_forecast.artifacts import load_json, load_table
from stock_forecast.mlflow_tracking import MLflowRunConfig, log_strict_protocol_result, mlflow_horizon_run
from stock_forecast.models import build_model
from stock_forecast.strict_protocol import run_strict_global_lstm_protocol

pd.set_option("display.max_columns", 200)

## Constants

In [3]:
if importlib.util.find_spec("torch") is None:
    raise ImportError("PyTorch is required for this notebook. Install/use the torchlab environment.")

def env_int(name: str, default: int) -> int:
    return int(os.environ.get(name, default))


def env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y"}


def env_int_list(name: str, default: list[int]) -> list[int]:
    value = os.environ.get(name)
    if not value:
        return default
    return [int(item.strip()) for item in value.split(",") if item.strip()]


FORCE_RETRAIN = env_bool("GLOBAL_LSTM_FORCE_RETRAIN", True)
RANDOM_STATE = env_int("GLOBAL_LSTM_RANDOM_STATE", 42)

STRICT_VALIDATION_ROWS = env_int("STRICT_VALIDATION_ROWS", 126)
STRICT_TEST_ROWS = env_int("STRICT_TEST_ROWS", 126)
MATURE_MIN_ROWS = env_int("MATURE_MIN_ROWS", 1008)
LIMITED_HISTORY_MIN_BLOCK_ROWS = env_int("LIMITED_HISTORY_MIN_BLOCK_ROWS", 42)
MIN_TRAIN_ROWS = env_int("MIN_TRAIN_ROWS", 60)
STRICT_MAX_TRAIN_ROWS = env_int("STRICT_MAX_TRAIN_ROWS", 1260)
INNER_MAX_FOLDS = env_int("INNER_MAX_FOLDS", 3)
INNER_MIN_TRAIN_ROWS = env_int("INNER_MIN_TRAIN_ROWS", 504)

GLOBAL_LSTM_N_TRIALS = env_int("GLOBAL_LSTM_N_TRIALS", 30)
GLOBAL_LSTM_OPTUNA_N_JOBS = env_int("GLOBAL_LSTM_OPTUNA_N_JOBS", 1)
GLOBAL_LSTM_MAX_EPOCHS = env_int("GLOBAL_LSTM_MAX_EPOCHS", 120)
GLOBAL_LSTM_PATIENCE = env_int("GLOBAL_LSTM_PATIENCE", 12)
GLOBAL_LSTM_DEVICE = os.environ.get("GLOBAL_LSTM_DEVICE", "auto")
GLOBAL_LSTM_ENSEMBLE_SEEDS = env_int_list("GLOBAL_LSTM_ENSEMBLE_SEEDS", [1, 7, 21])

TRANSACTION_COST_BPS = 10
SLIPPAGE_BPS = 5
SIGNAL_ANCHOR = "expanding_median"
MIN_VALIDATION_TRADES = 8
MAX_VALIDATION_DRAWDOWN = -0.35

MLFLOW_ENABLED = env_bool("MLFLOW_ENABLED", True)
MLFLOW_TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI", "http://localhost:5000")
MLFLOW_EXPERIMENT_NAME = os.environ.get("MLFLOW_EXPERIMENT_NAME", "stock_return_forecasting_research")
MLFLOW_LOG_OPTUNA_TRIALS = env_bool("MLFLOW_LOG_OPTUNA_TRIALS", True)

HORIZONS = [
    {"name": "week", "horizon": 5, "threshold_grid": [0.0, 0.0025, 0.005, 0.01]},
    {"name": "month", "horizon": 21, "threshold_grid": [0.0, 0.005, 0.01, 0.02]},
]
selected_horizons = {name.strip() for name in os.environ.get("GLOBAL_LSTM_HORIZONS", "").split(",") if name.strip()}
if selected_horizons:
    HORIZONS = [item for item in HORIZONS if item["name"] in selected_horizons]

## Model Config

In [4]:
def make_global_lstm_search_space(horizon: int) -> dict:
    huber_beta_choices = [0.04, 0.08, 0.12] if horizon >= 21 else [0.02, 0.04, 0.06]
    return {
        "lookback": {"type": "categorical", "choices": [40, 60, 90, 126]},
        "hidden_size": {"type": "categorical", "choices": [32, 64, 96, 128]},
        "num_layers": {"type": "categorical", "choices": [1, 2]},
        "input_projection_size": {"type": "categorical", "choices": [0, 64, 128]},
        "lstm_dropout": {"type": "float", "low": 0.0, "high": 0.35},
        "head_dropout": {"type": "float", "low": 0.10, "high": 0.50},
        "learning_rate": {"type": "float", "low": 1e-4, "high": 2e-3, "log": True},
        "weight_decay": {"type": "float", "low": 1e-5, "high": 1e-2, "log": True},
        "batch_size": {"type": "categorical", "choices": [64, 128, 256]},
        "loss": {"type": "categorical", "choices": ["smooth_l1", "huber", "mse"]},
        "huber_beta": {"type": "categorical", "choices": huber_beta_choices},
        "feature_clip": {"type": "categorical", "choices": [3.0, 5.0, 8.0]},
        "target_normalization": {"type": "categorical", "choices": ["global", "per_ticker"]},
        "balanced_ticker_sampling": {"type": "categorical", "choices": [True]},
        "grad_clip_norm": {"type": "float", "low": 0.5, "high": 2.0},
    }


def make_global_lstm_config(name: str, feature_cols: list[str], horizon: int) -> dict:
    return {
        "name": name,
        "model_type": "lstm",
        "estimator_factory": build_model,
        "input_mode": "full_frame",
        "feature_cols": feature_cols,
        "static_params": {
            "max_epochs": GLOBAL_LSTM_MAX_EPOCHS,
            "patience": GLOBAL_LSTM_PATIENCE,
            "device": GLOBAL_LSTM_DEVICE,
            "validation_fraction": 0.2,
        },
        "search_space": make_global_lstm_search_space(horizon),
        "post_selection_static_params": {"ensemble_seeds": GLOBAL_LSTM_ENSEMBLE_SEEDS},
        "n_trials": GLOBAL_LSTM_N_TRIALS,
        "optuna_n_jobs": GLOBAL_LSTM_OPTUNA_N_JOBS,
        "needs_scaler": False,
    }

## Load Global LSTM Data

In [5]:
horizon_inputs = []

for spec in HORIZONS:
    horizon_name = spec["name"]
    horizon = int(spec["horizon"])
    global_dir = GLOBAL_LSTM_DATA_DIR / "horizons" / horizon_name
    model_path = global_dir / "model_dataset.parquet"
    feature_path = global_dir / "feature_columns.json"
    if not model_path.exists() and not model_path.with_suffix(".csv").exists():
        raise FileNotFoundError(f"Missing global LSTM data for {horizon_name}. Run notebooks/01c_global_lstm_eda.ipynb first.")
    payload = load_json(feature_path)
    model_df = load_table(model_path)
    model_df["date"] = pd.to_datetime(model_df["date"])
    feature_sets = payload["global_feature_sets"]
    model_configs = [
        make_global_lstm_config("global_lstm_all", feature_sets["global_all"], horizon),
        make_global_lstm_config("global_lstm_stationary", feature_sets["global_stationary"], horizon),
    ]
    horizon_inputs.append({
        "horizon_name": horizon_name,
        "horizon": horizon,
        "threshold_grid": spec["threshold_grid"],
        "model_df": model_df,
        "feature_cols": feature_sets[payload.get("primary_global_feature_set", "global_stationary")],
        "target_col": payload["target_column"],
        "model_configs": model_configs,
        "artifact_dir": GLOBAL_LSTM_OUTPUT_DIR / horizon_name / "global_lstm",
    })
    print({
        "horizon": horizon_name,
        "rows": len(model_df),
        "tickers": model_df["ticker"].nunique(),
        "global_all_features": len(feature_sets["global_all"]),
        "global_stationary_features": len(feature_sets["global_stationary"]),
        "target": payload["target_column"],
    })

{'horizon': 'week', 'rows': 19407, 'tickers': 7, 'global_all_features': 167, 'global_stationary_features': 164, 'target': 'target_return_5_next_open'}
{'horizon': 'month', 'rows': 19295, 'tickers': 7, 'global_all_features': 167, 'global_stationary_features': 164, 'target': 'target_return_21_next_open'}

## Train And Evaluate

In [6]:
global_lstm_results = {}

for item in horizon_inputs:
    horizon_name = item["horizon_name"]
    horizon = int(item["horizon"])
    mlflow_config = MLflowRunConfig(
        tracking_uri=MLFLOW_TRACKING_URI,
        experiment_name=MLFLOW_EXPERIMENT_NAME,
        notebook_name="02c_global_lstm_forecasting",
        horizon_name=horizon_name,
        horizon=horizon,
        enabled=MLFLOW_ENABLED,
        log_optuna_trials=MLFLOW_LOG_OPTUNA_TRIALS,
    )
    mlflow_params = {
        "force_retrain": FORCE_RETRAIN,
        "random_state": RANDOM_STATE,
        "global_lstm_n_trials": GLOBAL_LSTM_N_TRIALS,
        "global_lstm_optuna_n_jobs": GLOBAL_LSTM_OPTUNA_N_JOBS,
        "global_lstm_max_epochs": GLOBAL_LSTM_MAX_EPOCHS,
        "global_lstm_patience": GLOBAL_LSTM_PATIENCE,
        "global_lstm_ensemble_seeds": GLOBAL_LSTM_ENSEMBLE_SEEDS,
        "model_count": len(item["model_configs"]),
        "feature_count": len(item["feature_cols"]),
        "target_col": item["target_col"],
        "threshold_grid": item["threshold_grid"],
        "validation_rows": STRICT_VALIDATION_ROWS,
        "test_rows": STRICT_TEST_ROWS,
        "transaction_cost_bps": TRANSACTION_COST_BPS,
        "slippage_bps": SLIPPAGE_BPS,
        "signal_anchor": SIGNAL_ANCHOR,
        "min_validation_trades": MIN_VALIDATION_TRADES,
        "max_validation_drawdown": MAX_VALIDATION_DRAWDOWN,
    }
    with mlflow_horizon_run(
        mlflow_config,
        params=mlflow_params,
        tags={"training_protocol": "strict_global_lstm", "training_notebook": "02c_global_lstm_forecasting"},
    ) as mlflow_run:
        result = run_strict_global_lstm_protocol(
            model_df=item["model_df"],
            feature_cols=item["feature_cols"],
            target_col=item["target_col"],
            model_configs=item["model_configs"],
            artifact_dir=item["artifact_dir"],
            force_retrain=FORCE_RETRAIN,
            random_state=RANDOM_STATE,
            run_metadata={
                "horizon_name": horizon_name,
                "horizon": horizon,
                "training_notebook": "02c_global_lstm_forecasting",
                "global_lstm_run": True,
            },
            validation_rows=STRICT_VALIDATION_ROWS,
            test_rows=STRICT_TEST_ROWS,
            mature_min_rows=MATURE_MIN_ROWS,
            limited_history_min_block_rows=LIMITED_HISTORY_MIN_BLOCK_ROWS,
            min_train_rows=MIN_TRAIN_ROWS,
            max_train_rows=STRICT_MAX_TRAIN_ROWS,
            inner_max_folds=INNER_MAX_FOLDS,
            inner_min_train_rows=INNER_MIN_TRAIN_ROWS,
            transaction_cost_bps=TRANSACTION_COST_BPS,
            slippage_bps=SLIPPAGE_BPS,
            threshold_grid=item["threshold_grid"],
            signal_anchor=SIGNAL_ANCHOR,
            min_validation_trades=MIN_VALIDATION_TRADES,
            max_validation_drawdown=MAX_VALIDATION_DRAWDOWN,
            mlflow_trial_logger=mlflow_run.trial_logger,
        )
        log_strict_protocol_result(
            result,
            params=mlflow_params,
            tags={"training_protocol": "strict_global_lstm", "training_notebook": "02c_global_lstm_forecasting"},
        )
    global_lstm_results[horizon_name] = result

    print(f"=== Global LSTM strict protocol: {horizon_name} ({horizon} trading days) ===")
    display(result["validation_threshold_search"])
    display(result["validation_model_ranking"])
    display(result["test_panel_signal_metrics"])
    display(result["test_signal_metrics"])
    display(result["leakage_audit"])

    failed = result["leakage_audit"][~result["leakage_audit"]["passed"]]
    if not failed.empty:
        raise AssertionError(f"Global LSTM leakage audit failed for {horizon_name}: {failed['check'].tolist()}")

🏃 View run week-global_lstm_all-trial-0 at: http://localhost:5000/#/experiments/2/runs/47adbeb064e84f7785b3bf4979f92c0e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-1 at: http://localhost:5000/#/experiments/2/runs/dfebfcd216434547adc0042e4ffa74c6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-2 at: http://localhost:5000/#/experiments/2/runs/63a3bec9ad994ec2a1e7446a1bd390e0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-3 at: http://localhost:5000/#/experiments/2/runs/f3c614a610b14f1b91fc7e36ddcc680a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-4 at: http://localhost:5000/#/experiments/2/runs/2cbcb18e223d4f64aa6e9dfaa00f87e4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-5 at: http://localhost:5000/#/experiments/2/runs/2f4addb8fb32421da065e1cf34dd02ec
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-6 at: http://localhost:5000/#/experiments/2/runs/88dce465c65f4182aebd7ab322b6f31f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-7 at: http://localhost:5000/#/experiments/2/runs/a4537c05a3044d48ae599717502ed356
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-8 at: http://localhost:5000/#/experiments/2/runs/dfccdc834e0648c98659c48c9ffdd073
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-9 at: http://localhost:5000/#/experiments/2/runs/fde2cb244e514878877d71b2dbf1ca06
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-10 at: http://localhost:5000/#/experiments/2/runs/57ecf2ca499e4eeea880ad1d7b2764c3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-11 at: http://localhost:5000/#/experiments/2/runs/4d98b745cbff498fb1b4170db4217984
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-12 at: http://localhost:5000/#/experiments/2/runs/6db0fabaa6c34e9c98bc3bf99758e7ee
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-13 at: http://localhost:5000/#/experiments/2/runs/d38590a2dd114f29b215b1e9fdf139e2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-14 at: http://localhost:5000/#/experiments/2/runs/4d4f69cdf8bc4efca4fa44958c25f726
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-15 at: http://localhost:5000/#/experiments/2/runs/703064eb22e746a1ba3005b640b1e93e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-16 at: http://localhost:5000/#/experiments/2/runs/31ac72b7823e4dc99f3ada145deb876e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-17 at: http://localhost:5000/#/experiments/2/runs/07705c10b30b4421902df1a4d795279d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-18 at: http://localhost:5000/#/experiments/2/runs/aaf9a76fda1a4d71ad1c70793c0ac399
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-19 at: http://localhost:5000/#/experiments/2/runs/c13daaa0741d49659e48d670b006556d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-20 at: http://localhost:5000/#/experiments/2/runs/bf8254f467dd4be8bccac61b89ea2934
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-21 at: http://localhost:5000/#/experiments/2/runs/70c723ce7fc2449e88c88d58ae6324ac
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-22 at: http://localhost:5000/#/experiments/2/runs/98e0b7ecf1094a1e940cc5d77192e0ab
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-23 at: http://localhost:5000/#/experiments/2/runs/2e3f70117dc044fca8c2a54769da848c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-24 at: http://localhost:5000/#/experiments/2/runs/0b9a119f3ca34f1d9d1b78518fa6a7f5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-25 at: http://localhost:5000/#/experiments/2/runs/5c7668846d064eaab622abad68ae54c3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-26 at: http://localhost:5000/#/experiments/2/runs/c845778ed9ed422bb0af62ca489e1557
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-27 at: http://localhost:5000/#/experiments/2/runs/8dd5a94533f6440d9ce4c9a29f3e1423
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-28 at: http://localhost:5000/#/experiments/2/runs/d86e10c807ba4a3b809ff8d2f75ae358
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_all-trial-29 at: http://localhost:5000/#/experiments/2/runs/4afbff35a53c4f8dbd7360d905265dbb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-0 at: http://localhost:5000/#/experiments/2/runs/46eee6ecddb54a21bdae3296daa7824e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-1 at: http://localhost:5000/#/experiments/2/runs/67ef9b7626414e499e13ced03739fd4e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-2 at: http://localhost:5000/#/experiments/2/runs/52e9c453fd6c4853a71dafad5bfdc114
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-3 at: http://localhost:5000/#/experiments/2/runs/00c9ad841cac454baac442338211932d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-4 at: http://localhost:5000/#/experiments/2/runs/2e2902c8d2944d4fbfc1253b8457cbc3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-5 at: http://localhost:5000/#/experiments/2/runs/789a644ee4244c41aa96cc7bebf374d5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-6 at: http://localhost:5000/#/experiments/2/runs/6c9340d56f7746119ab48f755e6681f2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-7 at: http://localhost:5000/#/experiments/2/runs/9fadd6df76b3485f9bc298acc6ad442e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-8 at: http://localhost:5000/#/experiments/2/runs/96e05bc72d864c0eadeedbacb0924abe
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-9 at: http://localhost:5000/#/experiments/2/runs/f7f9546f99ba43cda218fae4522a3a9d
🧪 View experiment at: http://localhost:5000/#/experiments/2

/home/sapce/forecasting_stock_prices/forecasting/src/stock_forecast/strict_protocol.py:1338: RuntimeWarning: Mean of empty slice
  mean_ticker_sharpe = float(np.nanmean(np.clip(ticker_sharpe, -5.0, 5.0))) if len(ticker_sharpe) else float("nan")

🏃 View run week-global_lstm_stationary-trial-10 at: http://localhost:5000/#/experiments/2/runs/22625b1b7994445289252edc179d9b15
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-11 at: http://localhost:5000/#/experiments/2/runs/752b971e098e44acad61302e85a12aa5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-12 at: http://localhost:5000/#/experiments/2/runs/89433fc4d2404ffaa43e6155ea8a2e92
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-13 at: http://localhost:5000/#/experiments/2/runs/d5a1eab4ab8c4d50926e15284deca8d1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-14 at: http://localhost:5000/#/experiments/2/runs/224431aa4f9043d99c3f6108d8a30d31
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-15 at: http://localhost:5000/#/experiments/2/runs/e93b21145b6a4c519d5ea2ca3a1eee73
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-16 at: http://localhost:5000/#/experiments/2/runs/41b2cbb2bfd54ac39625bf38d20b5dff
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-17 at: http://localhost:5000/#/experiments/2/runs/2a7161b03d5d41a8934d87eba4e3f0af
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-18 at: http://localhost:5000/#/experiments/2/runs/f3861ccc4178422aaa691bc72f76210b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-19 at: http://localhost:5000/#/experiments/2/runs/b1d65655205e4bd083b6b6de3f9cefa0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-20 at: http://localhost:5000/#/experiments/2/runs/b610bd6de317457689db4d665e17cc14
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-21 at: http://localhost:5000/#/experiments/2/runs/74dbe8ade8094783bbbc9d3973e07ac5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-22 at: http://localhost:5000/#/experiments/2/runs/9080173bfc354d8699fa835b50561af9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-23 at: http://localhost:5000/#/experiments/2/runs/b43ce252af6547a09910a4ad14acda0d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-24 at: http://localhost:5000/#/experiments/2/runs/fe0ab76f017045328c5ee811b7f6ef8d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-25 at: http://localhost:5000/#/experiments/2/runs/81ed1f5b7d1b490fa1d080c71c0dce96
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-26 at: http://localhost:5000/#/experiments/2/runs/6e0fe065c0a54196aaa1e68f60638b5d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-27 at: http://localhost:5000/#/experiments/2/runs/c87582264795437aad671efbf210dce4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-28 at: http://localhost:5000/#/experiments/2/runs/885274c359604d1c8b6df856a97e422e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_lstm_stationary-trial-29 at: http://localhost:5000/#/experiments/2/runs/a5d6b435a4794c7387cd3d0f5a77d80a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run 02c_global_lstm_forecasting-week at: http://localhost:5000/#/experiments/2/runs/4c4e1cf104ad43aeadaf0f5d5f589426
🧪 View experiment at: http://localhost:5000/#/experiments/2
=== Global LSTM strict protocol: week (5 trading days) ===

,profit_risk_utility,panel_sharpe,mean_ticker_sharpe,cumulative_return,max_drawdown,turnover,number_of_trades,validation_constraints_pass,long_threshold,model_name,selected_threshold,horizon_name,horizon,training_notebook,global_lstm_run
0,-0.420521,-0.815018,-0.087049,-0.024013,-0.087544,0.038892,157,True,0.0025,global_lstm_all,0.0025,week,5,02c_global_lstm_forecasting,True
1,-0.425820,-0.582420,-0.224720,-0.020716,-0.102839,0.043561,175,True,0.0000,global_lstm_all,0.0025,week,5,02c_global_lstm_forecasting,True
2,-0.815299,-1.552791,-0.351689,-0.035258,-0.067640,0.040137,156,True,0.0050,global_lstm_all,0.0025,week,5,02c_global_lstm_forecasting,True
3,-1.124095,-1.862221,-0.773047,-0.026434,-0.038477,0.020268,87,True,0.0100,global_lstm_all,0.0025,week,5,02c_global_lstm_forecasting,True
4,-0.625159,-0.827585,-0.579495,-0.005600,-0.016803,0.005521,27,True,0.0100,global_lstm_stationary,0.0100,week,5,02c_global_lstm_forecasting,True
5,-0.820431,0.053696,-1.436583,0.001224,-0.059943,0.019035,77,True,0.0050,global_lstm_stationary,0.0100,week,5,02c_global_lstm_forecasting,True
6,-1.615171,-1.971849,-1.458975,-0.065092,-0.112266,0.023368,83,True,0.0000,global_lstm_stationary,0.0100,week,5,02c_global_lstm_forecasting,True
7,-1.751210,-1.740697,-1.893551,-0.048509,-0.094077,0.022801,90,True,0.0025,global_lstm_stationary,0.0100,week,5,02c_global_lstm_forecasting,True

,profit_risk_utility,panel_sharpe,mean_ticker_sharpe,cumulative_return,max_drawdown,turnover,number_of_trades,validation_constraints_pass,long_threshold,model_name,selected_threshold,horizon_name,horizon,training_notebook,global_lstm_run,validation_rank,is_validation_selected
0,-0.420521,-0.815018,-0.087049,-0.024013,-0.087544,0.038892,157,True,0.0025,global_lstm_all,0.0025,week,5,02c_global_lstm_forecasting,True,1,True
1,-0.425820,-0.582420,-0.224720,-0.020716,-0.102839,0.043561,175,True,0.0000,global_lstm_all,0.0025,week,5,02c_global_lstm_forecasting,True,2,False
4,-0.625159,-0.827585,-0.579495,-0.005600,-0.016803,0.005521,27,True,0.0100,global_lstm_stationary,0.0100,week,5,02c_global_lstm_forecasting,True,3,False
2,-0.815299,-1.552791,-0.351689,-0.035258,-0.067640,0.040137,156,True,0.0050,global_lstm_all,0.0025,week,5,02c_global_lstm_forecasting,True,4,False
5,-0.820431,0.053696,-1.436583,0.001224,-0.059943,0.019035,77,True,0.0050,global_lstm_stationary,0.0100,week,5,02c_global_lstm_forecasting,True,5,False
3,-1.124095,-1.862221,-0.773047,-0.026434,-0.038477,0.020268,87,True,0.0100,global_lstm_all,0.0025,week,5,02c_global_lstm_forecasting,True,6,False
6,-1.615171,-1.971849,-1.458975,-0.065092,-0.112266,0.023368,83,True,0.0000,global_lstm_stationary,0.0100,week,5,02c_global_lstm_forecasting,True,7,False
7,-1.751210,-1.740697,-1.893551,-0.048509,-0.094077,0.022801,90,True,0.0025,global_lstm_stationary,0.0100,week,5,02c_global_lstm_forecasting,True,8,False

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning,long_threshold
0,-0.022185,-0.041926,0.023994,252.0,-1.747360,-2.460401,-0.047711,-0.878760,0.034524,137,__panel__,global_lstm_all,overlapping_tranches,863,False,0.0025
1,0.012959,0.024885,0.010454,252.0,2.380523,3.721241,-0.001681,14.803884,0.001804,8,__panel__,global_lstm_stationary,overlapping_tranches,863,False,0.0100

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning,long_threshold
0,-0.033954,-0.066755,0.145971,252.0,-0.457314,-0.462915,-0.209661,-0.318393,0.033333,21,CBOM,global_lstm_all,overlapping_tranches,126,False,0.0025
1,-0.006987,-0.016377,0.008492,252.0,-1.928554,-1.029844,-0.011607,-1.410943,0.011215,6,MBNK,global_lstm_all,overlapping_tranches,107,False,0.0025
2,-0.008088,-0.016110,0.014584,252.0,-1.104635,-0.980036,-0.010772,-1.495615,0.047619,30,SBER,global_lstm_all,overlapping_tranches,126,False,0.0025
3,0.002781,0.005570,0.011874,252.0,0.469059,0.405468,-0.005363,1.038513,0.034921,22,SBERP,global_lstm_all,overlapping_tranches,126,False,0.0025
4,-0.083699,-0.160392,0.032166,252.0,-4.986427,-3.694911,-0.083699,-1.916301,0.022222,14,SVCB,global_lstm_all,overlapping_tranches,126,False,0.0025
5,-0.020295,-0.040178,0.027085,252.0,-1.483403,-1.282047,-0.029895,-1.343946,0.034921,22,T,global_lstm_all,overlapping_tranches,126,False,0.0025
6,-0.036153,-0.070998,0.058818,252.0,-1.207082,-1.796862,-0.069879,-1.016020,0.034921,22,VTBR,global_lstm_all,overlapping_tranches,126,False,0.0025
7,0.058011,0.119386,0.063842,252.0,1.870038,2.156981,-0.000300,398.013871,0.006349,4,CBOM,global_lstm_stationary,overlapping_tranches,126,False,0.0100
8,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,MBNK,global_lstm_stationary,overlapping_tranches,107,False,0.0100
9,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,SBER,global_lstm_stationary,overlapping_tranches,126,False,0.0100
10,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,SBERP,global_lstm_stationary,overlapping_tranches,126,False,0.0100
11,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,SVCB,global_lstm_stationary,overlapping_tranches,126,False,0.0100
12,-0.004023,-0.008030,0.005290,252.0,-1.517851,-0.208489,-0.004023,-1.995977,0.003175,2,T,global_lstm_stationary,overlapping_tranches,126,False,0.0100
13,0.039642,0.080855,0.039082,252.0,2.068880,NaN,-0.000300,269.557593,0.003175,2,VTBR,global_lstm_stationary,overlapping_tranches,126,False,0.0100

,check,passed,details
0,global outer splits are available,True,split_rows=7
1,global validation predictions are available,True,rows=1726
2,global test predictions are available,True,rows=1726
3,global cutoffs are chronological,True,"global_validation_start=2025-08-26 00:00:00, g..."
4,ticker split dates are chronological,True,bad_rows=0
5,validation predictions match ticker split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match ticker split dates,True,"out_of_window=0, wrong_role=0"
7,validation model target dates end before globa...,True,overlap_rows=0
8,final refit target dates end before global tes...,True,overlap_rows=0
9,global final model payloads exist for test pre...,True,missing_models=0
10,test panel signal metrics are available,True,rows=2

🏃 View run month-global_lstm_all-trial-0 at: http://localhost:5000/#/experiments/2/runs/289a15a655d14034937786923854d8ff
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-1 at: http://localhost:5000/#/experiments/2/runs/ee6cd3644bf245f6a290b677f07ce2ff
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-2 at: http://localhost:5000/#/experiments/2/runs/4b8aeb8935034a3a96ded5c7ec442b61
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-3 at: http://localhost:5000/#/experiments/2/runs/b24c6c73995f48deb70ce3714899c6a2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-4 at: http://localhost:5000/#/experiments/2/runs/6245e703bd5148649c50a60e7eb224b0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-5 at: http://localhost:5000/#/experiments/2/runs/03a40a84d1d841b79a3837b4a2247f86
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-6 at: http://localhost:5000/#/experiments/2/runs/35de85b2a0e14f9a8f10adb40e389a8c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-7 at: http://localhost:5000/#/experiments/2/runs/647dae9746ae450ea2857b7ed1ed01a8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-8 at: http://localhost:5000/#/experiments/2/runs/0f7a90407ac446ce95b788f759bdd889
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-9 at: http://localhost:5000/#/experiments/2/runs/3df402c944274ae69bbe01ba1aeaa7c6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-10 at: http://localhost:5000/#/experiments/2/runs/58415a749c544bafa5fb7fbd837b8d89
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-11 at: http://localhost:5000/#/experiments/2/runs/bf45bf68d228400fbd3816f42e94cda1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-12 at: http://localhost:5000/#/experiments/2/runs/bf079569126849a9a60bd2c6e31fc77e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-13 at: http://localhost:5000/#/experiments/2/runs/b39ec9e0f24d4b1789aedb5b25d92e7e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-14 at: http://localhost:5000/#/experiments/2/runs/0eb0e2ebc4d7444c8adcb2b53c007f93
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-15 at: http://localhost:5000/#/experiments/2/runs/869c1b2327844126a36c5202b8c1055e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-16 at: http://localhost:5000/#/experiments/2/runs/4f72f1d6c0b54f288b9d6130e1556173
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-17 at: http://localhost:5000/#/experiments/2/runs/a2b0c2d7f77a47a894e96a9219e55d04
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-18 at: http://localhost:5000/#/experiments/2/runs/7bda61b5844f47ef882b6f6fc49cd03c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-19 at: http://localhost:5000/#/experiments/2/runs/57985dc55d5e4030a27f642c7b231387
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-20 at: http://localhost:5000/#/experiments/2/runs/a63db24292114e8eb8de268c585a7d4f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-21 at: http://localhost:5000/#/experiments/2/runs/d569a37496f142d9b3e768801a56a437
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-22 at: http://localhost:5000/#/experiments/2/runs/f3112efa6b41427997b37476cd3a4eb4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-23 at: http://localhost:5000/#/experiments/2/runs/1d083e011f49434e9f17175aa8f5a543
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-24 at: http://localhost:5000/#/experiments/2/runs/81606eb0cd114620be4d861526adafa3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-25 at: http://localhost:5000/#/experiments/2/runs/edb3b454edf841d591173399d78d6816
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-26 at: http://localhost:5000/#/experiments/2/runs/b809e4787ea748e18af1c3ffe9e36477
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-27 at: http://localhost:5000/#/experiments/2/runs/54573e7dbb504999823bdf39c232ae8a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-28 at: http://localhost:5000/#/experiments/2/runs/0863856d18d749f4b9ded749eac9d1d1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_all-trial-29 at: http://localhost:5000/#/experiments/2/runs/900de5d3b57f407790575e8ccaffb64d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-0 at: http://localhost:5000/#/experiments/2/runs/cbb8c5a42a2846e2b67a7af044f4747f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-1 at: http://localhost:5000/#/experiments/2/runs/e414a0d61e7c4d3baa168a0bad4296f7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-2 at: http://localhost:5000/#/experiments/2/runs/799f6b8fb824472bb89458944a9bc7df
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-3 at: http://localhost:5000/#/experiments/2/runs/26ea73df532d42d688578298ccf9ad4e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-4 at: http://localhost:5000/#/experiments/2/runs/69d5865ba3744261aabeae8e7d8ae67b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-5 at: http://localhost:5000/#/experiments/2/runs/9c1f576a6a8646f696f24fb3d13ca702
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-6 at: http://localhost:5000/#/experiments/2/runs/b0f02c5f5be347d492715e46893f768e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-7 at: http://localhost:5000/#/experiments/2/runs/770b20a11fe644e7bc1b6fc0c6ede1da
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-8 at: http://localhost:5000/#/experiments/2/runs/1849bbcc6a8d4b6ebd417146f528d562
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-9 at: http://localhost:5000/#/experiments/2/runs/d4f402abeadf4c259d9390f01c6909c5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-10 at: http://localhost:5000/#/experiments/2/runs/ca6588e824a345b19772ab2634984471
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-11 at: http://localhost:5000/#/experiments/2/runs/7f3b5e560a054cf29dfd77ff55530e77
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-12 at: http://localhost:5000/#/experiments/2/runs/f77b556e8b9e495996921a675d052457
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-13 at: http://localhost:5000/#/experiments/2/runs/96bb3e22005f4aa69ecc9f098968f147
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-14 at: http://localhost:5000/#/experiments/2/runs/3c9013aca8a0481c8da5db590c62ef05
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-15 at: http://localhost:5000/#/experiments/2/runs/8fbee853da9646d18570d862a787de73
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-16 at: http://localhost:5000/#/experiments/2/runs/6697ce5c315d4ac19d334e3a124fd2b1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-17 at: http://localhost:5000/#/experiments/2/runs/82ddc346ca2d4ab2930fd6e4aefe7cc5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-18 at: http://localhost:5000/#/experiments/2/runs/4991acd91c6b4adda8da5d6aa55fae55
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-19 at: http://localhost:5000/#/experiments/2/runs/7e13fee238b547c1bf26b3641403a654
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-20 at: http://localhost:5000/#/experiments/2/runs/15aa2485f8b34554b15b92b139390f2f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-21 at: http://localhost:5000/#/experiments/2/runs/f03d9b61de0147b2810fcbe2570c1d06
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-22 at: http://localhost:5000/#/experiments/2/runs/356def555a3944ac834bbfa54666b196
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-23 at: http://localhost:5000/#/experiments/2/runs/7fa63595b909406688df82fd1cb5010a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-24 at: http://localhost:5000/#/experiments/2/runs/77f85f3e904a4c10a48a20631678bdbc
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-25 at: http://localhost:5000/#/experiments/2/runs/286b99b10d8f4a83bfe20d0c8375851e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-26 at: http://localhost:5000/#/experiments/2/runs/364174e974654cf39000dc5989665052
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-27 at: http://localhost:5000/#/experiments/2/runs/bec4011ae48844cd92adc73736b9f12a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-28 at: http://localhost:5000/#/experiments/2/runs/c01bf6a8469c4e759bcfbe6970226c67
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_lstm_stationary-trial-29 at: http://localhost:5000/#/experiments/2/runs/1a6419b50df14005b48e0a0e53bc0bbe
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run 02c_global_lstm_forecasting-month at: http://localhost:5000/#/experiments/2/runs/87532bdacaf2493bac045c021aeee8d9
🧪 View experiment at: http://localhost:5000/#/experiments/2
=== Global LSTM strict protocol: month (21 trading days) ===

,profit_risk_utility,panel_sharpe,mean_ticker_sharpe,cumulative_return,max_drawdown,turnover,number_of_trades,validation_constraints_pass,long_threshold,model_name,selected_threshold,horizon_name,horizon,training_notebook,global_lstm_run
0,-1.890985,-2.218526,-1.973047,-0.014543,-0.028268,0.003413,54,True,0.020,global_lstm_all,0.02,month,21,02c_global_lstm_forecasting,True
1,-3.177663,-3.744990,-3.280535,-0.040669,-0.055028,0.004069,51,True,0.010,global_lstm_all,0.02,month,21,02c_global_lstm_forecasting,True
2,-3.378172,-3.999214,-3.452872,-0.052975,-0.069020,0.004458,64,True,0.005,global_lstm_all,0.02,month,21,02c_global_lstm_forecasting,True
3,-3.599454,-4.666607,-3.395833,-0.069313,-0.083765,0.003813,62,True,0.000,global_lstm_all,0.02,month,21,02c_global_lstm_forecasting,True
4,-0.968581,-0.971107,-1.103040,-0.006372,-0.024120,0.002983,46,True,0.020,global_lstm_stationary,0.02,month,21,02c_global_lstm_forecasting,True
5,-2.564705,-3.032347,-2.642185,-0.027876,-0.047069,0.003765,62,True,0.010,global_lstm_stationary,0.02,month,21,02c_global_lstm_forecasting,True
6,-3.445963,-4.608472,-3.187233,-0.052620,-0.070055,0.004675,69,True,0.005,global_lstm_stationary,0.02,month,21,02c_global_lstm_forecasting,True
7,-3.877457,-5.308555,-3.472618,-0.076488,-0.093338,0.005101,78,True,0.000,global_lstm_stationary,0.02,month,21,02c_global_lstm_forecasting,True

,profit_risk_utility,panel_sharpe,mean_ticker_sharpe,cumulative_return,max_drawdown,turnover,number_of_trades,validation_constraints_pass,long_threshold,model_name,selected_threshold,horizon_name,horizon,training_notebook,global_lstm_run,validation_rank,is_validation_selected
4,-0.968581,-0.971107,-1.103040,-0.006372,-0.024120,0.002983,46,True,0.020,global_lstm_stationary,0.02,month,21,02c_global_lstm_forecasting,True,1,True
0,-1.890985,-2.218526,-1.973047,-0.014543,-0.028268,0.003413,54,True,0.020,global_lstm_all,0.02,month,21,02c_global_lstm_forecasting,True,2,False
5,-2.564705,-3.032347,-2.642185,-0.027876,-0.047069,0.003765,62,True,0.010,global_lstm_stationary,0.02,month,21,02c_global_lstm_forecasting,True,3,False
1,-3.177663,-3.744990,-3.280535,-0.040669,-0.055028,0.004069,51,True,0.010,global_lstm_all,0.02,month,21,02c_global_lstm_forecasting,True,4,False
2,-3.378172,-3.999214,-3.452872,-0.052975,-0.069020,0.004458,64,True,0.005,global_lstm_all,0.02,month,21,02c_global_lstm_forecasting,True,5,False
6,-3.445963,-4.608472,-3.187233,-0.052620,-0.070055,0.004675,69,True,0.005,global_lstm_stationary,0.02,month,21,02c_global_lstm_forecasting,True,6,False
3,-3.599454,-4.666607,-3.395833,-0.069313,-0.083765,0.003813,62,True,0.000,global_lstm_all,0.02,month,21,02c_global_lstm_forecasting,True,7,False
7,-3.877457,-5.308555,-3.472618,-0.076488,-0.093338,0.005101,78,True,0.000,global_lstm_stationary,0.02,month,21,02c_global_lstm_forecasting,True,8,False

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning,long_threshold
0,0.043721,0.085124,0.010171,252.0,8.369657,29.882215,-0.003033,28.061475,0.001759,33,__panel__,global_lstm_all,overlapping_tranches,858,False,0.02
1,-0.004481,-0.008537,0.004336,252.0,-1.968762,-3.512713,-0.009841,-0.867487,0.001883,34,__panel__,global_lstm_stationary,overlapping_tranches,858,False,0.02

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning,long_threshold
0,0.214945,0.476091,0.062492,252.0,7.618460,33.442911,-0.025671,18.545558,0.004157,11,CBOM,global_lstm_all,overlapping_tranches,126,False,0.02
1,-0.001792,-0.004337,0.002243,252.0,-1.933565,-0.496060,-0.002015,-2.152320,0.001832,4,MBNK,global_lstm_all,overlapping_tranches,104,False,0.02
2,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,SBER,global_lstm_all,overlapping_tranches,126,False,0.02
3,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,SBERP,global_lstm_all,overlapping_tranches,126,False,0.02
4,-0.012932,-0.026107,0.008983,252.0,-2.906370,-0.983581,-0.012932,-2.018695,0.002304,6,SVCB,global_lstm_all,overlapping_tranches,124,False,0.02
5,0.049757,0.101989,0.012820,252.0,7.955377,NaN,-0.000071,1427.902861,0.001512,4,T,global_lstm_all,overlapping_tranches,126,False,0.02
6,0.067745,0.140080,0.025174,252.0,5.564514,18.793026,-0.004640,30.188745,0.003023,8,VTBR,global_lstm_all,overlapping_tranches,126,False,0.02
7,0.027810,0.056394,0.021826,252.0,2.583868,NaN,-0.000071,789.549325,0.002646,7,CBOM,global_lstm_stationary,overlapping_tranches,126,False,0.02
8,-0.087705,-0.199420,0.018027,252.0,-11.062523,-12.148443,-0.087705,-2.273759,0.000458,1,MBNK,global_lstm_stationary,overlapping_tranches,104,False,0.02
9,0.008418,0.016907,0.004514,252.0,3.745804,97.145721,-0.000116,145.760470,0.003779,10,SBER,global_lstm_stationary,overlapping_tranches,126,False,0.02
10,0.004536,0.009092,0.003151,252.0,2.885563,56.343150,-0.000160,56.665359,0.001512,4,SBERP,global_lstm_stationary,overlapping_tranches,126,False,0.02
11,0.000000,0.000000,0.000000,252.0,NaN,NaN,0.000000,NaN,0.000000,0,SVCB,global_lstm_stationary,overlapping_tranches,124,False,0.02
12,0.002689,0.005386,0.002749,252.0,1.958971,NaN,-0.000071,75.408837,0.000756,2,T,global_lstm_stationary,overlapping_tranches,126,False,0.02
13,0.013581,0.027346,0.011707,252.0,2.335816,6.264438,-0.000816,33.508076,0.003779,10,VTBR,global_lstm_stationary,overlapping_tranches,126,False,0.02

,check,passed,details
0,global outer splits are available,True,split_rows=7
1,global validation predictions are available,True,rows=1716
2,global test predictions are available,True,rows=1716
3,global cutoffs are chronological,True,"global_validation_start=2025-08-08 00:00:00, g..."
4,ticker split dates are chronological,True,bad_rows=0
5,validation predictions match ticker split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match ticker split dates,True,"out_of_window=0, wrong_role=0"
7,validation model target dates end before globa...,True,overlap_rows=0
8,final refit target dates end before global tes...,True,overlap_rows=0
9,global final model payloads exist for test pre...,True,missing_models=0
10,test panel signal metrics are available,True,rows=2

## Comparison Handles

In [7]:
for item in horizon_inputs:
    horizon_name = item["horizon_name"]
    global_reports = item["artifact_dir"] / "strict_protocol" / "reports"
    main_reports = ARTIFACT_DIR / "horizons" / horizon_name / "strict_protocol" / "reports"
    print({
        "horizon": horizon_name,
        "global_lstm_reports": display_path(global_reports),
        "main_strict_reports": display_path(main_reports),
        "global_panel_metrics": display_path(global_reports / "test_panel_signal_metrics.parquet"),
    })

{'horizon': 'week', 'global_lstm_reports': 'artifacts/horizons/week/global_lstm/strict_protocol/reports', 'main_strict_reports': 'artifacts/horizons/week/strict_protocol/reports', 'global_panel_metrics': 'artifacts/horizons/week/global_lstm/strict_protocol/reports/test_panel_signal_metrics.parquet'}
{'horizon': 'month', 'global_lstm_reports': 'artifacts/horizons/month/global_lstm/strict_protocol/reports', 'main_strict_reports': 'artifacts/horizons/month/strict_protocol/reports', 'global_panel_metrics': 'artifacts/horizons/month/global_lstm/strict_protocol/reports/test_panel_signal_metrics.parquet'}