# 02d Global Mamba Strict Forecasting

Train official `mamba-ssm` pooled/global Mamba sequence models with calendar-global purging and profit/risk validation selection.

## Setup

In [1]:
from pathlib import Path
import os
import sys

cwd = Path.cwd().resolve()
for candidate in [cwd, cwd / "forecasting", cwd.parent, cwd.parent / "forecasting"]:
    if (candidate / "src" / "stock_forecast").exists():
        PROJECT_DIR = candidate
        break
else:
    raise RuntimeError("Cannot locate forecasting project directory with src/stock_forecast")

SRC_DIR = PROJECT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

ARTIFACT_DIR = PROJECT_DIR / "artifacts"
DATA_DIR = ARTIFACT_DIR / "data"
REPORTS_DIR = ARTIFACT_DIR / "reports"
MAMBA_DATA_DIR = DATA_DIR / "mamba"
MAMBA_OUTPUT_DIR = Path(os.environ.get("MAMBA_OUTPUT_DIR", ARTIFACT_DIR / "horizons")).expanduser().resolve()
for path in [DATA_DIR, REPORTS_DIR]:
    path.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("TILELANG_CACHE_DIR", "/tmp/tilelang")


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(PROJECT_DIR))
    except ValueError:
        return str(path)


print(f"PROJECT_DIR = {PROJECT_DIR}")

PROJECT_DIR = /home/sapce/forecasting_stock_prices/forecasting

In [2]:
import importlib.util
import pandas as pd
from IPython.display import display

from stock_forecast.artifacts import load_json, load_table
from stock_forecast.mlflow_tracking import MLflowRunConfig, log_strict_protocol_result, mlflow_horizon_run
from stock_forecast.models import build_model
from stock_forecast.strict_protocol import run_strict_global_lstm_protocol

pd.set_option("display.max_columns", 220)

if importlib.util.find_spec("torch") is None:
    raise ImportError("PyTorch is required for this notebook. Install/use the torchlab environment.")
if importlib.util.find_spec("mamba_ssm") is None:
    raise ImportError("Official mamba-ssm is required. Install PyTorch first, then `pip install \"mamba-ssm[causal-conv1d]\" --no-build-isolation`.")

import torch


def env_int(name: str, default: int) -> int:
    return int(os.environ.get(name, default))


def env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y"}


def env_int_list(name: str, default: list[int]) -> list[int]:
    value = os.environ.get(name)
    if not value:
        return default
    return [int(item.strip()) for item in value.split(",") if item.strip()]

## Constants

In [3]:
FORCE_RETRAIN = env_bool("MAMBA_FORCE_RETRAIN", True)
RANDOM_STATE = env_int("MAMBA_RANDOM_STATE", 42)
MAMBA_REQUIRE_CUDA = env_bool("MAMBA_REQUIRE_CUDA", True)

STRICT_VALIDATION_ROWS = env_int("STRICT_VALIDATION_ROWS", 126)
STRICT_TEST_ROWS = env_int("STRICT_TEST_ROWS", 126)
MATURE_MIN_ROWS = env_int("MATURE_MIN_ROWS", 1008)
LIMITED_HISTORY_MIN_BLOCK_ROWS = env_int("LIMITED_HISTORY_MIN_BLOCK_ROWS", 42)
MIN_TRAIN_ROWS = env_int("MIN_TRAIN_ROWS", 60)
STRICT_MAX_TRAIN_ROWS = env_int("STRICT_MAX_TRAIN_ROWS", 1260)
INNER_MAX_FOLDS = env_int("INNER_MAX_FOLDS", 3)
INNER_MIN_TRAIN_ROWS = env_int("INNER_MIN_TRAIN_ROWS", 504)

MAMBA_N_TRIALS = env_int("MAMBA_N_TRIALS", 30)
MAMBA_OPTUNA_N_JOBS = env_int("MAMBA_OPTUNA_N_JOBS", 1)
MAMBA_MAX_EPOCHS = env_int("MAMBA_MAX_EPOCHS", 120)
MAMBA_PATIENCE = env_int("MAMBA_PATIENCE", 12)
MAMBA_DEVICE = os.environ.get("MAMBA_DEVICE", "auto")
MAMBA_ENSEMBLE_SEEDS = env_int_list("MAMBA_ENSEMBLE_SEEDS", [1, 7, 21])

TRANSACTION_COST_BPS = 10
SLIPPAGE_BPS = 5
SIGNAL_ANCHOR = "expanding_median"
MIN_VALIDATION_TRADES = 8
MAX_VALIDATION_DRAWDOWN = -0.35

MLFLOW_ENABLED = env_bool("MLFLOW_ENABLED", True)
MLFLOW_TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI", "http://localhost:5000")
MLFLOW_EXPERIMENT_NAME = os.environ.get("MLFLOW_EXPERIMENT_NAME", "stock_return_forecasting_research")
MLFLOW_LOG_OPTUNA_TRIALS = env_bool("MLFLOW_LOG_OPTUNA_TRIALS", True)

HORIZONS = [
    {"name": "week", "horizon": 5, "threshold_grid": [0.0, 0.0025, 0.005, 0.01]},
    {"name": "month", "horizon": 21, "threshold_grid": [0.0, 0.005, 0.01, 0.02]},
]
selected_horizons = {name.strip() for name in os.environ.get("MAMBA_HORIZONS", "").split(",") if name.strip()}
if selected_horizons:
    HORIZONS = [item for item in HORIZONS if item["name"] in selected_horizons]

if MAMBA_REQUIRE_CUDA and not torch.cuda.is_available():
    raise RuntimeError("Official mamba-ssm is CUDA-oriented. Run on a CUDA host or set MAMBA_REQUIRE_CUDA=0 for an explicit CPU experiment.")

## Model Config

In [4]:
def make_mamba_search_space(horizon: int) -> dict:
    lookbacks = [60, 90, 126, 252] if horizon >= 21 else [60, 90, 126]
    huber_beta_choices = [0.04, 0.08, 0.12] if horizon >= 21 else [0.02, 0.04, 0.06]
    return {
        "lookback": {"type": "categorical", "choices": lookbacks},
        "model_dim": {"type": "categorical", "choices": [32, 64, 96, 128]},
        "num_layers": {"type": "categorical", "choices": [1, 2, 3]},
        "d_state": {"type": "categorical", "choices": [8, 16, 32, 64]},
        "d_conv": {"type": "categorical", "choices": [2, 3, 4]},
        "expand": {"type": "categorical", "choices": [1, 2]},
        "block_dropout": {"type": "float", "low": 0.0, "high": 0.35},
        "head_dropout": {"type": "float", "low": 0.10, "high": 0.50},
        "learning_rate": {"type": "float", "low": 5e-5, "high": 2e-3, "log": True},
        "weight_decay": {"type": "float", "low": 1e-5, "high": 1e-2, "log": True},
        "batch_size": {"type": "categorical", "choices": [32, 64, 128]},
        "loss": {"type": "categorical", "choices": ["smooth_l1", "huber", "mse"]},
        "huber_beta": {"type": "categorical", "choices": huber_beta_choices},
        "feature_clip": {"type": "categorical", "choices": [3.0, 5.0, 8.0]},
        "target_normalization": {"type": "categorical", "choices": ["global", "per_ticker"]},
        "balanced_ticker_sampling": {"type": "categorical", "choices": [True]},
        "grad_clip_norm": {"type": "float", "low": 0.5, "high": 2.0},
    }


def make_mamba_config(name: str, feature_cols: list[str], horizon: int) -> dict:
    return {
        "name": name,
        "model_type": "mamba",
        "estimator_factory": build_model,
        "input_mode": "full_frame",
        "feature_cols": feature_cols,
        "static_params": {
            "max_epochs": MAMBA_MAX_EPOCHS,
            "patience": MAMBA_PATIENCE,
            "device": MAMBA_DEVICE,
            "validation_fraction": 0.2,
        },
        "search_space": make_mamba_search_space(horizon),
        "post_selection_static_params": {"ensemble_seeds": MAMBA_ENSEMBLE_SEEDS},
        "n_trials": MAMBA_N_TRIALS,
        "optuna_n_jobs": MAMBA_OPTUNA_N_JOBS,
        "needs_scaler": False,
    }

## Load Mamba Data

In [5]:
horizon_inputs = []

for spec in HORIZONS:
    horizon_name = spec["name"]
    horizon = int(spec["horizon"])
    mamba_dir = MAMBA_DATA_DIR / "horizons" / horizon_name
    model_path = mamba_dir / "model_dataset.parquet"
    feature_path = mamba_dir / "feature_columns.json"
    if not model_path.exists() and not model_path.with_suffix(".csv").exists():
        raise FileNotFoundError(f"Missing Mamba data for {horizon_name}. Run notebooks/01d_mamba_eda.ipynb first.")
    payload = load_json(feature_path)
    model_df = load_table(model_path)
    model_df["date"] = pd.to_datetime(model_df["date"])
    feature_sets = payload["mamba_feature_sets"]
    primary_feature_set = payload.get("primary_mamba_feature_set", "mamba_stationary")
    model_configs = [
        make_mamba_config("global_mamba_stationary", feature_sets["mamba_stationary"], horizon),
        make_mamba_config("global_mamba_all", feature_sets["mamba_all"], horizon),
    ]
    horizon_inputs.append({
        "horizon_name": horizon_name,
        "horizon": horizon,
        "threshold_grid": spec["threshold_grid"],
        "model_df": model_df,
        "feature_cols": feature_sets[primary_feature_set],
        "target_col": payload["target_column"],
        "model_configs": model_configs,
        "artifact_dir": MAMBA_OUTPUT_DIR / horizon_name / "global_mamba",
    })
    print({
        "horizon": horizon_name,
        "rows": len(model_df),
        "tickers": model_df["ticker"].nunique(),
        "mamba_all_features": len(feature_sets["mamba_all"]),
        "mamba_stationary_features": len(feature_sets["mamba_stationary"]),
        "target": payload["target_column"],
        "artifact_dir": display_path(MAMBA_OUTPUT_DIR / horizon_name / "global_mamba"),
    })

{'horizon': 'week', 'rows': 19407, 'tickers': 7, 'mamba_all_features': 275, 'mamba_stationary_features': 258, 'target': 'target_return_5_next_open', 'artifact_dir': 'artifacts/horizons/week/global_mamba'}
{'horizon': 'month', 'rows': 19295, 'tickers': 7, 'mamba_all_features': 275, 'mamba_stationary_features': 258, 'target': 'target_return_21_next_open', 'artifact_dir': 'artifacts/horizons/month/global_mamba'}

## Train And Evaluate

In [6]:
global_mamba_results = {}

for item in horizon_inputs:
    horizon_name = item["horizon_name"]
    horizon = int(item["horizon"])
    mlflow_config = MLflowRunConfig(
        tracking_uri=MLFLOW_TRACKING_URI,
        experiment_name=MLFLOW_EXPERIMENT_NAME,
        notebook_name="02d_mamba_forecasting",
        horizon_name=horizon_name,
        horizon=horizon,
        enabled=MLFLOW_ENABLED,
        log_optuna_trials=MLFLOW_LOG_OPTUNA_TRIALS,
    )
    mlflow_params = {
        "force_retrain": FORCE_RETRAIN,
        "random_state": RANDOM_STATE,
        "mamba_n_trials": MAMBA_N_TRIALS,
        "mamba_optuna_n_jobs": MAMBA_OPTUNA_N_JOBS,
        "mamba_max_epochs": MAMBA_MAX_EPOCHS,
        "mamba_patience": MAMBA_PATIENCE,
        "mamba_ensemble_seeds": MAMBA_ENSEMBLE_SEEDS,
        "model_count": len(item["model_configs"]),
        "feature_count": len(item["feature_cols"]),
        "target_col": item["target_col"],
        "threshold_grid": item["threshold_grid"],
        "validation_rows": STRICT_VALIDATION_ROWS,
        "test_rows": STRICT_TEST_ROWS,
        "transaction_cost_bps": TRANSACTION_COST_BPS,
        "slippage_bps": SLIPPAGE_BPS,
        "signal_anchor": SIGNAL_ANCHOR,
        "min_validation_trades": MIN_VALIDATION_TRADES,
        "max_validation_drawdown": MAX_VALIDATION_DRAWDOWN,
    }
    with mlflow_horizon_run(
        mlflow_config,
        params=mlflow_params,
        tags={"training_protocol": "strict_global_mamba", "training_notebook": "02d_mamba_forecasting"},
    ) as mlflow_run:
        result = run_strict_global_lstm_protocol(
            model_df=item["model_df"],
            feature_cols=item["feature_cols"],
            target_col=item["target_col"],
            model_configs=item["model_configs"],
            artifact_dir=item["artifact_dir"],
            force_retrain=FORCE_RETRAIN,
            random_state=RANDOM_STATE,
            run_metadata={
                "horizon_name": horizon_name,
                "horizon": horizon,
                "training_notebook": "02d_mamba_forecasting",
                "global_mamba_run": True,
            },
            validation_rows=STRICT_VALIDATION_ROWS,
            test_rows=STRICT_TEST_ROWS,
            mature_min_rows=MATURE_MIN_ROWS,
            limited_history_min_block_rows=LIMITED_HISTORY_MIN_BLOCK_ROWS,
            min_train_rows=MIN_TRAIN_ROWS,
            max_train_rows=STRICT_MAX_TRAIN_ROWS,
            inner_max_folds=INNER_MAX_FOLDS,
            inner_min_train_rows=INNER_MIN_TRAIN_ROWS,
            transaction_cost_bps=TRANSACTION_COST_BPS,
            slippage_bps=SLIPPAGE_BPS,
            threshold_grid=item["threshold_grid"],
            signal_anchor=SIGNAL_ANCHOR,
            min_validation_trades=MIN_VALIDATION_TRADES,
            max_validation_drawdown=MAX_VALIDATION_DRAWDOWN,
            mlflow_trial_logger=mlflow_run.trial_logger,
        )
        log_strict_protocol_result(
            result,
            params=mlflow_params,
            tags={"training_protocol": "strict_global_mamba", "training_notebook": "02d_mamba_forecasting"},
        )
    global_mamba_results[horizon_name] = result

    print(f"=== Global Mamba strict protocol: {horizon_name} ({horizon} trading days) ===")
    display(result["validation_threshold_search"])
    display(result["validation_model_ranking"])
    display(result["test_panel_signal_metrics"])
    display(result["test_signal_metrics"])
    display(result["leakage_audit"])

    failed = result["leakage_audit"][~result["leakage_audit"]["passed"]]
    if not failed.empty:
        raise AssertionError(f"Global Mamba leakage audit failed for {horizon_name}: {failed[check].tolist()}")

🏃 View run week-global_mamba_stationary-trial-0 at: http://localhost:5000/#/experiments/2/runs/5e8848e7d0134e558552eb0662516692
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-1 at: http://localhost:5000/#/experiments/2/runs/eb5ec45d57ee47fe97d2e062010f5108
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-2 at: http://localhost:5000/#/experiments/2/runs/096fab2276ae4ca69a0a2e494da92b5f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-3 at: http://localhost:5000/#/experiments/2/runs/bfc7670052d243539e43fa1ddad8a8cf
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-4 at: http://localhost:5000/#/experiments/2/runs/15c1ee9b68054009962934a9b4aab6e0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-5 at: http://localhost:5000/#/experiments/2/runs/25b823daf46547f1b5ff8cda1fe2e9a7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-6 at: http://localhost:5000/#/experiments/2/runs/c55377818eed4e1089b7c1ba0d3d370b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-7 at: http://localhost:5000/#/experiments/2/runs/fb61cdb57bef4998991704d519a04f4d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-8 at: http://localhost:5000/#/experiments/2/runs/1cc882cce8324bf689694278afe98df4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-9 at: http://localhost:5000/#/experiments/2/runs/d5f964be824547df8034e07717074a04
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-10 at: http://localhost:5000/#/experiments/2/runs/2f23173825b448619041ab6d577d7db6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-11 at: http://localhost:5000/#/experiments/2/runs/02859fa5521c474991efd0e7f5ee9a85
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-12 at: http://localhost:5000/#/experiments/2/runs/ca6979979021417a802158569a43d52b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-13 at: http://localhost:5000/#/experiments/2/runs/7759958aa9174c429d747aafd0fabd44
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-14 at: http://localhost:5000/#/experiments/2/runs/9d6352650c5e4143a9a327938419540c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-15 at: http://localhost:5000/#/experiments/2/runs/c5910b63dece491b8e4bbf3a5ebc783e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-16 at: http://localhost:5000/#/experiments/2/runs/fe0c19383a094d1fac4e64663c9ff0e5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-17 at: http://localhost:5000/#/experiments/2/runs/40733468284940d990176da89f5a6778
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-18 at: http://localhost:5000/#/experiments/2/runs/be26c2bffd2f45c198010874b55f8dda
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-19 at: http://localhost:5000/#/experiments/2/runs/f12db5bb679e42c28d0b6023c2bebd03
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-20 at: http://localhost:5000/#/experiments/2/runs/655d678b083240638a3225b74c9f61aa
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-21 at: http://localhost:5000/#/experiments/2/runs/33fec9b9ae264caf88f63c4d68071664
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-22 at: http://localhost:5000/#/experiments/2/runs/731a2ff2efec477c872c3e5e5ebc5354
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-23 at: http://localhost:5000/#/experiments/2/runs/5469e223436b4073a8f3f9223a031b5e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-24 at: http://localhost:5000/#/experiments/2/runs/9b570a3c26cb444cac6e167f2dbf6b52
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-25 at: http://localhost:5000/#/experiments/2/runs/73b54b6b6cb6421196ae884492979e46
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-26 at: http://localhost:5000/#/experiments/2/runs/4a04b96d4e274396869694c35f80aa79
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-27 at: http://localhost:5000/#/experiments/2/runs/f0c20280b036432fb5b49b6f927f6bb1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-28 at: http://localhost:5000/#/experiments/2/runs/211bbbc1f6074d4cbfeee35f6fcb6bcd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_stationary-trial-29 at: http://localhost:5000/#/experiments/2/runs/02b9a9ec6a7143d9946e8918aadf8522
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-0 at: http://localhost:5000/#/experiments/2/runs/c6cc87aed1104a0895a482cf3923edaa
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-1 at: http://localhost:5000/#/experiments/2/runs/fc0b244d0f2c4039b6ef87f6777a66e4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-2 at: http://localhost:5000/#/experiments/2/runs/5bee0e553c7b46c6a030488edd6552ea
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-3 at: http://localhost:5000/#/experiments/2/runs/a339a98f172c4656b3032cff021d151a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-4 at: http://localhost:5000/#/experiments/2/runs/8b660c2a13ec48d68ff68cf914acbab9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-5 at: http://localhost:5000/#/experiments/2/runs/db67b9d8e3254941b107f70f7a2212ba
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-6 at: http://localhost:5000/#/experiments/2/runs/fa01803d8a3d4cc0acc293937c01defe
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-7 at: http://localhost:5000/#/experiments/2/runs/170e784be766467cb0da5dc9184c30c6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-8 at: http://localhost:5000/#/experiments/2/runs/600cfcd6597e4e9387784e6d09aa5c88
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-9 at: http://localhost:5000/#/experiments/2/runs/ad2a032986734b3ca7e91f3819ec5943
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-10 at: http://localhost:5000/#/experiments/2/runs/df2340eaf09146ee9ac83ba7fb23887e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-11 at: http://localhost:5000/#/experiments/2/runs/85b4adedf4394e6ab615e168f6ab30e3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-12 at: http://localhost:5000/#/experiments/2/runs/2353b28cb7794faeaeb93ae03f54bda7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-13 at: http://localhost:5000/#/experiments/2/runs/170306d1c3e54e9c990380e9f472e039
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-14 at: http://localhost:5000/#/experiments/2/runs/9bc5585a5ca14398a400eb05b818d010
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-15 at: http://localhost:5000/#/experiments/2/runs/b244f5af3648489b8e07db845677eb12
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-16 at: http://localhost:5000/#/experiments/2/runs/a1cddbaed3b141e9a4f02e6a73a4a2e7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-17 at: http://localhost:5000/#/experiments/2/runs/a16f232e90d2459da2fd39cf0b4c551d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-18 at: http://localhost:5000/#/experiments/2/runs/0c143bdb91df4c13816cc81c4a392136
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-19 at: http://localhost:5000/#/experiments/2/runs/c43369b6e9724086a499ea3085cd36b7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-20 at: http://localhost:5000/#/experiments/2/runs/ee7883eeb34940e583f009e6e0381d65
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-21 at: http://localhost:5000/#/experiments/2/runs/33dce56fb63e4203b36bbfd324a630f1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-22 at: http://localhost:5000/#/experiments/2/runs/8b5e931efc054f47a810feb34bf511dd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-23 at: http://localhost:5000/#/experiments/2/runs/2ddc1024be564bc8807af88e22250055
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-24 at: http://localhost:5000/#/experiments/2/runs/4ec1042bbd5d49ddbec93e2759aa91ff
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-25 at: http://localhost:5000/#/experiments/2/runs/d6e824d04e134f8da221018bd8197dd8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-26 at: http://localhost:5000/#/experiments/2/runs/f0c32c57cff04dc2b7ee03a15053ca9c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-27 at: http://localhost:5000/#/experiments/2/runs/0701ff499bdd4926986e8e6c73496d6e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-28 at: http://localhost:5000/#/experiments/2/runs/ee396e731b804303b5759912f75e9c13
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run week-global_mamba_all-trial-29 at: http://localhost:5000/#/experiments/2/runs/35400e424df94897934f2fc0d3e0bcc7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run 02d_mamba_forecasting-week at: http://localhost:5000/#/experiments/2/runs/2b4761b925fa42e2a86147ab3d45a810
🧪 View experiment at: http://localhost:5000/#/experiments/2
=== Global Mamba strict protocol: week (5 trading days) ===

,profit_risk_utility,panel_sharpe,mean_ticker_sharpe,cumulative_return,max_drawdown,turnover,number_of_trades,validation_constraints_pass,long_threshold,model_name,selected_threshold,horizon_name,horizon,training_notebook,global_mamba_run
0,-0.624211,-0.502172,-0.754022,-0.009205,-0.031037,0.023436,95,True,0.0100,global_mamba_stationary,0.01,week,5,02d_mamba_forecasting,True
1,-0.747214,-0.613666,-0.863693,-0.015415,-0.054303,0.035861,167,True,0.0050,global_mamba_stationary,0.01,week,5,02d_mamba_forecasting,True
2,-0.864000,-0.899596,-0.874004,-0.024434,-0.060454,0.043523,185,True,0.0025,global_mamba_stationary,0.01,week,5,02d_mamba_forecasting,True
3,-1.082900,-1.322229,-0.958530,-0.043233,-0.078559,0.049567,215,True,0.0000,global_mamba_stationary,0.01,week,5,02d_mamba_forecasting,True
4,-1.037849,-1.037417,-1.158043,-0.011687,-0.034721,0.023778,110,True,0.0100,global_mamba_all,0.01,week,5,02d_mamba_forecasting,True
5,-1.132054,-1.673607,-0.882045,-0.031250,-0.045586,0.045409,185,True,0.0050,global_mamba_all,0.01,week,5,02d_mamba_forecasting,True
6,-1.244965,-2.173627,-0.711055,-0.058893,-0.067268,0.052873,227,True,0.0000,global_mamba_all,0.01,week,5,02d_mamba_forecasting,True
7,-1.575092,-2.534032,-1.099988,-0.057809,-0.057532,0.044538,191,True,0.0025,global_mamba_all,0.01,week,5,02d_mamba_forecasting,True

,profit_risk_utility,panel_sharpe,mean_ticker_sharpe,cumulative_return,max_drawdown,turnover,number_of_trades,validation_constraints_pass,long_threshold,model_name,selected_threshold,horizon_name,horizon,training_notebook,global_mamba_run,validation_rank,is_validation_selected
0,-0.624211,-0.502172,-0.754022,-0.009205,-0.031037,0.023436,95,True,0.0100,global_mamba_stationary,0.01,week,5,02d_mamba_forecasting,True,1,True
1,-0.747214,-0.613666,-0.863693,-0.015415,-0.054303,0.035861,167,True,0.0050,global_mamba_stationary,0.01,week,5,02d_mamba_forecasting,True,2,False
2,-0.864000,-0.899596,-0.874004,-0.024434,-0.060454,0.043523,185,True,0.0025,global_mamba_stationary,0.01,week,5,02d_mamba_forecasting,True,3,False
4,-1.037849,-1.037417,-1.158043,-0.011687,-0.034721,0.023778,110,True,0.0100,global_mamba_all,0.01,week,5,02d_mamba_forecasting,True,4,False
3,-1.082900,-1.322229,-0.958530,-0.043233,-0.078559,0.049567,215,True,0.0000,global_mamba_stationary,0.01,week,5,02d_mamba_forecasting,True,5,False
5,-1.132054,-1.673607,-0.882045,-0.031250,-0.045586,0.045409,185,True,0.0050,global_mamba_all,0.01,week,5,02d_mamba_forecasting,True,6,False
6,-1.244965,-2.173627,-0.711055,-0.058893,-0.067268,0.052873,227,True,0.0000,global_mamba_all,0.01,week,5,02d_mamba_forecasting,True,7,False
7,-1.575092,-2.534032,-1.099988,-0.057809,-0.057532,0.044538,191,True,0.0025,global_mamba_all,0.01,week,5,02d_mamba_forecasting,True,8,False

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning,long_threshold
0,0.036960,0.071744,0.042771,252.0,1.677424,5.143237,-0.029699,2.415689,0.023485,106,__panel__,global_mamba_stationary,overlapping_tranches,863,False,0.01
1,0.057019,0.111671,0.044444,252.0,2.512608,7.126211,-0.032668,3.418352,0.027165,109,__panel__,global_mamba_all,overlapping_tranches,863,False,0.01

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning,long_threshold
0,0.390477,0.933426,0.272225,252.0,3.428872,10.696357,-0.128075,7.288138,0.030159,19,CBOM,global_mamba_stationary,overlapping_tranches,126,False,0.01
1,-0.019390,-0.045067,0.026905,252.0,-1.675061,-1.544979,-0.033633,-1.339978,0.052336,28,MBNK,global_mamba_stationary,overlapping_tranches,107,False,0.01
2,-0.001086,-0.002171,0.002967,252.0,-0.731809,-0.172777,-0.001969,-1.102556,0.006349,4,SBER,global_mamba_stationary,overlapping_tranches,126,False,0.01
3,-0.000849,-0.001698,0.002153,252.0,-0.788728,-0.218467,-0.001447,-1.173521,0.006349,4,SBERP,global_mamba_stationary,overlapping_tranches,126,False,0.01
4,-0.028845,-0.056859,0.049718,252.0,-1.143634,-1.351851,-0.087506,-0.649771,0.044444,28,SVCB,global_mamba_stationary,overlapping_tranches,126,False,0.01
5,0.014413,0.029033,0.017086,252.0,1.699231,1.512650,-0.011062,2.624490,0.015873,10,T,global_mamba_stationary,overlapping_tranches,126,False,0.01
6,-0.074817,-0.144037,0.029134,252.0,-4.943872,-3.279235,-0.074817,-1.925183,0.020635,13,VTBR,global_mamba_stationary,overlapping_tranches,126,False,0.01
7,0.338808,0.792408,0.279820,252.0,2.831844,6.942978,-0.162113,4.887997,0.026984,17,CBOM,global_mamba_all,overlapping_tranches,126,False,0.01
8,-0.017623,-0.041011,0.022520,252.0,-1.821103,-0.961739,-0.019115,-2.145515,0.026168,14,MBNK,global_mamba_all,overlapping_tranches,107,False,0.01
9,0.015619,0.031482,0.014914,252.0,2.110981,3.330761,-0.004086,7.705662,0.034921,22,SBER,global_mamba_all,overlapping_tranches,126,False,0.01
10,0.013167,0.026507,0.012594,252.0,2.104787,3.037455,-0.002526,10.493537,0.019048,12,SBERP,global_mamba_all,overlapping_tranches,126,False,0.01
11,-0.032099,-0.063167,0.049909,252.0,-1.265651,-1.468467,-0.083936,-0.752560,0.028571,18,SVCB,global_mamba_all,overlapping_tranches,126,False,0.01
12,0.057567,0.118449,0.038271,252.0,3.095041,4.646365,-0.010660,11.111310,0.019048,12,T,global_mamba_all,overlapping_tranches,126,False,0.01
13,-0.014042,-0.027887,0.028716,252.0,-0.971121,-0.707918,-0.038493,-0.724462,0.022222,14,VTBR,global_mamba_all,overlapping_tranches,126,False,0.01

,check,passed,details
0,global outer splits are available,True,split_rows=7
1,global validation predictions are available,True,rows=1726
2,global test predictions are available,True,rows=1726
3,global cutoffs are chronological,True,"global_validation_start=2025-08-26 00:00:00, g..."
4,ticker split dates are chronological,True,bad_rows=0
5,validation predictions match ticker split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match ticker split dates,True,"out_of_window=0, wrong_role=0"
7,validation model target dates end before globa...,True,overlap_rows=0
8,final refit target dates end before global tes...,True,overlap_rows=0
9,global final model payloads exist for test pre...,True,missing_models=0
10,test panel signal metrics are available,True,rows=2

🏃 View run month-global_mamba_stationary-trial-0 at: http://localhost:5000/#/experiments/2/runs/4723044ac016477f9828e3a78fc1c44a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-1 at: http://localhost:5000/#/experiments/2/runs/9d9cffcf41bc43e1a75d2cde05e95ace
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-2 at: http://localhost:5000/#/experiments/2/runs/f301b459101b40bb88077bf8d4b5fe64
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-3 at: http://localhost:5000/#/experiments/2/runs/70059c356d2545f1b7e05a06e57b4958
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-4 at: http://localhost:5000/#/experiments/2/runs/6ac9d874de90413eac4f25f03d90bde9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-5 at: http://localhost:5000/#/experiments/2/runs/f8f29d80796f4d16bdd5d370b8841c7c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-6 at: http://localhost:5000/#/experiments/2/runs/4375d6d11c8d495ab464919ef09f8661
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-7 at: http://localhost:5000/#/experiments/2/runs/5041f187be9a40378f384633a53d0024
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-8 at: http://localhost:5000/#/experiments/2/runs/57f2a225652145c8921fde6debc9d4c6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-9 at: http://localhost:5000/#/experiments/2/runs/646e816fc79a4555a31a7812fdd9169a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-10 at: http://localhost:5000/#/experiments/2/runs/c8e6d270ecea45818c0764fce8887337
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-11 at: http://localhost:5000/#/experiments/2/runs/319de4b1537541d5b2967170367c8a0c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-12 at: http://localhost:5000/#/experiments/2/runs/360e24618f72428c8cdeddc92a149042
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-13 at: http://localhost:5000/#/experiments/2/runs/90d75875faf3417aad81455fe7a9ea26
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-14 at: http://localhost:5000/#/experiments/2/runs/bb46385f4b0a435988678a9933baa058
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-15 at: http://localhost:5000/#/experiments/2/runs/dbe74c9cf1d1415eaf8004dd97b2570e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-16 at: http://localhost:5000/#/experiments/2/runs/ab5e214132d34fa68cc1bc161ceb174b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-17 at: http://localhost:5000/#/experiments/2/runs/8afc829c77244b4286aebb2bb2c19d30
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-18 at: http://localhost:5000/#/experiments/2/runs/70c98cd025984f5ead68aff858ee8c27
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-19 at: http://localhost:5000/#/experiments/2/runs/956043d4bb6a45639cd607fb1d2bfca1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-20 at: http://localhost:5000/#/experiments/2/runs/dd0b71735a50432f850b1c42e7f8a8fc
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-21 at: http://localhost:5000/#/experiments/2/runs/df7a1d2ec2ff4bd78fd014138442bf7c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-22 at: http://localhost:5000/#/experiments/2/runs/2d99c69ea79f4ad3bfce5687f7567af6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-23 at: http://localhost:5000/#/experiments/2/runs/b317f57ca0264520a6f8b3f008a536d4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-24 at: http://localhost:5000/#/experiments/2/runs/1927ef2eebf9404badbc279701566ad1
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-25 at: http://localhost:5000/#/experiments/2/runs/e98883aea804484ea8b3d26f14cbc0d0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-26 at: http://localhost:5000/#/experiments/2/runs/94b9c0d5e3144232a00fa3de136450bc
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-27 at: http://localhost:5000/#/experiments/2/runs/9b53bbf695794b3d87982c0bc2fbf187
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-28 at: http://localhost:5000/#/experiments/2/runs/c644355505574f01a2a312b9c8b82dbc
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_stationary-trial-29 at: http://localhost:5000/#/experiments/2/runs/ee5ce3c32a894655889c17d246a70d33
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-0 at: http://localhost:5000/#/experiments/2/runs/8a7607b0137e4a4c9dc7959be58b380d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-1 at: http://localhost:5000/#/experiments/2/runs/be4fc7b69b83459c9845c734dd7c5ba7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-2 at: http://localhost:5000/#/experiments/2/runs/7d0a2949e407496d8da7580171dd1383
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-3 at: http://localhost:5000/#/experiments/2/runs/1d9cf4925e154740aa243a6dde64c5a2
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-4 at: http://localhost:5000/#/experiments/2/runs/495c48e1b9da4fe5b09000f3f77c7312
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-5 at: http://localhost:5000/#/experiments/2/runs/9fb2be6a76d44ec2a0fa6c43c6b9b3bd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-6 at: http://localhost:5000/#/experiments/2/runs/4a350fc56d6143df81685a58f403fcbb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-7 at: http://localhost:5000/#/experiments/2/runs/2a84bac294f64085995edac7af9d50fa
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-8 at: http://localhost:5000/#/experiments/2/runs/a59349e1fb0a463798c42f5ce176f9a4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-9 at: http://localhost:5000/#/experiments/2/runs/ec0bc4387f4f487ba485fa8c4665c2ef
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-10 at: http://localhost:5000/#/experiments/2/runs/fe461c96fd384d5f889c49711622a3c6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-11 at: http://localhost:5000/#/experiments/2/runs/fd4d5646b7004bf1a495cfb42f98af61
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-12 at: http://localhost:5000/#/experiments/2/runs/01fc6078d7784c6daff6ebae95401abf
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-13 at: http://localhost:5000/#/experiments/2/runs/b3bed04b2fd842c3b408c65450f1d1ec
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-14 at: http://localhost:5000/#/experiments/2/runs/9104ebd6c2bb41bfa8c742b9ba203b2b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-15 at: http://localhost:5000/#/experiments/2/runs/a50182c9cf03419d9055a28238fc61a9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-16 at: http://localhost:5000/#/experiments/2/runs/922cdfa088a74cfbb3f3a8e61d5cd2e4
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-17 at: http://localhost:5000/#/experiments/2/runs/7ec4941bc5fe401a858baa42aefb8220
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-18 at: http://localhost:5000/#/experiments/2/runs/dbd0b7b1b0d64f5b86428cc9e5e58213
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-19 at: http://localhost:5000/#/experiments/2/runs/b726a707980a494ba875edd3da5831f0
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-20 at: http://localhost:5000/#/experiments/2/runs/bc73d0f5ed1c4e35a944da674670627f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-21 at: http://localhost:5000/#/experiments/2/runs/33f0ad8c20464cdf82bf17fece60115c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-22 at: http://localhost:5000/#/experiments/2/runs/fcc0bcfa472a4bd1ae0da7b09c8d6497
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-23 at: http://localhost:5000/#/experiments/2/runs/043ec016ddf54cf6aa54229703fdb792
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-24 at: http://localhost:5000/#/experiments/2/runs/5c39dcf1ce9f4e9aa5d90337573cc0ab
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-25 at: http://localhost:5000/#/experiments/2/runs/db578402a823467586efdd7ea986e27a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-26 at: http://localhost:5000/#/experiments/2/runs/7b1b826501da437dbe96f99e351ef079
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-27 at: http://localhost:5000/#/experiments/2/runs/5bca58ac97d54c4ab3c012d18757a611
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-28 at: http://localhost:5000/#/experiments/2/runs/941afcedd0b2489a82f5cb197e0bc511
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run month-global_mamba_all-trial-29 at: http://localhost:5000/#/experiments/2/runs/dc87b9d66c8a4834ba115572bb68347f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run 02d_mamba_forecasting-month at: http://localhost:5000/#/experiments/2/runs/e2052058bb49493bb4ab86b880fb1e8e
🧪 View experiment at: http://localhost:5000/#/experiments/2
=== Global Mamba strict protocol: month (21 trading days) ===

,profit_risk_utility,panel_sharpe,mean_ticker_sharpe,cumulative_return,max_drawdown,turnover,number_of_trades,validation_constraints_pass,long_threshold,model_name,selected_threshold,horizon_name,horizon,training_notebook,global_mamba_run
0,-1.944546,-2.697059,-1.762601,-0.016737,-0.028177,0.006570,109,True,0.020,global_mamba_stationary,0.02,month,21,02d_mamba_forecasting,True
1,-2.890604,-3.619696,-2.835948,-0.037835,-0.057433,0.007788,119,True,0.010,global_mamba_stationary,0.02,month,21,02d_mamba_forecasting,True
2,-3.659608,-5.030627,-3.286265,-0.061390,-0.078796,0.006602,105,True,0.005,global_mamba_stationary,0.02,month,21,02d_mamba_forecasting,True
3,-3.717968,-5.341993,-3.157050,-0.078436,-0.094386,0.007544,129,True,0.000,global_mamba_stationary,0.02,month,21,02d_mamba_forecasting,True
4,-1.301407,-1.141359,-1.599404,-0.008295,-0.022297,0.005557,82,True,0.020,global_mamba_all,0.02,month,21,02d_mamba_forecasting,True
5,-2.394318,-2.799030,-2.493505,-0.025331,-0.038754,0.005996,107,True,0.010,global_mamba_all,0.02,month,21,02d_mamba_forecasting,True
6,-2.852201,-3.706841,-2.718295,-0.037905,-0.052053,0.007008,128,True,0.005,global_mamba_all,0.02,month,21,02d_mamba_forecasting,True
7,-3.269545,-4.359815,-3.029056,-0.051402,-0.066949,0.006867,126,True,0.000,global_mamba_all,0.02,month,21,02d_mamba_forecasting,True

,profit_risk_utility,panel_sharpe,mean_ticker_sharpe,cumulative_return,max_drawdown,turnover,number_of_trades,validation_constraints_pass,long_threshold,model_name,selected_threshold,horizon_name,horizon,training_notebook,global_mamba_run,validation_rank,is_validation_selected
4,-1.301407,-1.141359,-1.599404,-0.008295,-0.022297,0.005557,82,True,0.020,global_mamba_all,0.02,month,21,02d_mamba_forecasting,True,1,True
0,-1.944546,-2.697059,-1.762601,-0.016737,-0.028177,0.006570,109,True,0.020,global_mamba_stationary,0.02,month,21,02d_mamba_forecasting,True,2,False
5,-2.394318,-2.799030,-2.493505,-0.025331,-0.038754,0.005996,107,True,0.010,global_mamba_all,0.02,month,21,02d_mamba_forecasting,True,3,False
6,-2.852201,-3.706841,-2.718295,-0.037905,-0.052053,0.007008,128,True,0.005,global_mamba_all,0.02,month,21,02d_mamba_forecasting,True,4,False
1,-2.890604,-3.619696,-2.835948,-0.037835,-0.057433,0.007788,119,True,0.010,global_mamba_stationary,0.02,month,21,02d_mamba_forecasting,True,5,False
7,-3.269545,-4.359815,-3.029056,-0.051402,-0.066949,0.006867,126,True,0.000,global_mamba_all,0.02,month,21,02d_mamba_forecasting,True,6,False
2,-3.659608,-5.030627,-3.286265,-0.061390,-0.078796,0.006602,105,True,0.005,global_mamba_stationary,0.02,month,21,02d_mamba_forecasting,True,7,False
3,-3.717968,-5.341993,-3.157050,-0.078436,-0.094386,0.007544,129,True,0.000,global_mamba_stationary,0.02,month,21,02d_mamba_forecasting,True,8,False

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning,long_threshold
0,0.031539,0.061073,0.009003,252.0,6.783312,18.987348,-0.003366,18.144355,0.003808,59,__panel__,global_mamba_stationary,overlapping_tranches,858,False,0.02
1,0.047171,0.091982,0.016001,252.0,5.748433,12.686301,-0.019615,4.689397,0.004470,77,__panel__,global_mamba_all,overlapping_tranches,858,False,0.02

,cumulative_return,annualized_return,annualized_volatility,periods_per_year,sharpe,sortino,max_drawdown,calmar,turnover,number_of_trades,ticker,model_name,signal_mode,n_rebalances,sample_warning,long_threshold
0,0.187614,0.410426,0.057750,252.0,7.106977,19.427225,-0.013949,29.423178,0.006425,17,CBOM,global_mamba_stationary,overlapping_tranches,126,False,0.02
1,-0.000234,-0.000568,0.000276,252.0,-2.057119,-0.552133,-0.000234,-2.422673,0.000916,2,MBNK,global_mamba_stationary,overlapping_tranches,104,False,0.02
2,0.000935,0.001871,0.001554,252.0,1.204481,11.503937,-0.000194,9.657105,0.002268,6,SBER,global_mamba_stationary,overlapping_tranches,126,False,0.02
3,0.000511,0.001022,0.000831,252.0,1.230955,NaN,-0.000071,14.312963,0.000756,2,SBERP,global_mamba_stationary,overlapping_tranches,126,False,0.02
4,-0.001655,-0.003361,0.002261,252.0,-1.486345,-0.197802,-0.001655,-2.030522,0.000768,2,SVCB,global_mamba_stationary,overlapping_tranches,124,False,0.02
5,0.017224,0.034744,0.009094,252.0,3.820371,4.277019,-0.001660,20.926464,0.005291,14,T,global_mamba_stationary,overlapping_tranches,126,False,0.02
6,0.020374,0.041163,0.020238,252.0,2.033912,1.537455,-0.007923,5.195559,0.006047,16,VTBR,global_mamba_stationary,overlapping_tranches,126,False,0.02
7,0.242941,0.544902,0.092504,252.0,5.890556,10.847200,-0.081362,6.697226,0.004157,11,CBOM,global_mamba_all,overlapping_tranches,126,False,0.02
8,-0.007938,-0.019125,0.014073,252.0,-1.359026,-1.360228,-0.026911,-0.710678,0.005495,12,MBNK,global_mamba_all,overlapping_tranches,104,False,0.02
9,0.022118,0.044726,0.007476,252.0,5.982875,31.571969,-0.000561,79.665518,0.004535,12,SBER,global_mamba_all,overlapping_tranches,126,False,0.02
10,0.017141,0.034575,0.006562,252.0,5.268976,94.234152,-0.000160,215.662586,0.003779,10,SBERP,global_mamba_all,overlapping_tranches,126,False,0.02
11,-0.063768,-0.125332,0.018569,252.0,-6.749682,-7.105299,-0.063768,-1.965417,0.002304,6,SVCB,global_mamba_all,overlapping_tranches,124,False,0.02
12,0.036942,0.075248,0.012638,252.0,5.954151,5.253548,-0.004420,17.025575,0.006047,16,T,global_mamba_all,overlapping_tranches,126,False,0.02
13,0.052568,0.107900,0.025305,252.0,4.263962,14.662391,-0.003087,34.949505,0.003779,10,VTBR,global_mamba_all,overlapping_tranches,126,False,0.02

,check,passed,details
0,global outer splits are available,True,split_rows=7
1,global validation predictions are available,True,rows=1716
2,global test predictions are available,True,rows=1716
3,global cutoffs are chronological,True,"global_validation_start=2025-08-08 00:00:00, g..."
4,ticker split dates are chronological,True,bad_rows=0
5,validation predictions match ticker split dates,True,"out_of_window=0, wrong_role=0"
6,test predictions match ticker split dates,True,"out_of_window=0, wrong_role=0"
7,validation model target dates end before globa...,True,overlap_rows=0
8,final refit target dates end before global tes...,True,overlap_rows=0
9,global final model payloads exist for test pre...,True,missing_models=0
10,test panel signal metrics are available,True,rows=2

## Comparison Handles

In [7]:
for horizon_name, result in global_mamba_results.items():
    print({
        "horizon": horizon_name,
        "reports_dir": display_path(result["reports_dir"]),
        "test_predictions": display_path(result["reports_dir"] / "test_predictions.parquet"),
        "test_panel_signal_metrics": display_path(result["reports_dir"] / "test_panel_signal_metrics.parquet"),
        "leakage_audit": display_path(result["reports_dir"] / "leakage_audit.parquet"),
    })

{'horizon': 'week', 'reports_dir': 'artifacts/horizons/week/global_mamba/strict_protocol/reports', 'test_predictions': 'artifacts/horizons/week/global_mamba/strict_protocol/reports/test_predictions.parquet', 'test_panel_signal_metrics': 'artifacts/horizons/week/global_mamba/strict_protocol/reports/test_panel_signal_metrics.parquet', 'leakage_audit': 'artifacts/horizons/week/global_mamba/strict_protocol/reports/leakage_audit.parquet'}
{'horizon': 'month', 'reports_dir': 'artifacts/horizons/month/global_mamba/strict_protocol/reports', 'test_predictions': 'artifacts/horizons/month/global_mamba/strict_protocol/reports/test_predictions.parquet', 'test_panel_signal_metrics': 'artifacts/horizons/month/global_mamba/strict_protocol/reports/test_panel_signal_metrics.parquet', 'leakage_audit': 'artifacts/horizons/month/global_mamba/strict_protocol/reports/leakage_audit.parquet'}